main/plugins/org.talend.core.runtime/mappings/mapping_Teradata.xml
https://jira.talendforge.org/browse/TDI-31335
=> TDI-31335: error Data Type "BF" does not match a Defined Type name.

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
=> TDQ-9051: fix No schema shows under db connection when create context

main/plugins/org.talend.utils/pom.xml, main/plugins/pom.xml
To satisfy dependency of downstream DQ projects
=> Upgrade pom version to 5.5.3-SNAPSHOT

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/BigDataNode.java
Replace the break by continue.
=> Fix the setKeyList issue when the first element of a table is not checked

main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml
https://jira.talendforge.org/browse/TDI-32092
=> TDI-32092: Dynamic Schema doesn't work with mysql TEXT type

main/plugins/org.talend.librariesmanager/resources/java/routines/system/StringUtils.java
Introduce new split function to handle direct byte buffers and apply encoding rules to handle mixed encoded record (ex: ISO-8859-15 + UTF-8)
=> [TBD-1238]

main/plugins/org.talend.librariesmanager/resources/java/sqltemplates/Vertica/VerticaMergeInsert.sqltemplate, main/plugins/org.talend.librariesmanager/resources/java/sqltemplates/Vertica/VerticaMergeUpdate.sqltemplate
https://jira.talendforge.org/browse/TDI-29444
=> TDI-29444: Support for SQL Templates in Vertica

main/plugins/org.talend.core.runtime/mappings/mapping_Teradata.xml
add a mapping to talend boolean type for teradata
=> TDI-32044: Add new component Teradata SCD

main/plugins/org.talend.librariesmanager/resources/java/routines/system/StringUtils.java
can't use any SQL expression in the ELTMap otherwise it corrupts the SQL
Generated
https://jira.talendforge.org/browse/TDI-32594
=> TDI-32594: If UPDATE is used in any of our ELTOutput component : you

org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbstractNode.java, org.talend.librariesmanager/resources/java/routines/system/TalendThread.java
execution on iterations within the same subjob(TDI-30996)
=> TPS-952: [5.5.1]Duplicate variable names when enabling parallel

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/utils/MetadataConnectionUtils.java
=> TDQ-10412: fix Cannot Open ‘Indicator Selection’ in Column Analysis of

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ITDQRepositoryService.java
=> TDQ-10553 use TP_DM license,there is no profiling perspective

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
split the big method chaining to several parts
=> TDI-33066: TUJ failed BugTDI_6890_tFileOutputPositional stackoverflow

main/plugins/org.talend.core.repository/src/main/java/org/talend/repository/ui/actions/DeleteAction.java
Pls merge this update to resovle the issue.
=> TESB-14910:Route Builder: Cannot delete empty Code folders

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
use string literal instead of too many append() method
=> TDI-33301: tHashInput_1Process(Map<String,Object>) is exceeding the 65535 bytes limit when we checked option activate log4j in components

main/plugins/org.talend.core.runtime/mappings/mapping_Ingres.xml
https://jira.talendforge.org/browse/TDI-27730
=> TDI-27730: New version of Ingres iijdbc-file available

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/ComponentUtilities.java
modification
https://jira.talendforge.org/browse/TDI-33532
=> TDI-33532: Should have a migration task for reject row for TDI-32161

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/DqRepositoryViewService.java, test/plugins/org.talend.metadata.managment.test/src/org/talend/core/model/metadata/builder/database/DqRepositoryViewServiceTest.java
connection, only unfolder the connection node do persistence
this to fix run connection get wrong tables result
=> TDQ-10616: fix run connection analysis will not persistence data to

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/DqRepositoryViewService.java, test/plugins/org.talend.metadata.managment.test/src/org/talend/core/model/metadata/builder/database/DqRepositoryViewServiceTest.java
=> TDQ-10616: fix DQ - Profiling - Catalog Analysis - missing tables in

main/plugins/org.talend.librariesmanager/resources/java/routines/DataOperation.java, main/plugins/org.talend.librariesmanager/resources/java/routines/Mathematical.java, main/plugins/org.talend.librariesmanager/resources/java/routines/Numeric.java, main/plugins/org.talend.librariesmanager/resources/java/routines/Relational.java, main/plugins/org.talend.librariesmanager/resources/java/routines/TalendDate.java, main/plugins/org.talend.librariesmanager/resources/java/routines/TalendString.java
https://jira.talendforge.org/browse/TDI-32659
=> TDI-32659: Tmap:the function "Talenddate"-"diffdate" is not correct

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/ProcessUtils.java
I need this modification in order to use "getAssertAmount" on my spark jobs.
=> [TBD-2548] Compatibility of tests case with spark jobs.

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/utils/CheatSheetPerspectiveAdapter.java, main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/utils/CheatSheetUtils.java
=> TDQ-10433 fix after performing sth. on the max cheat sheet, it should be

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
=> TDQ-11192: Update description in routine generation dialog of

main/plugins/org.talend.model/src/main/java/org/talend/cwm/helper/ConnectionHelper.java
=> TDQ-11026: fix the getTdDataProvider method to support database

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/PluginChecker.java
Added property and method to check component is running in TIPASS env.
=> TIPAAS-6691:tActionFailure component

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
please help to merge . thanks!
=>  TDQ-11125 TOP doesn't have IComponentsService.avoid NPE.

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
please merge it to Talend maintenance 6.0 .thanks.
=> TDQ-11125 TOP doesn't have IComponentsService.avoid NPE.

main/plugins/org.talend.libraries.apache.cxf/build.properties
https://jira.talendforge.org/browse/TUP-3957
Note:Add new cxf jar
=> TUP-3957: [5.6.3 only] Upgrade to CXF 2.7.18

main/plugins/org.talend.librariesmanager/resources/java/routines/system/ComponentRuntimeContainerBase.java
[Need modify code out of "components" repository]
https://jira.talendforge.org/browse/TDI-35107
=> TDI-35107: New Salesforce components "Use this connection" doesn't work

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/EParameterFieldType.java
I had pushed the modification of " remove org.talend.component top-level package" to remote branch , need help to review the code and merge to master .
=> TUP-3843:fix a problem about the password controller , change to hidden text type(TUP-4010)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/ComponentServiceWithValueEvaluator.java
TUP-3843:fix a compilation error on org.talend.core.runtime(due to component API changes)(TUP-4010)
=> TUP-3843:fix a compilation error on org.talend.core.runtime(due to component API changes)(TUP-4010)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java
=> ITDI-35132:tAccessInput throws OOM when retrieve tables with big size

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/ITestContainerProviderService.java
test case and job stops building
=> TUP-4222:Change in context value does not get updated in the job and

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/IHadoopClusterService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/repository/HadoopRepositoryUtil.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ExtendedNodeConnectionContextUtils.java
=> TBD-3368:The Cloudera Navigator parameters are not set to component when

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
=> TDI-35737:Job cann't be deleted when it has test cases and don't in any

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/CopyObjectAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DuplicateAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ConvertJobsUtil.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/ITestContainerProviderService.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/process/EditProcessPropertiesWizard.java, test/plugins/org.talend.core.repository.test/src/org/talend/repository/utils/ConvertJobsUtilTest.java
=> TBD-3255:Should not remove the test case when doing convert between

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
"General JDBC"DB by setting the driver jar with absolute path
=> TUP-4287:Run column Analysis of "General JDBC" failed when connected the

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DeleteAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/view/RepositoryLabelProvider.java
=> [TDI-36018] Component Framework :Salesforce: folder error under

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/TalendProcessArgumentConstant.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IRemoteRunService.java, main/plugins/org.talend.core/src/main/java/org/talend/core/services/ICommandlineClientService.java
=> TDI-35506:[6.0.1] Studio distant run missing trace information with

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/gmf/draw2d/AnimatableZoomManager.java
=> TDI-35569:zoom out within job designer does not work as expected in

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/view/RepositoryLabelProvider.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/images/CoreImageProvider.java
=> [TDI-36030] Component Framework :Salesforce:R-click-menu-impact analysis

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/conf/EHadoopConfProperties.java
not mapping correctly(TBD-3267)
=> TPS-1338:[6.1.1] Import CDH config files with HDFS & RM HA information

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/XmiResourceManager.java, main/plugins/org.talend.repository.localprovider/src/main/java/messages.properties, main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
=> TUP-4082:NullPointerException triggered by connection items caused the

main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ApplicationWorkbenchWindowAdvisor.java
https://jira.talendforge.org/browse/TDI-36083
=> TDI-36083 fix: Studio main window hides, but the process is still there.

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/NexusServerUtils.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/talendlib/TalendLibsServerManager.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java, test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/model/service/LocalLibraryManagerTest.java
=> TUP-4607:LocalLibraryManager resolve jar can not work with modules with

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/CopyObjectAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DuplicateAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ConvertJobsUtil.java
=> TDI-36011:Duplicate job with testcase, job can duplicate, testcase can't

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportExportHandlersRegistryReader.java
https://jira.talendforge.org/browse/TUP-4604
=> TUP-4604 fix: Studio blocked while switching to Git Merge perspective

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
=> TDI-36328:JDBC URL change to jdbc:xxx://<xxx>:<xxx> when reopen a

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ArtifactsDeployer.java
nullorg/talend/libraries/hadoop-mapreduce-client-common-2.0.0-cdh4.4.0/6.0.0-SNAPSHOT/hadoop-mapreduce-client-common-2.0.0-cdh4.4.0-6.0.0-SNAPSHOT.pom
=> TUP-4630:error in the Studio log - just after starting it no protocol:

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IMavenUIService.java, main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/MavenUIService.java
=> TUP-4492:Unable to install Studio Patch if maven config exists :

main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IRunProcessService.java
=> TDI-35608:Publish standalone job with compilation error finished

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
=> TUP-4778:buildProjectSources:Only export job pom that don't have test

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java
=> TBD-3510：Redshift wizard: don't have Addtional JDBC Parameter filed but

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/SVNConstant.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
project' using CommandLine creates incomplete archive without errors
=> TUP-4420:[6.0.1] Building a Job for a project that uses a 'Reference

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java
=> TDI-35315: Context variable name changed, should be consistent when drag

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/ISAPConstant.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/command/RepositoryChangeMetadataForSAPBapi.java
metadata retrieve the bapi function with CHANING element
=> TDI-35841:talend metadata treat CHANGING element wrongly when talend

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/gmf/draw2d/AnimatableZoomManager.java
=> TDI-35007:positioning of drag and drop objects on designer space in

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/ITestContainerProviderService.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/wizard/models/ImportNodesBuilder.java
version,if import this job will remindor have same id for testcase
=> TUP-4846:TestCase: when job has testcase and job has different

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
=> TBD-3644:tSqoopXX -> Selecting a JDBC metadata loses the DB_VERSION of

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java, main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/relationship/RelationshipItemBuilderTest.java
=> TUP-4175：Export with dependencies fails to select (and export)

main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
=> TDI-35941:RecycleBin: Cannot restore job after deleting subfolder and

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/ITestContainerProviderService.java, main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
=> TUP-4482:All versions of same TestCase are built/tested for one version

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
=> TUP-4921:No pom available for the artifact once download a jar from a

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/ProcessUtils.java
Please review if this modification is ok. if it is ok, please help to merge .
Thanks!
=> TDQ-12162 avoid to miss dependencies for multilevel dependency.

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
download sub window for Hadoop cluster
=> TUP-4942:Studio Installer&Talend-Tools-Installer:Have duplicate jar on

test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/relationship/RelationshipItemBuilderTest.java
=> Remove mock codes

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/OtherConnectionContextUtils.java
=> TDI-36774: Fail to retrieve sap table/sap bw schema after export sap

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/InitializeMissingJarHandler.java
please review this commit. if it is ok,please merge it . 
Thanks!
=> TUP-4968 replace 'url.toURI(url)' with 'URIUtil.toURI(url)',make it support a path with special chars(like as space).

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryNodeUtilities.java
=> TDI-36770: fix repository node Utilities to retrieve from the view directly

main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/codegen/AbstractRoutineSynchronizer.java
TDI-35810:When log on Main project can not open referrence project's system routines.
=> TDI-35810:When log on Main project can not open referrence project's system routines.

main/plugins/org.talend.core/src/main/java/org/talend/core/branding/DefaultBrandingConfiguration.java
Hello, I added the Spring View Id as a placeholder in the bottom area, for the '*' placeholder is not work. The Spring View is for ESB route.
Thanks,
=> TESB-17301: Open Spring view at the bottom area

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/ProcessUtils.java
please review this code. merge it to Talend if it is ok.
Thanks!
=> TDQ-12325 should contain joblet related dependencies.

main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java
context.password+context.token
https://jira.talendforge.org/browse/TUP-5010
=> TUP-5010 fix: Password field show *** when using

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryNode.java
https://jira.talendforge.org/browse/TUP-5048
=> TUP-5048 fix: GIT: Reference Project doesn't show if logon MainProject/non-refbranch, then switch to refbranch

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
https://jira.talendforge.org/browse/TUP-5020
Refact GitHandler
=> TUP-5020 fix: Wrong commit in specified case

main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
=> TDI-36886: Update a context parameter will make the studio blocked on a

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IDbMapService.java
=> TDI-35297: tELTPostgressqlMap not functioning on other schemas apart

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/DBConnectionContextUtils.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
https://jira.talendforge.org/browse/TBD-3909
=> TBD-3909 fix: Impala principal is not contained in the exported context.

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/DBConnectionContextUtils.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
and Impala principal text box can not be edited after exported context.
when we click revert button,Impala principal text box should return
original value.
https://jira.talendforge.org/browse/TBD-3909
=> TBD-3909 fix: Impala principal is not contained in the exported context

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/JobInfoProperties.java
TDI-27409:Unable to export a job via TIS Studio with statistics enable
=> TDI-27409:Unable to export a job via TIS Studio with statistics enable

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
tables
https://jira.talendforge.org/browse/TDI-36954
=> TDI-36954 fix:Database metadata wizard mix up columns from different

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java
=> TUP-5136: Importing context group doesn't propagate changes to the jobs

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IODataComponentContainer.java
not sure how user made in and out connections with same unique name, can't reproduce. not possible to add migration task for this because we don't know  former unique name, so just add more condition for the judgement to get the right one.
=> TDI-36621: Always ask propagate enven sync the schema on tELTHiveMap.

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
--do update
https://jira.talendforge.org/browse/TBD-3744
=> TBD-3744 fix: Mapr 410&401: Missing Authentication option on hive wizard

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataTable.java
order.
https://jira.talendforge.org/browse/TDI-37079
=> TDI-37079 fix: after reopen job, can not change the schema's  column

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/ui/actions/metadata/ReadTableAction.java
"detect dependencies" do not work correctly.
=> TDI-36036: For columns under schemas, the r-click menu "read schema" and

main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
element make the studio too slow
=> TDI-37109:sap connection item have lots of <description href="#..."/>

main/plugins/org.talend.core.runtime/src/main/java/org/talend/commons/utils/io/FilesUtils.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenBundleTemplatePom.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/TalendCodeProjectUtil.java
for review first.
Need to check some other parts first on commandline
=> TDI-36930: Improve performances during the build

main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/database/EXASOLDatabaseMetaData.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/MDMConnectionFillerImpl.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/MetadataFillerImpl.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/SybaseConnectionFillerImpl.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/utils/MetadataConnectionUtils.java
please help to review the code and merge to master. thanks!
=> TDQ-12219 make the schema filter on Exasol works;display the correct

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
https://jira.talendforge.org/browse/TUP-4807
=> TUP-4807 fix: The text is not right when try to delete locked test case

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableWizard.java
=> TDI-37120: Edit schema which used in job, will hang on "Progress

main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/MDMForm.java
had merged some change to master directly and backport to other branch , MDM had done about implement the service .
=> TDI-37001:Create MDM MetaData Connection to SSL MDM server failed

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/seeker/AbstractRepoViewSeeker.java
"built-in" to "repositoy", then click "schema", the new schema will not
loaded, display the old schema list studio will throw NPE error logs.
=> TUP-5212:Git merge editor: tLogrow-prameter,if change property type from

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
the impala component has that
https://jira.talendforge.org/browse/TBD-2948
=> TBD-2948 fix: The impala wizard does not have the username filed, but

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
https://jira.talendforge.org/browse/TDI-37139
=> TDI-37139 fix: SQLite connection can not get columns.

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TUP-14715
=> TUP-14715 fix:Adapt to the changes of driver for DB2

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/dialog/PastSelectorDialog.java
not find its parent version job
=> TUP-5552：Studio will pop up NPE error when select a testcase which can

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/EParameterFieldType.java
And fix the layout problem of Text, Combo, Checkbox, File, Table
controllers in the wizard at the same time.
=> TUP-5252: add JSON_TABLE controller which is a table with json input.

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
cluster
https://jira.talendforge.org/browse/TBD-3987
=> TBD-3987 fix: Impala:Cann't check successfully when I use custom hadoop

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
=> TUP-5410:[Studio] MS SQL Server: Azure SQL (2016) support and 2014

main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/exception/ExceptionMessageDialog.java
https://jira.talendforge.org/browse/TUP-5207
=> TUP-5207 fix: GIT commits on every save in local mode

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/wizard/models/ImportNodesBuilder.java
https://jira.talendforge.org/browse/TUP-5285
=> TUP-5285 fix: Error version conflict in git merge editor.

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/OtherConnectionContextUtils.java
- Add back the old MDM constants
=> TMDM-9764 Give the ability to export as a context a Talend MDM connection

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/TalendProcessArgumentConstant.java
Add new argument constant for TESB-17856
=> TESB-17856: ESB Microservice can be exported only with Default context

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/EDatabaseTypeName.java, test/plugins/org.talend.metadata.managment.ui.test/src/main/test/org/talend/metadata/managment/ui/model/ProjectNodeHelperTest.java
=> TUP-5698: Studio becomes unresponsive when Adding a Schema to a db2 z/OS

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/ui/actions/metadata/AbstractCreateTableAction.java
https://jira.talendforge.org/browse/TUP-15988
=> TUP-15988 fix: Hive Metadata Wizard Does Not User Additional Parameters

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/AbstractRepositoryContentHandler.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/IRepositoryContentHandler.java, main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java, main/plugins/org.talend.repository.view.example/src/org/talend/repository/example/viewer/handler/demo/ExampleDemoRepositoryHandler.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/migration/ContextItem2JobDocExtContentHandler.java
duplicated and duplited item was deleted forever on Recycle bin
=> TUP-15953：Spark/spark str joblet content will be empty when it was

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolAvroHelper.java
https://jira.talendforge.org/browse/TDI-37525
=> TDI-37525: Add support document type in new framework

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialog.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/DownloadModuleRunnable.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/nexus/NexusDownloader.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ArtifactsDeployer.java, test/plugins/org.talend.designer.maven.test/src/test/java/org/talend/designer/maven/utils/PomUtilTest.java
=> TUP-16013:download jar ended with no response when build job, and need

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
hadoop), when export, check dependencies cann't checked used joblet and
hadoop
=> TUP-15822：For imported spark streaming job(used joblet and repository

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
=> TUP-16057 fix:Use name is set wrongly when import MapR 52 Ticket MapRDB

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java, main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-5593
=> TUP-5593 fix> GIT:can't export dependencies metadata when job version is updated

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/PropertiesWizardPage.java
=> TUP-16021: NPE error shows if Click Finish on "Create/Reuse a context

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
when hadoop cluster is on context mode.
=> TUP-16056: HDP 25 kerberos:Hive,Hbase context cann't check successfully

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/DBConnectionContextUtils.java
cluster(Mapr 52 ticket) is on context mode.
=> TUP-16092: MaprDB:revert cotext for it,password is missed when hadoop

main/plugins/org.talend.platform.logging/src/log4j.xml
=> TUP-16024:local nexus username password in clear text in studio .log

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
=> TESB-18091:<Copy to Branch> There will be an error when open a resource

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
https://jira.talendforge.org/browse/TUP-16129
=> TUP-16129 fix: Distribution shows wrong when importing a repository MapR 51 Impala item to component

main/plugins/org.talend.core/src/main/java/org/talend/core/model/metadata/QueryUtil.java, main/plugins/org.talend.core/src/main/java/org/talend/core/model/metadata/query/GenerateQueryFactory.java, main/plugins/org.talend.core/src/main/java/org/talend/core/model/metadata/query/generator/ImpalaQueryGenerator.java, test/plugins/org.talend.core.test/src/org/talend/core/model/metadata/query/generator/ImpalaQueryGeneratorTest.java
=> TUP-16122: Have a compile error for query when Impala with kerberos

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/prefs/SSLPreferenceConstants.java
Preparation SSL to Talend/SSL to be a common setting
=> TUP-15918:Move the preference page Talend/Specific Settings/Data

main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonViewer.java
https://jira.talendforge.org/browse/TUP-16164
=> TUP-16164 fix: Studio freezes caused by native WinNTFileSystem.getBooleanAttributes

main/plugins/org.talend.model/model/TalendFile.ecore, main/plugins/org.talend.model/model/TalendFile.genmodel, main/plugins/org.talend.model/src/main/java/org/talend/designer/core/model/utils/emf/talendfile/ElementValueType.java, main/plugins/org.talend.model/src/main/java/org/talend/designer/core/model/utils/emf/talendfile/TalendFilePackage.java, main/plugins/org.talend.model/src/main/java/org/talend/designer/core/model/utils/emf/talendfile/impl/ElementValueTypeImpl.java, main/plugins/org.talend.model/src/main/java/org/talend/designer/core/model/utils/emf/talendfile/impl/TalendFilePackageImpl.java
https://jira.talendforge.org/browse/TUP-7147
=> TUP-7147 Fix:[5.6.1] Special characters when used within a component cause job to dont open properly

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/i18n/messages.properties, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DeleteAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/EmptyRecycleBinAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/dialog/ItemReferenceDialog.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
https://jira.talendforge.org/browse/TUP-16186
=> TUP-16186 fix: Can not delete jobs which have been used in other job.

main/plugins/org.talend.librariesmanager/resources/java/routines/system/ParserUtils.java
https://jira.talendforge.org/browse/TDI-37596
=> TDI-37596: tExtractDelimitedFields outputs "null" as the errorMessage on the reject path when schema is BigDecimal

main/plugins/org.talend.librariesmanager/resources/java/routines/system/TypeConvert.java
https://jira.talendforge.org/browse/TDI-37739
=> TDI-37739 : tMap: type converter errors are not expressive enough

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/repository/RepositoryComponentManager.java
be deleted from the referencing project
=> TUP-15926：Joblet with the same name as in the referenced project cannot

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/XmlFileStep2Form.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/dnd/XmlToSchemaDragAndDropHandler.java
context" to replace parameter failed
=> TUP-5777 fix:Create xml file select "Reuse an existing repository

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/XmiResourceManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/JobContextManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java, main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/cache/RepositoryObjectCache.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/model/ImportItem.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/manager/ChangeIdManager.java, main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-16073
=> TUP-16073 fix: Importing duplicated job causes wrong subjob referenced in tRunJob

main/plugins/org.talend.librariesmanager.ui/src/main/java/messages.properties, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/actions/ImportExternalJarAction.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialog.java
=> TUP-16309:Jar selection for the modules expect to have the exact name

main/plugins/org.talend.librariesmanager/resources/java/routines/system/TypeConvert.java
https://jira.talendforge.org/browse/TDI-37741
=> TDI-37741: Automatic Type Conversion from Object to byte/short/int/long/..... issue

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DuplicateAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ConvertJobsUtil.java
by spark job with test case to Spark back.
=> TUP-15118：A wrong warning shown when convert MR job which is converted

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TDI-37116
Change the jar needed when View Database
=> TDI-37116 : Upgrade exajdbc-5.0.12.jar to exajdbc-5.0.13.jar

main/plugins/org.talend.core.repository/plugin.xml, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/handlers/RouteParameterRelationshipHandler.java
=> TESB-18096:<Copy to Branch> when copy to branch with checking "select dependencies", the dependency is not selected automatically

main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/ContextOrderProperties.java
=> TUP-16393:Run testcase failed and throw unexpected

main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/swt/tableviewer/TableViewerCreatorNotModifiable.java
=> TUP-16298：[5.6.2]Problems copying values of cSetHeader components

main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/rowgenerator/data/Function.java
=> TUP-5658 fix:Error when run job trowgenerator to tlogrow with check and

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/INOSQLService.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ExtendedNodeConnectionContextUtils.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/context/AbstractRepositoryContextHandler.java
=> TUP-15459: Mongodb replica set: when convert it to context,replica

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/SchemaCellEditor.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/dialog/MetadataDialog.java
=> TUP-16433: All Schema Columns in Component are wrong after editing

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/DiSchemaConstants.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolAvroHelper.java
See corresponding change in Daikon. No tests provided because there is not a unit test framework for this as far as I know.
=> TDI-37709 Date/Time issues

main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/swt/tableviewer/TableViewerCreatorNotModifiable.java, main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/swt/tableviewer/tableeditor/TableEditorManager.java
TUP-16262 Opening schema is very slow using Talend studio 6.2
https://jira.talendforge.org/browse/TUP-16262
=> TUP-16262 Fix Opening schema is very slow using Talend studio 6.2

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/context/MetadataContextPropertyValueEvaluator.java
=> TUP-16441: Issue with opening job with context group in Salesforce

main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/managers/FileResourcesUnityManager.java
https://jira.talendforge.org/browse/TUP-16473
=> TUP-16473 fix: Cannot get correct status after "importItems" in commandline

main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/managers/FileResourcesUnityManager.java
Reverts Talend/tcommon-studio-se#769
=> Revert "TUP-16473 fix: Cannot get correct status after "importItems" in commandline"

main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
TUP-16458 projects not retrieved correctly when do refresh on logon window
https://jira.talendforge.org/browse/TUP-16458
=> TUP-16458 projects not retrieved correctly when do refresh on logon window

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ILibraryManagerService.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/nexus/NexusDownloadHelperWithProgress.java
=> TUP-16557:Local download of jar doesn't update the status of jar

main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
=> TUP-16604: Always need to restart studio when changing workspace

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ITDQSurvivorshipService.java
tRuleSurvivorship node when export job
=> TDQ-13026 consider the sub-job and joblet dependecies wherether include

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/services/IGitContentService.java
https://jira.talendforge.org/browse/TUP-16444
=> TUP-16444 fix> JobScript: Cannot edit new jobscript on GIT Project(Manual, UnLock Items)

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/ProcessorDependenciesManager.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/SortableDependency.java
=> TESB-18147:java.lang.NoSuchMethodError:org.springframework.core.MethodParameter.getContainingClass()

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/cmd/MergeContextVariablesCommand.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java
=> TUP-16671:AMC database repository connect doesn't grab all context

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DuplicateAction.java
TUP-16472 Then icon will not change directly when converting between MR and Spark job by duplicate
https://jira.talendforge.org/browse/TUP-16472
=> TUP-16472 Then icon will not change directly when converting between MR and Spark job by duplicate

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/editor/JobEditorInput.java
=> TUP-5873：Ref project job's jobscript can be modified when logon main

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
bugfix/6.4.0/TUP-14737_too_slowly_when_import_items_using_overwrite_to svn/git_project(Fix_compiler_error_for_CI)
https://jira.talendforge.org/browse/TUP-14737
=> bugfix/6.4.0/TUP-14737_too_slowly_when_import_items_using_overwrite_to svn/git_project(Fix_compiler_error_for_CI)

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/excel/ExcelFileStep1Form.java
=> TUP-16746: Excel file metadata : Error "Unable to recognize OLE stream"

main/plugins/org.talend.core.runtime/mappings/mapping_AS400.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Access.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Firebird.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Greenplum.xml, main/plugins/org.talend.core.runtime/mappings/mapping_H2.xml, main/plugins/org.talend.core.runtime/mappings/mapping_HSQLDB.xml, main/plugins/org.talend.core.runtime/mappings/mapping_IBMDB2.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Informix.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Ingres.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Interbase.xml, main/plugins/org.talend.core.runtime/mappings/mapping_JavaDB.xml, main/plugins/org.talend.core.runtime/mappings/mapping_MsOdbc.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml, main/plugins/org.talend.core.runtime/mappings/mapping_ParAccel.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Postgres.xml, main/plugins/org.talend.core.runtime/mappings/mapping_PostgresPlus.xml, main/plugins/org.talend.core.runtime/mappings/mapping_SQLite.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Sybase.xml, main/plugins/org.talend.core.runtime/mappings/mapping_VectorWise.xml, main/plugins/org.talend.core.runtime/mappings/mapping_Vertica.xml
https://jira.talendforge.org/browse/TDI-36295
=> TDI-36295 : data type mapping: wrong DB->Java mapping

main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
=> bug fixed TDQ-13229 restart TOS_DQ studio, then create analysis, can not

main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java, test/plugins/org.talend.core.test/src/org/talend/core/model/utils/TalendTextUtilsTest.java
=> TUP-16318:Password field in connection components should not mask global

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
https://jira.talendforge.org/browse/TDI-37755
=> TDI-37755: Add a common method to remove LineSeparator in MEMO.

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/view/RepositoryLabelProvider.java
=> TUP-15911:Offline Mode: Lock Icon and ">" doesn't show after editing

main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
* Add snowflake component to studio repository.
=> feat(TDI-38068): integrate snowflake component

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
right cliking hadoop cluster hdp2.0
=> TUP-16492:No standalone value shows for "Hive Model" when create hive by

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
Reverts Talend/tcommon-studio-se#845
=> Revert "TDI-37755: Add a common method to remove LineSeparator in MEMO."

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/AbstractEMFRepositoryFactory.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/IRepositoryFactory.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
TUP-17108 Git:after check out as local, studio can't be used
https://jira.talendforge.org/browse/TUP-17108
=> Bugfix/6.4.0/tup 17108 git after check out as local,studio can't be used

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
TUP-17109 Git: can't switch to new branch
https://jira.talendforge.org/browse/TUP-17109
=> TUP-17109 Git: can't switch to new branch

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/excel/ExcelFileStep1Form.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/excel/ExcelReader.java
Reverts Talend/tcommon-studio-se#861
=> Revert "TUP-16710:Update Excel components to support Excel 2016/next version"

main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml, main/plugins/org.talend.designer.maven.tos/resources/unzip/pom.xml, pom.xml
=> DEVOPS-1729 Nexus migration: Update URLs [master]

main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml, main/plugins/org.talend.designer.maven.tos/resources/unzip/pom.xml, pom.xml
=> DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.3]

main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml, main/plugins/org.talend.designer.maven.tos/resources/unzip/pom.xml, pom.xml
=> DEVOPS-1729 Nexus migration: Update URLs [maintenance/6.2]

pom.xml
=> DEVOPS-1729 Nexus migration: Update URLs [patch/6.0.1]

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/ExtractManager.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/dbs/OracleExtractManager.java
=> TUP-17049:Retrieve Schema not always updates schema after TABLE

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponentsFactory.java
=> TUP-17201:Upgrade issue with Jobs referencing joblets from a reference

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java, main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java, test/plugins/org.talend.core.runtime.test/src/org/talend/repository/ProjectManagerTest.java
TUP-16722 Need to simplify the branch creation of reference projects on Git Local(Support TAC)
https://jira.talendforge.org/browse/TUP-16722
=> TUP-16722 Need to simplify the branch creation of reference projects on Git Local(Support TAC)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TDI-37831
=> TDI-37831:Add Support for ExaSol 6

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/tableviewer/TableViewerCreator.java, main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/tableviewer/behavior/DefaultCellModifier.java
TUP-6549 tFixFlowInput on the Ubuntu job:show an error when I click add button before add schema
https://jira.talendforge.org/browse/TUP-6549
=> TUP-6549 tFixFlowInput on the Ubuntu job:show an error when I click add button before add schema

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java, test/plugins/org.talend.core.runtime.test/src/org/talend/repository/ProjectManagerTest.java
TUP-16722 Need to simplify the branch creation of reference projects on Git Local/TUP-17280
Review text of popup when push branch
https://jira.talendforge.org/browse/TUP-16722
=> TUP-17280 Review text of popup when push branch

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TDI-38429
=> TDI-38429:Correct the wrong jar name.

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ITDQPatternService.java
Repository pattern type get error dialog, job can not run--on windows
=> TDQ-13484 open job with tPatternCheck and tPatternExtract which select

main/plugins/org.talend.librariesmanager/resources/java/routines/system/TalendDataSource.java
=> TESB-18908:Memory-Leak in TalendDataSource implementation

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/version/EHadoopDistributions.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/ProcessUtils.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
Google dataproc need to have the contexts  files integrated to the jars.
This PR will allow the code generator to do that.
=> feat(TBD-4707): Add Google Dataproc distribution and its context support

main/plugins/org.talend.registration/content/talendForgeDiage.html
=> TUP-17244:Field for input username to connect to Talend Exchange does

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/extension/AbstractRepository4ProcessUpdateManagerProvider.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/extension/AbstractRepositoryUpdateManagerProvider.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/extension/IRepositoryUpdateManagerProvider.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/extension/UpdateManagerProviderDetector.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/relationship/RelationshipItemBuilderTest.java
=> TUP-17248:Faulty impact analysis and detect dependencies on joblets

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
TUP-16722 Need to simplify the branch creation of reference projects(Fix a NPE problem)
https://jira.talendforge.org/browse/TUP-16722
=> TUP-16722 Need to simplify the branch creation of reference projects(Fix a NPE problem)

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java, main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonViewer.java, main/plugins/org.talend.repository.view/src/org/talend/repository/viewer/content/listener/ResourcePostChangeRunnableListener.java
https://jira.talendforge.org/browse/TUP-17217
=> TUP-17217 fix: Hive table is not shown at once when retrieve schema for Hive

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/HadoopConstants.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/IHadoopClusterService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/repository/HadoopRepositoryUtil.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ModuleNeeded.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IMetadataManagmentUiService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IRunProcessService.java, main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/MetadataManagmentUiService.java
feat(TUP-16698): revert feature TUP-16698
=> Revert "Feature/6.4/tup 16698 support context for hadoop conf jar (#894)"

main/plugins/org.talend.core.runtime/mappings/mapping_MicrosoftCrm_odata.xml
* add new mapping for microsoft crm 2016 odata
This is a mapping between java and odata web api type
refer to https://msdn.microsoft.com/en-us/library/mt607990.aspx#bkmk_properties
=> feat(TDI-38091):Support Microsoft CRM online 365/2016 - ODATA

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
https://jira.talendforge.org/browse/TUP-17442
=> TUP-17442: Wrong orders for sybase db version.

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ExtensionModuleManager.java
=> TUP-17505:Jars could be retrieved as SNAPSHOT even if defined in the

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/excel/ExcelFileStep1Form.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/excel/ExcelReader.java
=> feat(TUP-16710/hwang):Update Excel components to support Excel 2016/next

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/CheckJobDeleteReference.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/CheckJobletDeleteReference.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DeleteAction.java
fix(TUP-17422/hwang):Job lost the related joblet, after empty recycle
=> fix(TUP-17422/hwang):Job lost the related joblet, after empty recycle

main/plugins/org.talend.librariesmanager/resources/java/routines/Relational.java, main/plugins/org.talend.librariesmanager/resources/java/routines/StringHandling.java, main/plugins/org.talend.librariesmanager/resources/java/routines/TalendDate.java, main/plugins/org.talend.librariesmanager/resources/java/routines/TalendStringUtil.java
https://jira.talendforge.org/browse/TDI-38412
=> TDI-38412:Refactor the code of conversion functions.

main/plugins/org.talend.libraries.mdm.webservice.ce/pom.xml
Reverts Talend/tcommon-studio-se#952
=> Revert "DEVOPS-1222: Pull MDM CE Webservice stub artifacts from Nexus during …"

main/plugins/org.talend.osgi.lib.loader/src/org/talend/osgi/hook/MissingJarBundleFileWrapper.java
org.ops4j.pax.url.mvn.MavenResolver not loaded
=> TUP-17411 : do not crash stusio when service

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
=> TUP-17530: missing many default stuido jar when using global maven

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
TUP-17412 Remote Runs from Studio Display Project Setting Log4jLevel
https://jira.talendforge.org/browse/TUP-17412
=> TUP-17412 Remote Runs from Studio Display Project Setting Log4jLevel

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
=> fix(TUP-17534):Different sybase db version in dbconnection and in

main/plugins/org.talend.libraries.persist.lookup/META-INF/MANIFEST.MF
=> TDQ-13464: fix running the match analysis with "Store on disk" option

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/INexusService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/EParameterFieldType.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListCellEditor.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListDialog.java
=> TESB-17306:Connect Talend (ESB) Studio to Nexus

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListDialog.java
=> TUP-17550:Can not import in external jar when create a general jdbc connection.

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/utils/MetadataConnectionUtils.java
=> fix(TUP-17524):Some decimal-type columns of hive table lose precision

main/plugins/org.talend.core.runtime/mappings/mapping_AS400.xml
https://jira.talendforge.org/browse/TDI-38627
=> TDI-38627:NUMERIC format problem on tAS400Output

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/utils/ProjectRepositoryNodeCache.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/utils/RepositoryNodeCache.java, main/plugins/org.talend.repository.view/src/org/talend/repository/viewer/content/listener/ResourceCollectorVisitor.java, test/plugins/org.talend.core.repository.test/src/org/talend/core/repository/ui/utils/RepositoryNodeCacheTest.java
fix(TUP-17290): retrieve SAP Table and BW metadata can't show up properly until click refresh repository https://jira.talendforge.org/browse/TUP-17290
=> fix(TUP-17290): retrieve SAP Table and BW metadata can't show up properly until click refresh repository	

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ITDQPatternService.java
=> TDQ-13507 "Cancel" button which on "Pattern Selector" dialog will dirty

main/plugins/org.talend.libraries.persist.lookup/META-INF/MANIFEST.MF, main/plugins/org.talend.libraries.persist.lookup/pom.xml
option get NoClassDefFoundError
=> fix(TDQ-13464): fix running the match analysis with "Store on disk"

main/plugins/org.talend.librariesmanager/resources/java/routines/StringHandling.java, main/plugins/org.talend.librariesmanager/resources/java/routines/TalendDate.java
https://jira.talendforge.org/browse/TDI-38412
=> TDI-38412:add the to_char method and fix some bug.

main/plugins/org.talend.librariesmanager/resources/java/routines/system/TalendDataSource.java
Merged from master:
https://github.com/Talend/tcommon-studio-se/commit/4da3e6ea822b8fe8c854f1c6ac51467b16a41aa7
https://github.com/Talend/tcommon-studio-se/commit/7997edd95e66517056d616786b5f496586bf9c3d
=> TESB-18908: Memory-Leak in TalendDataSource implementation

main/plugins/org.talend.libraries.mdm/META-INF/MANIFEST.MF
=> TMDM-10190: Allows fragment bundles to add additional API to the host(during building).

main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/linksbar/LinksToolbarItem.java
fix(TUP-17427): update url in TOS
https://jira.talendforge.org/browse/TUP-17427
=> fix(TUP-17427): update url in TOS

.gitignore, main/plugins/org.talend.core.runtime/mappings/mapping_MSSQL.xml
Summary of changes:
* Added mapping of 'CHAR' to 'id_String'
Additional information:
* JIRA issue: https://jira.talendforge.org/browse/TDI-38624
=> fix(TDI-38624): Allow mapping of MSSQL CHAR to 'String'

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
fix(TUP-17065): fix new framework propagation (fix a compile error)
https://jira.talendforge.org/browse/TUP-17065
=> fix(TUP-17065): fix new framework propagation (fix a compile error)

main/plugins/org.talend.librariesmanager/resources/java/routines/StringHandling.java
https://jira.talendforge.org/browse/TDI-38707
=> TDI-38707:Some conversion functions need optimize

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/XsdMetadataUtils.java, test/plugins/org.talend.metadata.managment.ui.test/resources/RFC_READ_TABLE_Input.xsd, test/plugins/org.talend.metadata.managment.ui.test/src/main/test/org/talend/metadata/managment/ui/utils/XsdMetadataUtilsTest.java
=> TUP-17611:Talend and SAP Bapi connectivity : incorrect data type for

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/builder/ConvertionHelper.java
=> fix(TUP-17599):Renaming Schema causes "Access to data failure{0}"

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/conf/EHadoopProperties.java
https://jira.talendforge.org/browse/TUP-17592
=> bugfix(TUP-17592)No default value for HDInsight hadoop wizard

main/plugins/org.talend.utils/src/main/java/org/talend/utils/sql/ResultSetUtils.java
Add support read ability for type of blob column
=> patch complete TPS-1928[6.3.1] Unable to profile SQL Server NVARCHAR(MAX) (TDQ-13488)

main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
fix(TUP-16646):Error_when_logging_into_Project_that_has_a_reference_project_in_Dev_Studio
https://jira.talendforge.org/browse/TUP-16646
=> fix(TUP-16646):Error_when_logging_into_Project_that_has_a_reference

main/plugins/org.talend.librariesmanager/resources/java/routines/StringHandling.java
https://jira.talendforge.org/browse/TDI-38707
=> TDI-38707:add the missing static.

main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/ui/UpdateWizardModel.java
=> fix(TUP-17551):There is npe when try to install tdm/esb in "Install

main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/VersionUtils.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/builder/ConvertionHelper.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/repository/ERepositoryObjectTypeTest.java, test/plugins/org.talend.metadata.managment.test/src/org/talend/core/model/metadata/builder/ConvertionHelperTest.java, test/plugins/org.talend.migrationTool.test/src/org/talend/migrationtool/MigrationToolServiceTest.java, test/plugins/org.talend.updates.runtime.test/src/org/talend/updates/runtime/engine/component/RemoteComponentsTransportTest.java
* check junits when no access website
* don't use PowerMock for junit
* enhance the generic type
* fix the failed junits without PowerMock
=> test(TUP-17687): enhance junits

test/plugins/org.talend.metadata.managment.test/src/org/talend/core/model/metadata/builder/database/manager/dbs/AbstractTest4ExtractManager.java, test/plugins/org.talend.updates.runtime.test/src/org/talend/updates/runtime/engine/component/RemoteComponentsTransportTest.java, test/plugins/org.talend.utils.test/src/org/talend/utils/network/ServerSocketFreePortOpenerTest.java
* test(TUP-17687): fix the problem for accessing web junit
* test(TUP-17687): fix one error log for NPE DB
* test(TUP-17687): disable the debug flag for port test
=> test(TUP-17687): fix some junit issues

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/conf/EHadoopProperties.java
*forgot to push this branch
https://jira.talendforge.org/browse/TUP-17771
=> fix(TUP-17771):Should not remove "Job result folder" from HDI wizard

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
fix(TUP-17221): git performance slow with distant git repository
https://jira.talendforge.org/browse/TUP-17221
=> fix(TUP-17221): git performance slow with distant git repository

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DuplicateAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/RestoreAction.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/ICoreUIService.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/CoreUIService.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/services/IDesignerCoreUIService.java
Streaming job which are both converted from Spark job for the first time
=> fix(TUP-17591)：Cannot drag the Spark Streaming joblet to the Spark

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/AbstractNamedWizardPage.java
https://jira.talendforge.org/browse/TUP-17829
=> fix(TUP-17829):incorrect characters can be saved when edit property

main/plugins/org.talend.librariesmanager/resources/java/routines/StringHandling.java
https://jira.talendforge.org/browse/TDI-38803
=> TDI-38803:StringHandling.LPAD(first_string, length) return wrong value

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
*Disable kerberos for EMR's Hbase
https://jira.talendforge.org/browse/TUP-17659
=> fix(TUP-17659)EMR 55 hbase should not enable kerberos authentication

main/plugins/org.talend.core.runtime/mappings/mapping_AS400.xml
*now can automatically recognize Float, Integer, Long and Double from
NUMERIC DB type.
https://jira.talendforge.org/browse/TUP-14124
=> fix(TUP-14124):Retrieve schema

main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ApplicationWorkbenchAdvisor.java
fix(TUP-17867): can't logon git mdm project
https://jira.talendforge.org/browse/TUP-17867
=> fix(TUP-17867): can't logon git mdm project

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ITDQPatternService.java
=> TDQ-13685 -tMultiPatternCheck: fix one bug about refresh deleted

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ILibraryManagerService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ILibrariesService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/INexusService.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListCellEditor.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListDialog.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/actions/ImportExternalJarAction.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialog.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ArtifactsDeployer.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/AbstractLibrariesService.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LibrariesService.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
=> TESB-19643:RouteBuilder - cConfig Install button active and creation of 6.0.0-SNAPSHOT Versions

main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/core/IDesignerCoreService.java
=> fix(TUP-17890):tRunJob takes 1 minute to display the component tab

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/document/IGenerateAllDocumentation.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/RepositoryNodeManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/RepositoryManagerHelper.java, main/plugins/org.talend.core/src/main/java/org/talend/core/model/repository/documentation/DocumentationHelper.java, main/plugins/org.talend.core/src/main/java/org/talend/core/model/repository/documentation/generation/IDocumentationGenerator.java, main/plugins/org.talend.core/src/main/java/org/talend/core/model/repository/documentation/generation/JobHTMLScriptsManager.java
=> fix(TUP-17900):"Export all projects documentation" does not create the

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListDialog.java
=> TESB-19732:Cannot select module for driver jar

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/AbstractLibrariesService.java
*now can use "+" in file path
https://jira.talendforge.org/browse/TUP-17723
=> fix(TUP-17723)No message to notice customer why cannot upload jar

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponentsFactory.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/repository/RepositoryComponentManager.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/component/settings/ComponentsSettingsHelper.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/images/CoreImageProvider.java, main/plugins/org.talend.helpers/src/main/java/org/talend/helpers/ui/actions/LogLoadedComponentsAction.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java, main/plugins/org.talend.repository.view.example/src/org/talend/repository/example/viewer/handler/demo/ExampleDemoDragAndDropHandler.java
fix(TUP-17983): random issue when logon remote project error pop up
https://jira.talendforge.org/browse/TUP-17983
=> fix(TUP-17983): random issue when logon remote project error pop up

main/plugins/org.talend.core/src/main/java/org/talend/core/services/ICommandlineClientService.java
fix(TUP-17412)Remote_Runs_from_Studio_Display_Project_Setting_Log4jLevel(Fix
command line problem)
https://jira.talendforge.org/browse/TUP-17412
=> fix(TUP-17412)Remote_Runs_from_Studio_Display_Project_Setting_Log4jLevel(Fix command line problem)

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/XmlFileStep1Form.java
fix(TUP-18012): wizard ui problem for xml metedata
https://jira.talendforge.org/browse/TUP-18012
=> fix(TUP-18012): wizard ui problem for xml metedata

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/version/custom/HadoopVersionDialog.java
wizard
https://jira.talendforge.org/browse/TUP-17988
=> fix(TUP-17988)Hide Cloudera altus from distributions available on the

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/AbstractLibrariesService.java
=> TUP-17977:Meet StackOverFlowError when import in demos.

main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/model/P2ExtraFeature.java
=> fix(TUP-17968):Additional Packages - Not taken from local folder (local

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbstractNode.java
fix(TUP-5461):AmazonAurora components can't select existing connection from joblet
https://jira.talendforge.org/browse/TUP-5461
=> fix(TUP-5461):AmazonAurora components can't select existing connection

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IODataComponent.java
TUP-17701 Can't setup / reopen tMap if component is not existing (D&D tmap from palette to Job)
https://jira.talendforge.org/browse/TUP-17701
=> TUP-17701 Can't setup / reopen tMap if component is not existing (D&Dtmap from palette to Job)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/IGenericElementParameter.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/manager/ChangeIdManager.java
fix(TUP-16516): after change context group under repository re-import the whole project again will get error
https://jira.talendforge.org/browse/TUP-16516
=> fix(TUP-16516): after change context group under repository re-import the whole project again will get error

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
=> TESB-19787:Import a route with routelet, the relationship of the routelet will be missed

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IScdComponentService.java
=> fix(TUP-17950):Failed to generate code after making minor valid changes

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/document/IDocumentationService.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
=> fix(TUP-18014):Rename folder has "ResourceNotFoundException" in error

main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/NetworkUtil.java, main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/gmf/util/DisplayUtils.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
fix(TUP-18137)Need to remove http calls to use https only
https://jira.talendforge.org/browse/TUP-18137
=> fix(TUP-18137)Need to remove http calls to use https only

main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java, test/plugins/org.talend.core.test/src/org/talend/core/model/utils/TalendTextUtilsTest.java
*Remove the method to make line break. 
*add a junit.
https://jira.talendforge.org/browse/TUP-18089
=> fix(TUP-18089)SQLBuilder insert /n in value but changing their meaning

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/prefs/ITalendCorePrefConstants.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/core/IDesignerCoreService.java
=> TUP-18046:Cannot Retrieve Columns from Metadata MapRDB Database

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/advanced/dataeditor/AbstractDataTableEditorView.java
=> fix(TUP-17873):tRowGenerator : wizard display : auto-expand, but dont

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/extension/AbstractRepositoryNodeUpdateManagerProvider.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/extension/AbstractRepositoryUpdateManagerProvider.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/extension/IRepositoryUpdateManagerProvider.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/extension/UpdateManagerProviderDetector.java
fix(TUP-17800):detect dependencies trigger a dialogue box of change propagation
https://jira.talendforge.org/browse/TUP-17800
=> fix(TUP-17800):detect dependencies trigger a dialogue box of change propagation

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java
https://jira.talendforge.org/browse/TUP-18002
=> fix(TUP-18002)can't see context after first added when drop to editor

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/SwitchContextGroupNameImpl.java
connection to context with more than one group and do dataviewer with
wrong group setting.
=> fix(TUP-18107):JDBC URL change to jdbc:xxx://<xxx>:<xxx> if export the

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/SelectRepositoryContextDialog.java
https://jira.talendforge.org/browse/TUP-18078
=> fix(TUP-18078)Selected context Could not be deselect

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ILibrariesService.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/AbstractLibrariesService.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LibrariesService.java
fix(TUP-17904):Export Context with multiple groups is slow
https://jira.talendforge.org/browse/TUP-17904
=> fix(TUP-17904):Export Context with multiple groups is slow

main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonNavigator.java
fix(TUP-16691): uncommitted items not show if click Apply then Ok on Project settings->custom components
https://jira.talendforge.org/browse/TUP-16691
=> fix(TUP-16691): uncommitted items not show if click Apply then Ok on Project settings->custom components

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/prefs/ITalendCorePrefConstants.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/core/IDesignerCoreService.java
fix(TUP-18152): when the first time create tag,always met the issue "connect server timeout"
https://jira.talendforge.org/browse/TUP-18152
=> fix(TUP-18152): when the first time create tag,always met the issue "connect server timeout"

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
fix(TUP-17689): Meet NPE error log when log on 632 build
https://jira.talendforge.org/browse/TUP-17689
=> TUP-17689 Meet NPE error log when log on 632 build

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ILibraryManagerService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/TalendLibsServerManager.java, main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
=> fix(TUP-18208):Studio sending multiple "getLibLocation" metaservlet

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
fix(TUP-18204): NullPointerException when opening code routines from Reference project after switch branch
https://jira.talendforge.org/browse/TUP-18204
=> fix(TUP-18204): NullPointerException when opening code routines from Reference project after switch branch

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/ui/actions/metadata/AbstractCreateTableAction.java
fix(TUP-6786): repository refresh problem for schema when click cancel
https://jira.talendforge.org/browse/TUP-6786
=> fix(TUP-6786): repository refresh problem for schema when click cancel

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
=> fix(TUP-18252):Hbase of Mapr:open existing hbase connection,some default

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/ITestContainerProviderService.java
=> fix(TUP-17992):RefProject:Run Test Case: nothing feedback after run

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/SelectorTableForm.java
fix(TUP-18049)Unable to Retrieve Schema if clicking multiple times
https://jira.talendforge.org/browse/TUP-18049
=> fix(TUP-18049)Unable to Retrieve Schema if clicking multiple times

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/template/MavenTemplateManager.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomIdsHelper.java, test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/utils/PomIdsHelperTest.java
kjwang/fix(TUP-18276):PATCH broke Build Job with sub-jobs from Reference project
https://jira.talendforge.org/browse/TUP-18276
=> kjwang/fix(TUP-18276):PATCH broke Build Job with sub-jobs from Reference

test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/utils/PomIdsHelperTest.java
kjwang/fix(TUP-18276):PATCH broke Build Job with sub-jobs from Reference project(junit)
https://jira.talendforge.org/browse/TUP-18276
=> Kjwang/fix(tup 18276)patch broke build job with subjobs from reference project junit

main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/action/RetrieveMDMSchemaAction.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/ui/actions/metadata/AbstractCreateTableAction.java
fix(TUP-6786): schema name refresh problem
https://jira.talendforge.org/browse/TUP-6786
=> fix(TUP-6786): schema name refresh problem

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/IRepositoryTypeProcessor.java
https://jira.talendforge.org/browse/TUP-17378
=> fix(TUP-17378)Should not show CDH 5.8 Spark 2 distribution in MR job

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/IRepositoryTypeProcessor.java
Reverts Talend/tcommon-studio-se#1166
=> Revert "fix(TUP-17378)Should not show CDH 5.8 Spark 2 distribution in MR job"

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java
Related to https://jira.talendforge.org/browse/TCOMP-291
and is required for https://github.com/Talend/tdi-studio-se/pull/1366
TO BE MERGED AFTER 6.4.1 RELEASE
=> fix(TCOMP-291):add method to find dynamic property

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java, test/plugins/org.talend.repository.items.importexport.test/src/org/talend/repository/items/importexport/handlers/ImportExportHandlersManagerTest.java
=> fix(TUP-18001):InvocationTargetException show when import the attached

main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-16794
=> TUP-16794 : Improve the save logic in LocalRepositoryFactory

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/advanced/dataeditor/AbstractDataTableEditorView.java
https://jira.talendforge.org/browse/TUP-18325
=> fix(TUP-18325)Interface of Row line component display deformation

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java, test/plugins/org.talend.metadata.managment.ui.test/src/main/test/org/talend/metadata/managment/ui/utils/ConnectionContextHelperTest.java
tsalesforceinput when select a repository salesforce which convert to
context will show pop up error.
=> fix(TUP-5432):Component Framework :Salesforce: For component

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/extension/UpdateManagerProviderDetector.java
fix(TUP-18349): "Detect Dependencies" doesn't work
https://jira.talendforge.org/browse/TUP-18349
=> fix(TUP-18349): "Detect Dependencies" doesn't work

.gitignore, main/plugins/org.talend.core.runtime/mappings/mapping_MSSQL.xml
Back-port TDI-38624 to 6.2.x
https://jira.talendforge.org/browse/TDI-39222
https://jira.talendforge.org/browse/TDI-38624
=> fix(TDI-39222): Back-port TDI-38624 to 6.2.x

.gitignore, main/plugins/org.talend.core.runtime/mappings/mapping_MSSQL.xml
Back-port TDI-38624 to 6.3.x
https://jira.talendforge.org/browse/TDI-39222
https://jira.talendforge.org/browse/TDI-38624
=> fix(TDI-39222): Back-port TDI-38624 to 6.3.x

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/linking/TableToTreeLinker.java
*add colors for table since mac does not support row separater line
*adjust "y" coordinate of end point of line on mac
https://jira.talendforge.org/browse/TUP-18404
=> fix(TUP-18404)Link Target Issue

main/plugins/org.talend.core.runtime/mappings/mapping_Snowflake.xml
For https://jira.talendforge.org/browse/TDI-39289
- add mapping for snowflake
=> fix(TDI-39289) : support tSnowflakeConnection in ELTJDBC

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolHelper.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableForm.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/MetadataToolHelperTest.java
https://jira.talendforge.org/browse/TUP-18465
=> fix(TUP-18465)column names that contain Japanese get some underscores

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponent.java
Fix the problem of reference display and limit the number of refresh
done.
=> fix(TUP-18434) fix problem of refresh

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/database/conn/DatabaseConnStrUtilTest.java
=> fix(TUP-18517):Adding additional JDBC parameters to metadata connection

main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
https://jira.talendforge.org/browse/TDI-38416
=> chore(TDI-38416): split Marketo modules

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/actions/ImportExternalJarAction.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ArtifactsDeployer.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
=> fix(TUP-18489):tLibraryLoad doesn't display the jars available in local

main/plugins/org.talend.datatools.xml/src/main/java/org/talend/datatools/xml/utils/XSDPopulationUtil2.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/metadata/xml/utils/TreeUtil.java, test/plugins/org.talend.metadata.managment.ui.test/src/main/test/org/talend/metadata/managment/ui/wizard/metadata/xml/utils/TreeUtilTest.java
Fix as well import of XSD to avoid to lose information on similar nodes
=> fix(TUP-18452) fix wrong generation of schema from WSDL

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DBTypeForm.java
=> fix(TUP-18607):[BUG] Hive/Hbase wizard cann't click Finish button under

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/TrackerUtil.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/utils/TrackerUtilTest.java
feat(TUP-18035)Tracking influence unification
https://jira.talendforge.org/browse/TUP-18035
=> feat(TUP-18035)Tracking influence unification

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
=> TESB-20417:Issues with Hyphen in ServiceName

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
fix: can not download/browse jars
=> fix: can not download/browse jars

main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
'ProcessorUtilities'.copy drools files when run or build job.
=> TDQ-14308 move th code of copy drools file from 'BuildJobHandler' to

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IESBMicroService.java
=> TESB-20466:Data Services (REST) as Microservice - Part II

main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/codegen/IMicroserviceCodeGeneratorService.java
Hi, I've add a new interface for microservice code generator.
Yi
=> TESB-20466: Add microservice code generator service interface

main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/core/IDesignerCoreService.java
https://jira.talendforge.org/browse/TUP-18261
=> fix(TUP-18261): there is an error when Studio tries to make a query to secured tmc service

main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
https://jira.talendforge.org/browse/TDI-38416
=> feat(TDI-38416): Marketo backport to 651

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
fix(TUP-18804): connection to SQL Server not retrieving Schemas
https://jira.talendforge.org/browse/TUP-18804
=> fix(TUP-18804): connection to SQL Server not retrieving Schemas

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
This reverts commit c8a10b68bc68ec02e6c10b165422d876218ac655.
=> Revert "TESB-20417:Issues with Hyphen in ServiceName (#1242)"

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
This reverts commit d8fbf443099832075e430061e35122187285792d.
=>  Revert "TESB-20417:Issues with Hyphen in ServiceName (#1243)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
This reverts commit d8fbf443099832075e430061e35122187285792d.
=> Revert "TESB-20417:Issues with Hyphen in ServiceName (#1243)"

main/plugins/org.talend.libraries.apache.cassandra/plugin.xml
Add nexus description for spark-cassandra-connector-assembly-2.0.5-patched-20171023.jar
=> fix(TBD-5985): add nexus desc for spark-cassandra-assembly

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataUtils.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseWizard.java
TUP-18753 Update driver of vertica
https://jira.talendforge.org/browse/TUP-18753
=> Kjwang/feat(tup 18753)update driver of vertica

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/ContextParameterUtilsTest.java
=> fix(TUP-18772):buildjob override parameter add unecessary backslash

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/download/DownloadHelper.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/nexus/NexusDownloader.java
=> fix(TUP-14602):Exchange view: Download monitor dialog slows down the

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponent.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponentFileNaming.java
* Add methods to IComponent for templateURI unification
* Add method to IComponentFileNaming to calculate path from String prefix
Should be merged together with PRs https://github.com/Talend/tdi-studio-se/pull/1737 and https://github.com/Talend/tdi-studio-ee/pull/572
=> feat(TCOMP-683): tacokit integration

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/ITargetExecutionConfig.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
TUP-18626 Handle Jobserver authentification
https://jira.talendforge.org/browse/TUP-18626
=> Kjwang/feat(tup 18626)handle jobserver authentification(6.5)

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/gmf/util/DisplayUtils.java, main/plugins/org.talend.core.repository/schema/repository_provider.exsd, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/DynamicFieldBean.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/RepositoryFactoryProvider.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/IRepositoryService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
https://jira.talendforge.org/browse/TUP-18724
=> feat(TUP-18724): manage connections: improvements

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
TUP-19042 Project reference from a project branch to another branch
https://jira.talendforge.org/browse/TUP-19042
=> Fix(tup 19042)project reference from a project branch to another branch

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java, main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java, main/plugins/org.talend.repository.view/src/org/talend/repository/viewer/content/FolderListenerSingleTopContentProvider.java
https://jira.talendforge.org/browse/TCOMP-691
=> task(TCOMP-691): create context menu for Tacokit node in repository panel

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
TUP-19013 Studio hangs/freezes after clicking cancel while job is being built
https://jira.talendforge.org/browse/TUP-19013
=> TUP-19013 Studio hangs/freezes after clicking cancel while job is being

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java, main/plugins/org.talend.librariesmanager/resources/java/routines/system/GetJarsToRegister.java
Space in classpath are not supported
Addition in the API to provide the ability to encode spaces and support them in classpaths
=> fix(TBD-5136): support space encoding in classpath

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/SelectRepositoryContextDialog.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/cmd/AddRepositoryContextGroupCommand.java
=> fix(TUP-19089):Unable to select or deselect used variables in select

main/features/org.talend.fragment.jars.feature/feature.xml
Remove HL7 components, and repository metadata
=> feat(TUP-19077) Remove HL7

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/EParameterFieldType.java
https://jira.talendforge.org/browse/TCOMP-691
=> task(TCOMP-691): create context menu for Tacokit node in repository

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
https://jira.talendforge.org/browse/TUP-19123
=> feat(TUP-19123): Manage connections: improvements (2)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/Project.java
fix(TUP-19147)Commandline: listProject command throw errors after initRemote a migration tac
https://jira.talendforge.org/browse/TUP-19147
=> fix(TUP-19147)Commandline: listProject command throw errors after

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/RouteUtil.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
=> TESB-20515:Routelet can not be executed in Microservice

main/plugins/org.talend.core/src/main/java/org/talend/core/model/components/AbstractComponentsProvider.java
* Add methods required for guess schema feature
=> feat(TCOMP-683): Guess schema

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/connection/manager/ImpalaConnectionManager.java
https://jira.talendforge.org/browse/TBD-6225
=> fix(TBD-6225): CDH 5.13 Kerberos impala cannot check successfully

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/RouteUtil.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
=> TESB-20515:Routelet can not be executed in Microservice (#1370)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/temp/ECodePart.java
https://jira.talendforge.org/browse/TDI-39741
Related PR :
* tdi-studio-se: https://github.com/Talend/tdi-studio-se/pull/1862
* components:   https://github.com/Talend/components/pull/1107
=> feat(TDI-39741): add data process parts to ECodePart

main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
https://jira.talendforge.org/browse/TDI-39298
=> feat(TDI-39298): tGoogleDrive Integration

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ReferenceProjectProblemManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/RepositoryWorkUnit.java
fix(TUP-19085)Migration of reference project (handle tags)
https://jira.talendforge.org/browse/TUP-19085
=> fix(TUP-19085)Migration of reference project (handle tags)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/ComponentUtilities.java
* Add getAllInputConnections method
* Refactor getAllOutputConnections
Should be merged simultaneously with all another PRs in this jira
https://jira.talendforge.org/browse/TDI-39312
=> feat(TDI-39469): Extends ComponentUtilities class

main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
Ensure the local repo has slf4j-simple for TOS support
=> adding slf4j-simple in tcomp temp repo

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ArtifactRepositoryBean.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/IRepositoryArtifactHandler.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/NexusServerBean.java, main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/RepositorySystemFactory.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus2RepositoryHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
Hi, please check my PR for TESB-20440: Support Nexus 3 in ESB use cases.
Thanks,
Yi
=> TESB-20440: Support Nexus 3 in ESB use cases

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/DatabaseConnStrUtil.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java
=> TDQ-14702 old General jdbc only for TOP;Get correct url for TCOMP JDBC

test/plugins/org.talend.core.repository.test/src/org/talend/core/repository/model/ArtifactRepositoryBeanTest.java
TESB-20440: Fixed test case for nexus type changing
=> TESB-20440: Fixed test case for nexus type changing

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/InstallModuleDialog.java
custom mvn uri
https://jira.talendforge.org/browse/TUP-19008
=> fix(TUP-19008)unexpected character display when click detect button for

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
https://jira.talendforge.org/browse/TDI-39968
=> fix(TDI-39968):Split SQL to avoid exceed 64k limitation.

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
https://jira.talendforge.org/browse/TUP-19355
=> fix(TUP-19355): Spark job cannot build successfully in CDH 513 Kerberos

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryNodeUtilities.java, main/plugins/org.talend.repository.view/src/org/talend/repository/viewer/filter/RecycleBinViewerFilter.java
=> fix(TUP-19368):JDBC: jdbc connection isn't in folder after deleting it's

main/plugins/org.talend.libraries.mdm/plugin.xml
The jars are all in Nexus now. 
https://talend-update.talend.com/nexus/#nexus-search;quick~neethi
https://talend-update.talend.com/nexus/#nexus-search;quick~jaxb-impl
https://talend-update.talend.com/nexus/#nexus-search;quick~jaxb-core
=> TMDM-11699 Can't download jar automatically while creating mdm connection

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/EParameterFieldType.java
add TACOKIT_BUTTON field type required for Tacokit integration
=> feat(TCOMP-681): add TACOKIT_BUTTON field type

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
https://jira.talendforge.org/browse/TDI-39968
=> fix(TDI-39968):Compile error of constant string too long.

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/StandaloneConnectionContextUtils.java
=> fix(TDQ-14726): fix TdqReportRun can not run with HiveContextKerberos

main/plugins/org.talend.presentation.onboarding/src/org/talend/presentation/onboarding/handlers/OnBoardingHandler.java, main/plugins/org.talend.presentation.onboarding/src/org/talend/presentation/onboarding/handlers/OnBoardingStartup.java
https://jira.talendforge.org/browse/TUP-19456
=> fix(TUP-19456): Studio Crashes On load of and empty GitHub project

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenStandardJobOSGiPom.java
Hi, please review my fix for OSGi bundle issue
Thanks,
Yi
=> TESB-20833: Fixed avoid to overwrite OSGi bundle pom file

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
Hi, please review my fix by adding microservice type.
Yi
=> TESB-20834: fixed NPE for microservice type missing

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListCellEditor.java
=> fix(TUP-19516):now the driver select table can't be used for jdbc

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
Parent PR for https://github.com/Talend/tdi-studio-se/pull/1960/
=> fix(TDI-40000): Fix property name

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DBTypeForm.java
=> fix(TUP-19354):JDBC: Cannot open jdbc medadata after changing mysql

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/utils/MetadataConnectionUtils.java
=> fix(TUP-19515):JDBC DB Metadata Connection Retrieve Schema Fails to

main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
At this moment we have ClassNotFoundEception during execution of Routes with Routelets in Studio because if Routes project has no Routelet project in depdendency. Current fix resolves this issue.
=> TESB-21230 Routelet is added to Route dependency

main/plugins/org.talend.utils/src/main/java/org/talend/utils/files/AbstractDataCleaner.java
fix for https://jira.talendforge.org/browse/TPSVC-3770
=> fix https://jira.talendforge.org/browse/TPSVC-3770

main/plugins/org.talend.utils/src/main/java/org/talend/utils/files/AbstractDataCleaner.java
fix for https://jira.talendforge.org/browse/TPSVC-3770
=> fix for https://jira.talendforge.org/browse/TPSVC-3770

main/plugins/org.talend.core.runtime/mappings/mapping_Oracle.xml
https://jira.talendforge.org/browse/TDI-35418
=> fix(TDI-35418): Change mapping for REAL numbers

main/plugins/org.talend.designer.maven/META-INF/MANIFEST.MF, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/ProcessorDependenciesManager.java
https://jira.talendforge.org/browse/TUP-19530
=> fix(TUP-19530)There is an error when importing old job with test cases

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
https://jira.talendforge.org/browse/TDI-39968
=> fix(TDI-39968):Split SQL to avoid exceed 64k limitation. (#1399)

main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
=> fix(TUP-19526):Dynamic schema with generic JDBCconnection fails when job

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/actions/DownloadExternalJarAction.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/views/ModulesView.java
=> fix(TUP-19493):Module View: not possible to download anymore the single

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/IRepositoryNode.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryNode.java
https://jira.talendforge.org/browse/TUP-19640
=> task(TUP-19640): Deleted tacokit nodes can't be shown in recyclebin node

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenStandardJobOSGiPom.java
Please check my PR for TESB-21414.
=> TESB-21414: Fixed unable to install Kar feature in runtime

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/PropertiesWizard.java
dependencies
https://jira.talendforge.org/browse/TUP-18925
=> fix(TUP-18925)ChangeVersion command doesn't upgrade the version of

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
main class commonpro.tjava_0_1.tjava
https://jira.talendforge.org/browse/TUP-19695
=> fix(TUP-19695)run task failed with error :Error: Could not find or load

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
=> fix(TUP-19692):Bad performance when do updating stats&logs setting to

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
https://jira.talendforge.org/browse/TUP-19408
=> fix(TUP-19408): Pom file is deteled in server incorrectly.

main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
add slf4j-standard logger dependency
=> add slf4j standard dependency

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/ITaCoKitService.java
https://jira.talendforge.org/browse/TUP-19738
=> item(TUP-19738): Tacokit migration API not wired into the studio

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
TUP-19803 Fix the the junits on master
https://jira.talendforge.org/browse/TUP-19803
=> TUP-19803 Fix the the junits on master

main/plugins/org.talend.libraries.jdbc.access/pom.xml, main/plugins/org.talend.libraries.jdbc.exasol/pom.xml
https://jira.talendforge.org/browse/TUP-19810 : fix tycho warning
=> TUP-19810 : fix for Tycho build

main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/exception/MessageBoxExceptionHandler.java
tests"
https://jira.talendforge.org/browse/TUP-19726
=> fix(TUP-19726)publish job with testcase failed if check on "execute

main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
fix(TUP-19801)NPEs executing importItems with CommandLine
https://jira.talendforge.org/browse/TUP-19801
=> fix(TUP-19801)NPEs executing importItems with CommandLine

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/context/RepositoryContext.java
=> fix(TUP-18674):Studio connection does not show other git branches with

main/plugins/org.talend.model/plugin.xml
https://jira.talendforge.org/browse/TUP-19630 : remove extra emf registration package
=> fix TUP-19630 : remove extra emf registration package

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/ContextParameterUtilsTest.java
I've decided to move isDynamic() method from javajet to this class.
See https://github.com/Talend/tdi-studio-se/pull/2114/files
=> feat(TCOMP-734): add ContextParameterUtils.isDynamic() method

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ILibraryManagerService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ISVNProviderServiceInCoreRuntime.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/routines/RoutineLibraryMananger.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ui/dialog/LibrariesListSelectionDialog.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/InitializeMissingJarHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/AbstractLibrariesService.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/NexusDownloader.java, test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/model/service/LocalLibraryManagerTest.java
fix(TUP-19748) when logon project pop up error after migration
https://jira.talendforge.org/browse/TUP-19748
=> fix(TUP-19748) when logon project pop up error after migration

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/repository/build/RepositoryObjectTypeBuildProvider.java
to fix TESB-21507: SOAP Data Service should not be packaged as "job design"
Yi
=> TESB-21507: Add realtion for service

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
Each time we try to build a job, it will try to get the dependencies of the system routines.
Since the system routines are considered as "fixed", we cache the list of jars needed for routines, and reload only if we reset the cache.
=> fix(TUP-19848) improve build performances

test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelperTest.java
=> feat(TUP-19782)Add filter on the pom synchronization

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenBeanPom.java
Install default modules for beans
=> TESB-21419: Install default modules for beans

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/PropertiesWizard.java
=> fix(TUP-18925):ChangeVersion command doesn't upgrade the version of

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
=> fix(TUP-19852):Installer: when start studio, error "Share libraries

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/INode.java
=> fix(TUP-19802):For DB Unified, Fixed schema for database error is added

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
kjwang/fix can't run job on job server problem
=> kjwang/fix can't run job on job server problem

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ModuleNeeded.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ModuleStatusProvider.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
when launch studio for the first time
=> fix(TUP-19881):External jar need to be installed in the route component

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/ProcessorDependenciesManager.java
version to another one, but pom dependency still need previous spark
version jar
=> fix(TUP-19636):import previous spark with test case job, set spark

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/utils/MetadataConnectionUtils.java
a driver which not match the DB version
=> fix(TUP-19828):Connect oracle DB with JDBC type failed randomly when set

main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/TalendProxySelector.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/HttpClientTransport.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/NexusServerUtils.java, main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
https://jira.talendforge.org/browse/TUP-19667
=> fix(TUP-19667): use HTTP proxy instead of SOCKS

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IFilterService.java, main/plugins/org.talend.designer.maven.ui/src/main/java/messages.properties, main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/setting/project/page/MavenProjectSettingPage.java
settings->Build->Maven,error will show in error log.
=> fix(TUP-19880):[bug] when input wrong filter in Project

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
avoid tests for the aggregator pom
=> fix(TUP-19937) fix build from parent with test case

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
Routines "myroutine" has compile errors.
=> fix(TUP-19945):first generate failed with error:ProcessorException:

main/plugins/org.talend.designer.maven.ui/src/main/java/messages.properties, main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/setting/project/page/MavenProjectSettingPage.java
missing documentation for user
=> workitem(TUP-19959):Wrong content for CI project settings on TOS and

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
Execution / routines.jar missing in ZIP file
=> fix(TUP-19806):Error: Could not find or load main class / Remote

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java
https://jira.talendforge.org/browse/TUP-19915
=> fix(TUP-19915): Context parameter changes are not getting reflected under Hive connection

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
=> fix(TUP-19965):fix the download button show as manual after upload a jar

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
=> TESB-21810:Module tab shows the incorrect list of installed jar files

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/HandlerUtil.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
https://jira.talendforge.org/browse/TUP-19934
=> fix(TUP-19934)Items are duplicated in Import Dialog

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/ProcessUtils.java
Fixed routes cannot use bean from reference project
=> TESB-21799: Fixed routes cannot use bean from reference project

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
=> fix(TUP-19808):Studio doesn't display Reference project trunk or branch

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/AbstractDragAndDropServiceHandler.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/IDragAndDropServiceHandler.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java, main/plugins/org.talend.repository.view.example/src/org/talend/repository/example/viewer/handler/demo/ExampleDemoDragAndDropHandler.java
https://jira.talendforge.org/browse/TUP-19974
=> fix(TUP-19974)Opening a job takes more than half an hour in studio

main/plugins/org.talend.libraries.apache.cassandra/plugin.xml
https://jira.talendforge.org/browse/TBD-6803
=> fix(TBD-6803): add spark-cassandra-connector jar definition

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/maven/MavenArtifact.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
=> TESB-21888:When using cConfig component "Check" (Advance tab) button

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListDialog.java
SNAPSHOT version to cConfig creates the wrong default version for the
nexus upload
=> TESB-22023:Adding external jars with a XXX-8.0.0-20180412.070852-4.jar

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/DBConnectionContextUtils.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
https://jira.talendforge.org/browse/TUP-20149
=> fix(TUP-20149)Hive Metastore Port can't convert to context mode

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/AbstractRepositoryContentHandler.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/IRepositoryContentHandler.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/MetadataService.java, main/plugins/org.talend.repository.view.example/src/org/talend/repository/example/viewer/handler/demo/ExampleDemoRepositoryHandler.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/migration/ContextItem2JobDocExtContentHandler.java
https://jira.talendforge.org/browse/TUP-20124
=> fix(TUP-20124): NPE during changing TCOMP component repository value

main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/swt/tableviewer/TableViewerCreatorNotModifiable.java
https://jira.talendforge.org/browse/TUP-20156
=> fix(TUP-20156): Cannot open the tMap component, throwing 'An SWT error has occured'.

main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
* split logic of components on definition and runtime
=> feat(TDI-40477): Split Snowflake components

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ui/actions/AContextualAction.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/actions/ActionsHelper.java, main/plugins/org.talend.repository.view/src/org/talend/repository/viewer/action/RepoDoubleClickAction.java, main/plugins/org.talend.repository.view/src/org/talend/repository/viewer/action/RepoNodeActionProvider.java
https://jira.talendforge.org/browse/TUP-20166
=> fix(TUP-20166): Studio "Attempted to beginRule: F/.Java/src/main/java, does not match outer scope rule" Error

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ILibraryManagerService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponentsService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ModuleNeeded.java, main/plugins/org.talend.core/src/main/java/org/talend/core/model/components/AbstractComponentsProvider.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ConfigModuleDialog.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/general/ModuleNeededTest.java, test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/model/service/LocalLibraryManagerTest.java
module protobuf-java-2.6.1.jar
=> bugfix(TUP-20210):Strange behavior on component tNLPModel for required

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java, test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/model/service/LocalLibraryManagerTest.java
module protobuf-java-2.6.1.jar
=> fix(TUP-20210):Strange behavior on component tNLPModel for required

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
fix(TUP-20197) Connection Talend-SAS
https://jira.talendforge.org/browse/TUP-20197
=> fix(TUP-20197) Connection Talend-SAS

main/plugins/org.talend.core.runtime/mappings/mapping_Sybase.xml
https://jira.talendforge.org/browse/TDI-31645
=> fix(TDI-31645):Eliminate the invalid data type "DOUBLE PRECIS"

main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
=> bump Tacokit version to 1.0.1-SNAPSHOT

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java, main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/RetrieveItemsUtil.java
tRunJob component
https://jira.talendforge.org/browse/TUP-20248
=> fix(TUP-20248)Impact analysis doesn't work correctly against job in

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
=> fix(TUP-20276):there is NPE error for CommonExceptionHandler show in

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/IJobletProviderService.java
name in JobletView
https://jira.talendforge.org/browse/TUP-20231
=> fix(TUP-20231)Update Detection won't popup after updating it's joblet

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ConvertJobsUtil.java
Reverts Talend/tcommon-studio-se#1742
=> Revert "feat(TUP-20277):Deprecated items on 7.1"

main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MDMOutputSchemaForm.java
https://jira.talendforge.org/browse/TMDM-12326
=> TMDM-12326 ArrayIndexOutOfBoundsException on tMDMOutput

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
fix TUP-20251 Unable to create a tag (Cloud)
https://jira.talendforge.org/browse/TUP-20251
=> fix TUP-20251 Unable to create a tag (Cloud)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/ArtifactRepositoryBean.java
fix(TUP-20318) CommandLine uses localhost url for publishing
https://jira.talendforge.org/browse/TUP-20318
=> fix(TUP-20318) CommandLine uses localhost url for publishing

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/context/RepositoryContext.java
https://jira.talendforge.org/browse/TUP-20356
=> item(TUP-20356): Lock user recognize both login and ldap ID

test/plugins/org.talend.migrationTool.test/src/org/talend/migrationtool/MigrationTaskValidator.java
https://jira.talendforge.org/browse/TUP-20357
Add junit to validate migrationTask configuration
=> fix(TUP-20357): Unable to migrate DI project from 6.5.1 To 7.0.1

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/ConnParameterKeys.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ExtendedNodeConnectionContextUtils.java
some fields in DI job
https://jira.talendforge.org/browse/TUP-19900
=> fix(TUP-19900)tPigload component using HCatalog in repository cannot get

main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TUP-20407
=> TUP-20407 : update tacokit version to 1.0.2-SNAPSHOT

main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java, main/plugins/org.talend.model/src/main/java/org/talend/cwm/helper/ConnectionHelper.java, main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/repository/migration/UnifyPasswordEncryption4MDMConnectionMigrationTask.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/migration/UnifyPasswordEncryption4LdapConnectionMigrationTask.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/migration/UnifyPasswordEncryption4SalesforceSchemaConnectionMigrationTask.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/migration/UnifyPasswordEncryption4WsdlConnectionMigrationTask.java
https://jira.talendforge.org/browse/TUP-20391
=> fix(TUP-20391): Migration tasks are re-executed and encrypting passwords

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/wizard/models/ImportNodesBuilder.java
https://jira.talendforge.org/browse/TUP-20317
=> fix(TUP-20317)node of JDBC should be hidden when import db items

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/EParameterFieldType.java
Linked to jira https://jira.talendforge.org/browse/TDM-6267
=> TUP-20449 New parameter field type needed for TDM

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/recyclebin/RecycleBinManager.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
TUP-20448 exception show in error log when i export a job contain connection then import it again
https://jira.talendforge.org/browse/TUP-20448
=> TUP-20448 exception show in error log when i export a job contain connection then import it again

main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
needed for https://jira.talendforge.org/browse/TCOMP-918
=> TCOMP-918 bump tacokit version to 1.0.4-SNAPSHOT

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/JobContextManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/ContextSetConfigurationDialog.java
do not get updated in the main project.
=> fix(TUP-20411):Adding context environment in the reference project, they

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
added pom-microservice and pom-control-bundle to SVN accepted pom files pattern.
=> fix(TESB-22816): added pom-microservice and pom-control-bundle to patterns

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericWizardService.java
getting "UNEXPECTED_EXCEPTION" upon selecting the same connection
created.
=> fix(TUP-20492):When doing extract as context for a tsalesforceinput,

main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
also made little refactor, see inline comments for details.
=> fix(TESB-23022): added tRouteIn and tRouteLoop as ESB components

main/plugins/org.talend.utils/src/main/java/org/talend/utils/database/Constants.java
this driver works both MySQL 8 and MySQL 5
=> Update default Driver for Mysql

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/InputStreamProvider.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/manager/ResourcesManager.java
TUP-20448 exception show in error log when i export a job contain connection then import it again (Fix command line's issue)
https://jira.talendforge.org/browse/TUP-20448
=> TUP-20448 exception show in error log when i export a job contain

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
=> fix(TUP-20526):Not able to run job with reference project joblet on

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
https://jira.talendforge.org/browse/TUP-20592
=> fix(TUP-20592)Null Pointer Exception when building/publishing a job

main/plugins/org.talend.designer.maven.aether/META-INF/MANIFEST.MF, main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/DynamicDistributionAetherUtils.java
https://jira.talendforge.org/browse/TUP-20105
=> feat(TUP-20105): Change hortonworks setup to set the default proxy from talend

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/types/ContextParameterJavaTypeManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/types/JavaTypesManager.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/nattableTree/ContextNatTableConfiguration.java
jobs/joblets
https://jira.talendforge.org/browse/TUP-20458
=> feat(TUP-20458)Implement the resource dependencies editor page for DI

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/repository/item/ItemProductValuesHelper.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/ItemDateParser.java, main/plugins/org.talend.model/src/main/java/org/talend/core/model/properties/impl/PropertyImpl.java, main/plugins/org.talend.model/src/main/java/org/talend/cwm/helper/ResourceHelper.java
https://jira.talendforge.org/browse/TMDM-11731
=> TMDM-11731 Fix NumberFormatException throwed during parse date string.

test/plugins/org.talend.core.runtime.test/src/org/talend/core/runtime/repository/item/ItemProductValuesHelperTest.java
https://jira.talendforge.org/browse/TMDM-11731
=> TMDM-11731 Fix compile error.

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
link: https://jira.talendforge.org/browse/TMDM-12508
=>     TMDM-12508  Import view will show error for the view name is case sensitive in import dialog.

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
link: https://jira.talendforge.org/browse/TMDM-12508
=> TMDM-12508 Import view will show error for the view name is case sensitive in import dialog.

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/nexus/NexusDownloadHelperWithProgress.java
=> fix(TUP-20625):Studio displays nexus password if any artifact repository

main/plugins/org.talend.librariesmanager/resources/java/routines/system/ParserUtils.java, test/plugins/org.talend.librariesmanager.test/src/routines/system/ParserUtilsTests.java
Add a method to parse epoch time to java Date.
Relates to https://github.com/Talend/tdi-studio-se/pull/2643
=> Add epoch time parser

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/delimited/DelimitedFileStep3Form.java
Error occured in error log when conn file connection with context model
https://jira.talendforge.org/browse/TUP-20490
=> fix(TUP-20490)Error occured in error log when conn file connection with context model

main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/DynamicDistributionAetherUtils.java
https://jira.talendforge.org/browse/TUP-20704
=> item(TUP-20704): Update nexus url for dynamic distributions in studio

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
https://jira.talendforge.org/browse/TUP-20678
=> feat(TUP-20678): Add APAC datacenter to the list on the studio (license / connection)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/TalendProcessArgumentConstant.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/TemplateFileUtils.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java, test/plugins/org.talend.core.runtime.test/resources/template.xml, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/TemplateFileUtilsTest.java
=> bugfix(TUP-7208):bat & sh are exported to zip if I select Unix for Shell

main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
=> bugfix(TUP-20617):Can't import the data models if the data containers

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
are not commited to SVN when migrating from 6.0 to 7.1 using commandline
https://jira.talendforge.org/browse/TUP-20606
=> fix(TUP-20606)relationship.index/project.settings/migration_task.index

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/TemplateFileUtils.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/TemplateFileUtilsTest.java
bat & sh are exported to zip if I select Unix for Shell Launcher
=> bugfix(TUP-7208):

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenStandardJobOSGiPom.java
feat(TESB-22869):Change OSGi pom template for CI publish to cloud
=> feat(TESB-22869):Change OSGi pom template for CI publish to cloud

main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/DynamicDistributionAetherUtils.java
https://jira.talendforge.org/browse/TUP-20803
=> fix(TUP-20803): Bad maven reference for apache-curator

main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ui/actions/AContextualAction.java
run a job
https://jira.talendforge.org/browse/TUP-20315
=> fix(TUP-20315)NPE show in error log when click Project settings after

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/core/IDesignerCoreService.java, main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
https://jira.talendforge.org/browse/TUP-20284
=> fix(TUP-20284)Import Items throw errors

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java, main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java, test/plugins/org.talend.core.repository.test/src/org/talend/repository/utils/ProjectDataJsonProviderTest.java
fix(TUP-20903)Possible to import 7.1.1 project into a 6.4.2 release
https://jira.talendforge.org/browse/TUP-20903
=> fix(TUP-20903)Possible to import 7.1.1 project into a 6.4.2 release

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/recyclebin/RecycleBinManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
* fix(TUP-20620): Studio commits to remote repo, regardless of any
changes
locally
https://jira.talendforge.org/browse/TUP-20620
Conflicts:
main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/recyclebin/RecycleBinManager.java
main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
test/plugins/org.talend.core.repository.test/src/org/talend/repository/utils/ProjectDataJsonProviderTest.java
=> fix(TUP-20620): Studio commits to remote repo, regardless of any changes locally (#1886)

main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/DynamicDistributionAetherUtils.java
fix(TUP-20803): Bad maven reference for apache-curator
https://jira.talendforge.org/browse/TUP-20803
=> fix(TUP-20803): Bad maven reference for apache-curator (#1888)

main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/feature/FeaturesManager.java, main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/model/P2ExtraFeature.java
https://jira.talendforge.org/browse/TUP-20875
=> fix(TUP-20875): Components Manager: errors when do cancel the install patch/components

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ReferenceProjectProblemManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ReferenceProjectProvider.java
Fix (TUP-20887) Sub-reference project is listed in Reference Project settings if Sub-reference project is deleted in TAC
https://jira.talendforge.org/browse/TUP-20887
=> Fix (TUP-20887) Sub-reference project is listed in Reference Project

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/nattableTree/ContextParaModeChangeMenuConfiguration.java
resource dependency only
https://jira.talendforge.org/browse/TUP-20789
For now Resource type only restricted by built-in
=> feat(TUP-20789)Remove the dependencies page and use context view for

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ReferenceProjectProblemManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ReferenceProjectProvider.java
Revert "Fix (TUP-20887) Sub-reference project is listed in Reference Project (#1905)"
=> Revert "Fix (TUP-20887) Sub-reference project is listed in Reference

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/ReflectionUtils.java
https://jira.talendforge.org/browse/TUP-20973
=> fix(TUP-20973): [BUG] Failed Test Connection for HBase of dynamic CDH 6.0.0 cluster

main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/system/EclipseCommandLine.java, test/plugins/org.talend.commons.runtime.test/src/org/talend/commons/utils/system/EclipseCommandLineTest.java
https://jira.talendforge.org/browse/TUP-20985
=> fix(TUP-20985): Studio cant be installed in a folder with space in folder name

main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
THIS IS PREPARATION FOR RELEASE.
DON'T MERGE UNTIL 0.25.2 IS RELEASED
=> chore: update Components version to 0.25.2

main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/system/EclipseCommandLine.java, test/plugins/org.talend.commons.runtime.test/src/org/talend/commons/utils/system/EclipseCommandLineTest.java
https://jira.talendforge.org/browse/TUP-20985
=> fix(TUP-20985): Studio cant be installed in a folder with space in folder name(#1926)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/IRepositoryArtifactHandler.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/TalendLibsServerManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/TalendMavenResolver.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IMavenUIService.java, main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/MavenUIService.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/nexus/NexusDownloadHelperWithProgress.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/AbstractArtifactRepositoryHandler.java, main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/nexus/component/ComponentsDeploymentManager.java
=> fix(TUP-20998):Can not download jars from custom nexus after use

main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/system/EclipseCommandLine.java, test/plugins/org.talend.commons.runtime.test/src/org/talend/commons/utils/system/EclipseCommandLineTest.java
https://jira.talendforge.org/browse/TUP-20985
=> fix(TUP-20985): Studio cant be installed in a folder with space in folder name(#1926) (#1929)

main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/nexus/component/ComponentIndexManager.java
https://jira.talendforge.org/browse/TUP-21019
=> fix(TUP-21019): Can't install component patch in some special cases

main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/model/P2ExtraFeature.java, main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/ui/ShowWizardHandler.java
https://jira.talendforge.org/browse/TUP-21043
=> fix(TUP-21043): Can't pop up restart studio window automatically after complete installation required jar and bpm feature

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IResourcesDependenciesService.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
job first after change the resources item
https://jira.talendforge.org/browse/TUP-20913
=> fix(TUP-20913)Remote project:job run use old data if not run the child

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/TalendQuoteUtils.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/utils/TalendQuoteUtilsTest.java
bugfix(TUP-20693):Table selection widget - wrong generated code
=> bugfix(TUP-20693):Table selection widget - wrong generated code (#1911)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/AbstractUpdateManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/IUpdateManager.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericWizardService.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java
* bugfix(TUP-20837):Job containing saleforce components takes too much
time to open
=> Hwang/tup 20837 master (#1958)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IRunProcessService.java, main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/model/MavenSystemFolders.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/MavenProjectUtils.java
fix(TUP-21005)In studio Java Debugging of Routes fails
=> Jzhang/bugfix backport702/tup 21005 in studio java debugging of routes fails

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-20862
=> fix(TUP-20862): Folder in "poms\jobs" won't be updated after move around spark job folders in studio repository (#1974)

main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/model/emf/TalendXMIResource.java
=> bugfix(TUP-20038):Studio is vulnerable to entity expansion attacks when

main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/service/ITaCoKitService.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/constants/FileConstants.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ComponentsJsonModel.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
https://jira.talendforge.org/browse/TUP-21055
=> fix(TUP-21055)Migration check executed at each start of studio

main/plugins/org.talend.librariesmanager/resources/java/routines/TalendDate.java
Backport of https://jira.talendforge.org/browse/TDI-40846
Related task: https://jira.talendforge.org/browse/TDI-41327
=> fix(TDI-40846): create isDateStrict in routines (#1823)

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/AbstractEMFRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-21075
=> fix(TUP-20594)use duplicate name for jdbc connection, no error show

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/TalendProcessOptionConstants.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IRunProcessService.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
=> feat(TUP-20633):Add a command to regenerate all the poms of jobs in a project.

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
=> fix(TUP-21054):backport to 7.1

main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IProcessor.java, main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
JOB_GN_SFDC_LANCEUR_FLUX_DELTA_REG14.
=> fix(TUP-20979):OutOfMemoryError error when do build job

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
TUP-21144 Talend Studio very bad performances or stuck in Job Generation (Build)
https://jira.talendforge.org/browse/TUP-21144
=> TUP-21144 Talend Studio very bad performances or stuck in Job Generation

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java, main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java
https://jira.talendforge.org/browse/TUP-21085
=> fix(TUP-21085)Need to remove warning of technical migration

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java, main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java
fix(TUP-21085)Need to remove warning of technical migration
https://jira.talendforge.org/browse/TUP-21085
=> fix(TUP-21085)Need to remove warning of technical migration (#2013)

main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/editor/AbstractMetadataTableEditorView.java
https://jira.talendforge.org/browse/TUP-21107
=> fix(TUP-21107)Components don't save the field name properly

test/plugins/test.all.test.suite/src/test/common/BundleTestCollector.java
fixed an NPE when launching test suite.
=> fix(TESB-23687) : fixed tests

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
fix(TUP-21131)Miss "Additional parameter" text box when type "String of connection"
https://jira.talendforge.org/browse/TUP-21131
=> fix(TUP-21131)Miss "Additional parameter" text box when type "String of

main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TUP-21149
=> feat: upgrade Tacokit runtime version to 1.1.2

main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/exception/ExceptionMessageDialog.java
https://jira.talendforge.org/browse/TUP-21216
=> bugfix(TUP-21216):Audit:Generate Report:NPE when do refresh

main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/selector/DynamicDependencySelector.java, main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/DynamicDistributionAetherUtils.java
https://jira.talendforge.org/browse/TUP-21288
=> item(TUP-21288): Allow to use multi-thread to collect dynamic distribution dependencies

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/StudioSSLContextProvider.java
* fix(TUP-21142)Restore SSL config has error in error log
* fix(TUP-21142)SSL ERROR
=> fix(TUP-21142)Restore SSL config has error in error log (#2058)

main/plugins/org.talend.librariesmanager/resources/java/routines/Numeric.java
* throw RuntimeException if max value is less than or equal to min
=> fix(TDI-31052): tRowGenerator Numeric.random

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java
6.4.1 to 7.1.1
https://jira.talendforge.org/browse/TUP-21245
=> fix(TUP-21245)faile to check JDBC connection with context Migrate from

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ITDQRepositoryService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java, main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/context/ContextWizard.java
TDQ-16114 Action not correct when Rename variable but select NO option
- move the update DQ side context from context wizard to
RepositoryUpdateManager
- change the parameter in ITDQRepsototyService for updating context
=> Item    TDQ-15353 Rename variable issue for Repository context

main/plugins/org.talend.core/src/main/java/org/talend/core/model/migration/AbstractAllJobMigrationTask.java, main/plugins/org.talend.core/src/main/java/org/talend/core/model/migration/AbstractBDJobMigrationTask.java, main/plugins/org.talend.core/src/main/java/org/talend/core/model/migration/AbstractJobMigrationTask.java
when import a 621 testcase for tFileoutputDelimited component
=> bugfix(TUP-21134):"Throw an error if the file already exist" is ticked

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ModuleNeeded.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/TalendProcessOptionConstants.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/AbstractMavenProcessorPom.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
when spark job launched from standard job by jobserver
https://jira.talendforge.org/browse/TUP-21356
=> bugfix(TUP-21356):"talend-bigdata-launcher-1.2.0-20170410.jar" not found

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/ExtractManager.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/dbs/IBMDB2ExtractManager.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/dbs/MSSQLExtractManager.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/dbs/OracleExtractManager.java
for table
https://jira.talendforge.org/browse/TUP-21086
=> fix(TUP-21086)Unable to retrieve the schema from Synonym but works fine

main/features/org.talend.platform.feature/feature.xml
https://jira.talendforge.org/browse/TUP-21119
=> feat(TUP-21119): Cleanup features, each plugin must be in one unique feature

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataFromDataBase.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/ExtractManager.java, main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableFilterForm.java
=> fix(TUP-20360): In the Mysql database, For the system databases like mysql, information_schema retrieve schema is not working.

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbstractNode.java
https://jira.talendforge.org/browse/TUP-21333
=> fix(TUP-21333)OnSubJob Links Not Working

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbstractNode.java
https://jira.talendforge.org/browse/TUP-21333
=> fix(TUP-21333)OnSubJob Links Not Working (#2093)

main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
Fix TUP-21498 The port of Sybase did not display right on DI side
https://jira.talendforge.org/browse/TUP-21498
=> Fix TUP-21498 The port of Sybase did not display right on DI side

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/context/ContextWizard.java
=> Fix   TDQ-16340 created context group need a refresh to show in

main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/xml/XmlNodeRetriever.java, main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/dnd/MDMLinker.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/extraction/XmlToXPathLinker.java
TUP-21263 Consider setting the secure processing feature on XPathFactory instances
https://jira.talendforge.org/browse/TUP-21263
=> TUP-21263 Consider setting the secure processing feature on XPathFactory

main/plugins/org.talend.core/src/main/java/org/talend/core/model/genhtml/HTMLHandler.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java, main/plugins/org.talend.utils/META-INF/MANIFEST.MF, main/plugins/org.talend.utils/src/main/java/org/talend/utils/wsdl/WSDLLoader.java, main/plugins/org.talend.utils/src/main/java/org/talend/utils/xml/XmlUtils.java
Fix TUP-21305 Set the secure processing feature on TransformerFactory instances
https://jira.talendforge.org/browse/TUP-21305
=> Fix TUP-21305 Set the secure processing feature on TransformerFactory instances

main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonNavigator.java
https://jira.talendforge.org/browse/TUP-21496
=> bugfix(TUP-21496): Always pop up "Refreshing" dialog

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenStandardJobOSGiPom.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
S3 component and standard DI job having S3 connection component fails
with an error.
=> fix(TUP-21532):Standard DI job which refers to big data batch job having

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/IRepositoryFactory.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DeleteAction.java, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/EmptyRecycleBinAction.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IRunProcessService.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/IProxyRepositoryFactory.java, main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
GIT mode
https://jira.talendforge.org/browse/TUP-19978
=> fix(TUP-19978)It is very slow to delete many items at the same time on

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
https://jira.talendforge.org/browse/TUP-21646
=> fix(TUP-21646): Job Build hangs when the "-talendDebug" flag are enabled

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/AbstractMavenProcessorPom.java
Run->console after running a specific job
=> fix(TUP-21552):"Could not find the context Default" shows in

main/plugins/org.talend.designer.maven.tos/resources/build/plugins/spring-boot-maven-plugin-1-5-9-RELEASE/pom.xml
Reverts Talend/tcommon-studio-se#2173
=> Revert "TESB-24386:High CVE Vulnerability found in Talend Components"

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/EParameterFieldType.java
https://jira.talendforge.org/browse/TUP-21467
=> feat(TUP-21467): add TACOKIT_SUGGESTABLE_TABLE widget

main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/DBConnectionContextUtils.java, test/plugins/org.talend.metadata.managment.ui.test/src/main/test/org/talend/metadata/managment/ui/utils/DBConnectionContextUtilsTest.java
https://jira.talendforge.org/browse/TUP-20974
Fix url problem
=> fix(TUP-20974): [BUG] Impala connection failed on CDH 6.0.0

main/plugins/org.talend.librariesmanager/resources/java/routines/TalendString.java, main/plugins/org.talend.utils/src/main/java/org/talend/utils/IdGenerator.java
https://jira.talendforge.org/browse/TUP-21307
=> workItem(TUP-21307):Duplicate code in IdGenerator + TalendString

main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/AbstractMavenProcessorPom.java
This commit also includes fix of TUP-21552 by @zwxue
=> [TESB-22363] Build the route which contains cTalendJob failed in studio

main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/CryptoHelper.java
Reverts Talend/tcommon-studio-se#2202
=> Revert "Ttao/bugfix/tup 21205 remove crypto helper from tcommon se ee"

main/features/org.talend.utils.feature/feature.xml, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ParameterValueUtil.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/maven/MavenUrlHelper.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/StudioSSLContextProvider.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ui/login/connections/EncryptedProperties.java, main/plugins/org.talend.model/src/main/java/org/talend/core/model/metadata/builder/connection/impl/ConnectionImpl.java, main/plugins/org.talend.model/src/main/java/org/talend/cwm/helper/ConnectionHelper.java, main/plugins/org.talend.model/src/main/java/org/talend/designer/core/model/utils/emf/talendfile/impl/ContextParameterTypeImpl.java, main/plugins/org.talend.model/src/main/java/org/talend/designer/core/model/utils/emf/talendfile/impl/ElementParameterTypeImpl.java, main/plugins/org.talend.model/src/main/java/org/talend/designer/core/model/utils/emf/talendfile/impl/ElementValueTypeImpl.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/designerproperties/RepositoryToComponentPropertyForPasswordTest.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/ParameterValueUtilTest.java, test/plugins/org.talend.metadata.managment.ui.test/src/main/test/org/talend/metadata/managment/ui/utils/OtherConnectionContextUtilsTest.java, test/plugins/org.talend.utils.test/src/org/talend/utils/security/CryptoHelperTest.java
Reverts Talend/tcommon-studio-se#2189
=> Revert "fix(TUP-21205):Remove CryptoHelper from tcommon-studio-se +"

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/dialogs/EventLoopProgressMonitor.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
be "/" instead of "-" when running testcase
=> bugfix(TUP-6176):TestCase: Path Seperator in Progress Infomation should

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/ItemCacheManager.java
Fix TUP-21692 Trunjob will miss its child when you do export out the job in project and import in another project.
https://jira.talendforge.org/browse/TUP-21692
=> Fix TUP-21692 Trunjob will miss its child when you do export out the job in project and import in another project.

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/XSDValidater.java
https://jira.talendforge.org/browse/TUP-21251
=> workitem(TUP-21251):Replace com.sun.org.apache.xerces.internal.jaxp

main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/dbs/OracleExtractManager.java
=> fix(TUP-21641)Oracle,Next wouldn't enabled after "Creation Status" is

main/plugins/org.talend.utils/pom_server.xml, main/plugins/org.talend.utils/src/main/java/org/talend/utils/ssl/SSLUtils.java
TUP-21308 Fix SSLUtils TLS configuration
https://jira.talendforge.org/browse/TUP-21308
=> TUP-21308 Fix SSLUtils TLS configuration

main/plugins/org.talend.utils/src/main/java/org/talend/utils/ssl/SSLUtils.java
Studio cannot launch. This reverts commit 430b425626603100d6eff863179ef586978895f3.
=> DEVOPS-6216 Revert "TUP-21308 Fix SSLUtils TLS configuration (#2200)"

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java, main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
Fix TUP-21911 Build job takes about 4 minutes while Run job takes > 40 minutes to start
https://jira.talendforge.org/browse/TUP-21911
=> Fix TUP-21911 Build job takes about 4 minutes while Run job takes > 40

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java, main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
Fix TUP-21911 Build job takes about 4 minutes while Run job takes > 40 minutes to start
https://jira.talendforge.org/browse/TUP-21911
=> Fix TUP-21911 Build job takes about 4 minutes while Run job takes

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ModuleNeeded.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
=> bugfix(TDI-41803):Job migrated from 6.5.1 to 7.1.1 throwing

main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/utils/io/FileCopyUtils.java
kjwang/Fix TUP-22005 Unexpected Empty Contexts Variable Values
https://jira.talendforge.org/browse/TUP-22005
=> kjwang/Fix TUP-22005 Unexpected Empty Contexts Variable Values

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
#	main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
=> fix(TDI-41285): Error of compilation due to wrong split of SQL query

main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/utils/io/FileCopyUtils.java
kjwang/Fix TUP-22005 Unexpected Empty Contexts Variable Values
https://jira.talendforge.org/browse/TUP-22005
=> kjwang/Fix TUP-22005 Unexpected Empty Contexts Variable Values (#2262)

main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ModuleLicenseDialog.java, main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/wizards/AcceptModuleLicensesWizardPage.java, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/i18n/messages.properties, main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/salesforce/BrowerDialog.java
=> fix(TUP-22145)Error pops up after clicked accept license when

main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/dialogs/SSLDialog.java
https://jira.talendforge.org/browse/TUP-18064
=> feat(TUP-18064): [Studio] Update to more recent Eclipse (4.10)

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
https://jira.talendforge.org/browse/TUP-21920
=> fix(TUP-21920)Nullpointer on build job

main/plugins/org.talend.librariesmanager/resources/java/routines/system/PasswordEncryptUtil.java
=> Dsylaiev/tdi 41808 fix showing pass nzload (#2276)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/IGenericElementParameter.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/ContextTreeTable.java
group variable set for connection type Oauth.
https://jira.talendforge.org/browse/TUP-21903
=> fix(TUP-21903):tSalesForceConnection JWT flow does not work with Context

main/plugins/org.talend.repository.mdm/resources/UpdateReport.xsd
https://jira.talendforge.org/browse/TMDM-11900
=> TMDM-11900 Update schema of UpdateReport, add 'UUID' field for standalone mode.

main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java
* Add util method to escape special symbols
=> fix(TDI-41951): special chars in column comment

main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java
* Add util method to escape special symbols
=> fix(TDI-41951): special chars in column comment (#2293)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/DiSchemaConstants.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolAvroHelper.java
https://jira.talendforge.org/browse/TDI-42013
=> fix(TDI-41188): map Snowflake Time type to Talend Date instead of Talend Integer (#2009)

main/plugins/org.talend.core.runtime/mappings/mapping_Vertica.xml
https://jira.talendforge.org/browse/TDI-41790 
Vertica Db Integer columns incorrectly interpreted as Java Integer
Mapping was changed.
=>  fix(TDI-41790): change mapping for numbers

main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/i18n/messages.properties, main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/view/RepositoryDropAdapter.java, test/plugins/org.talend.core.repository.test/src/org/talend/core/repository/ui/view/RepositoryDropAdapterTest.java
containing an already open job to another folder
https://jira.talendforge.org/browse/TUP-21925
=> fix(TUP-21925):Empty pop-up error message when moving a folder

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolAvroHelper.java
apache AVRO schema have default values.
=> fix(TDI-41876):Importing job from 6.2.1 to 7.1.1 is throwing error.

main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java, main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenStandardJobOSGiPom.java
TUP-22281 Missing jar in lib folder for Job Server(Solution 2) 
https://jira.talendforge.org/browse/TUP-22281
=> TUP-22281 Missing jar in lib folder for Job Server(Solution 2)

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/INexus3SearchHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/Nexus3BetaSearchHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/Nexus3ScriptSearchHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/Nexus3V1SearchHandler.java
Fix TUP-22469 Nexus3.15: studio can't detect patch for 701/711 release
=> Fix TUP-22469 Nexus3.15: studio can't detect patch for 701/711 release

main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/INexus3SearchHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/Nexus3BetaSearchHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/Nexus3ScriptSearchHandler.java, main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/Nexus3V1SearchHandler.java
Fix TUP-22469 Nexus3.15: studio can't detect patch for 701/711 release
=> Kjwang/fix tup 22469 nexus3.15 b70

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataTable.java, main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolHelper.java, main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/dialog/MetadataDialog.java
Fix TUP-22425 [7.1.1] Stackoverflow issue in studio
https://jira.talendforge.org/browse/TUP-22425
=> Kjwang/fix tup 22425 stackoverflow (#2322)

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolAvroHelper.java
Back-port for 7.0
apache AVRO schema have default values.
=> fix(TDI-41876):Importing job from 6.2.1 to 7.1.1 is throwing error. back-port 7.0

main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
https://jira.talendforge.org/browse/TUP-21920
Loop dependency classpath issue caused main class not found
=> fix(TUP-21920)Nullpointer on build job (#2309)

main/plugins/org.talend.librariesmanager/resources/java/routines/system/StringUtils.java
* fix(TBD-7687): tFileInputDelimited issue with separator
add a null instead of delete the column
* Update StringUtils.java
=> fix(TBD-7687): tFileInputDelimited issue with separator (#2314)

main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TUP-22610
=> item(TUP-22610): update tacokit to version 1.1.9

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/ArtifactRepositoryBean.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/nexus/ArtifactRepositoryBeanTest.java
https://jira.talendforge.org/browse/TUP-22182
=> fix(TUP-22182)Non-default Artifactory context path, not working

main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/ArtifactRepositoryBean.java, test/plugins/org.talend.core.runtime.test/src/org/talend/core/nexus/ArtifactRepositoryBeanTest.java
* fix(TUP-22182)Non-default Artifactory context path, not working
https://jira.talendforge.org/browse/TUP-22182
* fix(TUP-22182)Non-default Artifactory context path, not working
https://jira.talendforge.org/browse/TUP-22182
=> fix(TUP-22182)Non-default Artifactory context path, not working (#2338)

main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/ExtraFeaturesUpdatesFactory.java, main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/AbstractExtraUpdatesFactory.java, main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/TOSDynamicExtraFeaturesFactory.java, main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/feature/FeaturesManager.java, main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/ui/CheckExtraFeaturesToInstallJob.java, main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/ui/UpdateStudioWizard.java
kjwang/Feat TUP-21191 Remove any internet check
TUP-21191 Remove any internet check from Additional package dialog
=> kjwang/Feat TUP-21191 Remove any internet check
