- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/BigDataNode.java
BigDataNode use the input connection instead of the output connection to create the KeyList.
> [TBD-1978] Little fix to avoid NullPointer exception.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/EDatabase4DriverClassName.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/dburl/SupportDBUrlType.java
JDBC driver
https://jira.talendforge.org/browse/TDI-32783
> TDI-32783: "ca.ingres.jdbc.IngresDriver" have been removed in Ingres new

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
65535 bytes limit when we checked option activate log4j in components
use string literal instead of too many append() method
> TDI-33301: tHashInput_1Process(Map<String,Object>) is exceeding the

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
exceeding the
65535 bytes limit when we checked option activate log4j in components
use string literal instead of too many append() method
> TDI-33301 , TDI-33066: tHashInput_1Process(Map<String,Object>) is

- main/plugins/org.talend.commons.runtime/talend.properties
Can we update this file to 6.1.0 right away on master?  Leaving it at 6.0.1 causes the studio to fail after 6.1.0 migration tasks are applied to a workspace project.
> Update master version to 6.1.0 (necessary for migration tasks).

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/ComponentUtilities.java
jobs which include tOracleOutput/tTeradataOutput with reject row have an
error alarm
https://jira.talendforge.org/browse/TDI-34018
> TDI-34018: A wrong migration task  in TDI-31497 for use batch cause old

- main/plugins/org.talend.libraries.apache.cxf/build.properties
include cxf-tools-common-3.1.3.jar
https://jira.talendforge.org/browse/TDI-34435
> TDI-34435: Change build.properties of org.talend.libraries.apache.cxf to

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/IHadoopClusterService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/repository/HadoopRepositoryUtil.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
TBD-3202: [6.1.1] Hive properties dont get submitted correctly when
re-using context
TBD-3212: hadoop cluster:hadoop property is added double quotes when
drag hdfs schema to a standard job
> Fixed the bugs:

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/JobContextManager.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/context/JobContextManagerTest.java
> TUP-4534: HDFS&Context:"xmi:id" should not changed after rename

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
TUP-4567: When open a main project job, the merged refer project job will disappear.
> TUP-4567: When open a main project job, the merged refer project job will disappear.

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/wizard/models/ImportNodesBuilder.java
on "Import items" dialog standard job folder show same level with  "Standard" node, but should under  "Standard" node
https://jira.talendforge.org/browse/TDI-36633
> TDI-36633 fix: On "Import items" dialog standard job folder show same

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
components
https://jira.talendforge.org/browse/TUP-5644
> TUP-5644 fix: EXASolution metadata wizard expects different driver than

- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/ExtractManager.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableWizard.java
made retrieve schemas very slow.
> TUP-5859: The dbconnection is closed and recreated for many times, which

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
The impala wizard does not have the username filed, but the impala
component has that
> TUP-15801 fix:

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/CommonsPlugin.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
Hi,
ESB Micorservice bundle still need maven online to build as a jar, we still not find a simple way to build this spring boot bundle iwth maven offline setting, so I added a checked in CommonsPlugin.java for the commandline builds ESB Micorservice jar, if the commandline is building ESB Micorservice, it will ignore to switch maven to offline, for any other cases, it will keep maven offline setting.
Thanks,
Yi Yan
> TESB-17856: For commandline builds ESB Micorservice bundle

- main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonViewer.java
TUP-15968 Fix Get in a freshly install 6.1.2 Studio, this error in the log " org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
https://jira.talendforge.org/browse/TUP-15968
> TUP-15968 Fix Get in a freshly install 6.1.2 Studio, this error in the

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DuplicateAction.java
TUP-16472 Then icon will not change directly when converting between MR and Spark job by duplicate
https://jira.talendforge.org/browse/TUP-16472
> TUP-16472 Then icon will not change directly when converting between MR and Spark job by duplicate

- main/plugins/org.talend.libraries.jdbc.access/pom.xml
need to merge it after talend-ucanaccess-utils lib appear in talend-newbuild repository.
> fix(TDI-33559): tAccessXX don't work when access database encrypted

- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
characters does not correctly duplicate
> TUP-17238:A function "Duplicate" for metadata named in multi-byte

- main/plugins/org.talend.librariesmanager/resources/java/routines/system/TalendDataSource.java
There are still some components are using the close method, so we could remove the close method later.
> TESB-18908:Memory-Leak in TalendDataSource implementation

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/hd/IHDistributionVersion.java
Context menu "Create Oozie" should not show on Cloudera Spark 2 Hadoop
Cluster
https://jira.talendforge.org/browse/TUP-17371
> bugfix TUP-17371

- main/plugins/org.talend.libraries.apache.cassandra/plugin.xml
We build the Spark Cassandra Connector against Scala 2.11 (spark-cassandra-connector-assembly-2.0.2-patched-20170519.jar is generated).
Please see https://github.com/Talend/spark-cassandra-connector/blob/master/doc/12_building_and_artifacts.md
> feat(TBD-5000): Add Spark 2.1 in local mode

- main/plugins/org.talend.librariesmanager/resources/java/routines/system/xml/sax/NamespaceFilter.java
* Introduced SAX filter which removes namespace mappings from XML
This PR is part of https://github.com/Talend/tdi-studio-se/pull/1319
> fix(TDI-34726): Implement SAX filter for removing of namespaces

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
*when have many context groups within Hive, Hbase, Hcate or HDFS, open
their wizard will not pop up select-context dialog now. 
*dialog will not appear when check service also.
https://jira.talendforge.org/browse/TUP-18019
> fix(TUP-18019)context group dialog popup manytimes when check service

- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/gmf/util/DisplayUtils.java
fix(TUP-17098): better to give a "commit files" progress popup instead of just show it in right-bottom corner for git
https://jira.talendforge.org/browse/TUP-17409
> fix(TUP-17098): better to give a "commit files" progress popup instead of just show it in right-bottom corner for git

- main/plugins/org.talend.librariesmanager/resources/java/routines/system/BundleUtils.java
The pull request contains code of a Java class compiled into the "routines" library at job code generation. This class allows to perform some OSGi-related tasks in jobs without adding an explicit dependency on OSGi classes, as the helper class uses reflection and simply no-ops in non-OSGi deployments. In the context of bug TESB-20301 it is required to resolve an OSGi service (SAM agent access) in a nested job where the service is not provided upfront via Blueprint.
> TESB-20301 - Helper class for late resolution of OSGi services added.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
For https://jira.talendforge.org/browse/TDI-39518
Fix issue:
Get wrong right quote index when replace CRLF for memo property value.
> fix(TDI-39518) tSendMail job with multiline Message cannot be moved from 6.1.1 to 6.4.1

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
For https://jira.talendforge.org/browse/TDI-39542
typo of NodeUtil method
Change `getFakeRithtQuotes` to `getFakeRightQuotes`
> fix(TDI-39542): typo of NodeUtil method

- main/plugins/org.talend.librariesmanager/resources/java/routines/TalendDate.java
For jira: https://jira.talendforge.org/browse/TDI-39670
Make sure `TalendDate.formatDateInUTC()` and `TalendDate.parseDateInUTC()` don't change the original timezone of `FastDateParser.getInstance(pattern)`
This would influence other format or parse method.
> fix(TDI-39670) Side effect when using TalendDate.formatDateInUTC() and TalendDate.parseDate()

- main/plugins/org.talend.libraries.apache.cassandra/plugin.xml
Cherry-pick fix from 6.5 branch
> fix(TBD-5985): add nexus desc for spark-cassandra-assembly

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
Re-used simply the code existing in the past used for ESB only. (working on their side)
But make it more standard to use it on every kind of item.
> fix(TUP-19042) Find back project name if parent is null

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ILibraryManagerService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ILibrariesService.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListCellEditor.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/AbstractLibrariesService.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LibrariesService.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
In scope of the commit:
- Prevent appearance of orange "Additional library required" bar with "Install..." button for cConfig component when exteran ljar is added to dependency list (ModuleListCellEditor.java)
- Added method to LibraryService API to publish jars only to local studio reposiotry, without attempting to reach Nexus
> [TESB-20924] cConfig cannot install the external jar

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialog.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialogWithProgress.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/DownloadModuleRunnable.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/DownloadModuleRunnableWithLicenseDialog.java
Change done:
- have only one check of libraries instead of multiple for every jar installed (not related to current issue, but will improve performances also)
- when use the download dialog to install, do the check of libraries only after install the full list of jars from the dialog itself (instead of the download class)
> fix(TUP-19590) Fix the problem of download of jar during build

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
SubJob Processor is necessary to get location of SubJob artifacts (location of pom.xml, target folder etc)
> TESB-21427 Lost SubJob Processor is restored

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
Current issue is based on very "old" problem which is reproducable from Studio 6.4.1 (I did not check with oldest versions).
The problem is - empty Routes  are not compilable (for example, we will see many errors if  we open Route using "code" tab from Studio).
The reason of issue is - we have no "default" Route dependencies (all  dependencies are "extracted" from Route components). List of required "default" dependencies:
camel-core-VERSION.jar
camel-spring-VERSION.jar
spring-context-VERSION.jar
spring-beans-VERSION.jar
spring-core-VERSION.jar
We did not see "pup up with 'Job compile error'" before because of coresponding errors was supressed explicitly.
So, we can resolve this issue in few ways:
1. suppress error again, but we will face the same problem in case of Project will be built …
> TESB-21435 Default Route dependencies are added

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
provides fix for the case when Connection has "MAIN" connector name (it is true for TCOMP components), but "FLOW" is expected
> fix: fix wrong connector names for TCOMP components

- main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/setting/project/page/MavenProjectSettingPage.java
This fix avoids an NPE which occurs when the reference project dialog is closed with "ok" and avoids that the reference project is really added.
> fix(TUP-19883): Avoid NPE when closing reference project settings.

- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
Remove the force of reload, since the function will reload automatically the item (if the file exists).
> fix(TUP-19780) update fix of reload from repository

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
The expected handling of non-required libraries declared as bean dependencies is the following:
1. At compile time, the non-required library needs to be present.
2. At OSGi bundle build, the non-required library must not be included in the bundle, but the packages used by classes in the bundle shall be added to the imports in the manifest.
3. At microservice build, the non-required library shall be physically added.
The present fix changes the handling of non-required libraries to meet these expectations.
> fix(TESB-22034): Fix handling of non-required bean libs in route builds.

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
TESB-22034: Fix handling of non-required bean libs in route builds
> TESB-22034: Fix handling of non-required bean libs in route builds

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
The handling of non-required dependencies of beans used by routes has been improved to use a separate attribute and no longer bear any risk of interfering with dependency processing for routines.
> fix(TESB-22034): Improved handling of non-required bean deps in routes.

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/wsdl/WSDLLoader.java
- test/plugins/org.talend.utils.test/src/org/talend/utils/wsdl/TestService.wsdl
- test/plugins/org.talend.utils.test/src/org/talend/utils/wsdl/TestServiceBinding.wsdl
- test/plugins/org.talend.utils.test/src/org/talend/utils/wsdl/WSDLLoaderTest.java
Circular WSDL imports are not prohibited by WS-I basic profile. However, they are currently causing WSDL import to fail in an endless recursion. The present fix corrects this condition and ensures that WSDL documents are not imported more than once.
> fix(TESB-22183): Add support for circular WSDL imports to WSDLLoader.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/EParameterFieldType.java
PR adds new type of Parameter field - TacokitValueSelection.
It is the same field type as in Salesforce component (NAME_SELECTION_REFERENCE), but it works for Tacokit integration
https://jira.talendforge.org/browse/TCOMP-842
> feat(TCOMP-842): add Value Selection widget

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
fix(TUP-20303)project folder name not correct in workspace after import using "Import an existing project"
https://jira.talendforge.org/browse/TUP-20303
> fix(TUP-20303)project folder name not correct in workspace after import using "Import an existing project"

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/IProxyRepositoryFactory.java
RelationshipItemBuilder can also be used for other projects instead of
current project and reference projects during git merge.
> fix(TUP-20248) shouldn't have NPE but need to be able for

- main/plugins/org.talend.libraries.jdbc.exasol/pom.xml
https://jira.talendforge.org/browse/TDI-40917
Version of EXABulkUtil was updated
> fix(TDI-40917): update version of EXABulkUtil

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
At this moment Jobs which are referenced from Routelets using cTalendJob component are built as simple jars (not OSGI bundles). It happeds because of Built Type is not set. Current change propagates Build Type from root Route to child subjobs.
> TESB-23502 Propagation of build type to child Route/Routelet Jobs is added

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
This change must be reverted because of it does not resolve general issue with child Routets job processing. Besides, we have minor side effect - routes are marked as modified in Studio after Route is built.
> Revert "TESB-23502 Propagation of build type to child Route/Routelet Jobs is added"

- main/plugins/org.talend.librariesmanager/resources/java/routines/TalendDate.java
Create new method isDateStrict in routines to avoid too long method length, also not break existing methods usage.
> fix(TDI-40846): create isDateStrict in routines

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/DatabaseConnStrUtil.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/database/conn/DatabaseConnStrUtilTest.java
(#1870)
* fix(TUP-20758)Metadata connection to MSSQL with Integrated Security
and
TCP Dynamic ports
https://jira.talendforge.org/browse/TUP-20758
* fix(TUP-20758)Metadata connection to MSSQL with Integrated Security
and
TCP Dynamic ports
https://jira.talendforge.org/browse/TUP-20758
Add a junit
* fix(TUP-20758)Metadata connection to MSSQL with Integrated Security
and
TCP Dynamic ports
https://jira.talendforge.org/browse/TUP-20758
Conflicts:
test/plugins/org.talend.core.runtime.test/src/org/talend/core/database/conn/DatabaseConnStrUtilTest.java
> fix(TUP-20758)Metadata connection to MSSQL with Integrated Security and

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ReferenceProjectProblemManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ReferenceProjectProvider.java
Fix (TUP-20887) Sub-reference project is listed in Reference Project settings if Sub-reference project is deleted in TAC
https://jira.talendforge.org/browse/TUP-20887
> Fix (TUP-20887) Sub-reference project is listed in Reference Project

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-20862
> fix(TUP-20862): Folder in "poms\jobs" won't be updated after move around spark job folders in studio repository

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
Fix TUP-20835 CI Builder generation error if re-import job that previously existed
https://jira.talendforge.org/browse/TUP-20835
> Fix TUP-20835 CI Builder generation error if re-import job that previously existed

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
Fix TUP-20835 CI Builder generation error if re-import job that previously existed
https://jira.talendforge.org/browse/TUP-20835
> Fix TUP-20835 CI Builder generation error if re-import job that (#2047)

- main/plugins/org.talend.core/src/main/java/org/talend/core/model/metadata/query/AbstractQueryGenerator.java
- main/plugins/org.talend.core/src/main/java/org/talend/core/model/metadata/query/IQueryGenerator.java
Guess query is not correct for tHiveInput if hivetable name is used a context value(#2061)
* fix(TUP-20244)Guess query is not correct for tHiveInput if hivetable
name is used a context value
* fix(TUP-20244)Guess query is not correct for tHiveInput if hivetable
name is used a context value
> fix(TUP-20244)Guess query is not correct for tHiveInput if hivetable name is used a context value 

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/XsdMetadataUtils.java
The present fix handles the condition that with the import of several schemas of the same target namespace, not all types and elements are necessarily resolved in the scope of on XSD import.
> fix(TESB-24543): Fix NPE on WSDL import with several schemas in one TNS.

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
fix(TUP-21646): Job Build hangs when the "-talendDebug" flag are enabled
https://jira.talendforge.org/browse/TUP-21646
> fix(TUP-21646): Job Build hangs when the "-talendDebug" flag are enabled (#2168)

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/xml/XSDValidator.java
Fix TUP-21115 Enable secure processing disallow doctypes for DocumentBuilderFactory instances https://jira.talendforge.org/browse/TUP-21115 (XSDValidator open Doctype
option)
> Fix TUP-21115 Enable secure processing disallow doctypes for DocumentBuilderFactory instances

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
https://jira.talendforge.org/browse/TUP-21646
fix(TUP-21646): Job Build hangs when the "-talendDebug" flag are enabled
Conflicts:
main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
> fix(TUP-21646): Job Build hangs when the "-talendDebug" flag are enabled

- main/plugins/org.talend.presentation.onboarding/META-INF/MANIFEST.MF
- main/plugins/org.talend.presentation.onboarding/src/org/talend/presentation/onboarding/utils/OnBoardingUtils.java
license
For the html file DocumentBuilderfactory, we shouldn't set
XMLConstants.FEATURE_SECURE_PROCESSING feature to true.
https://jira.talendforge.org/browse/TUP-21880
> fix(TUP-21880):Quick tour page is blank when launch studio using ESB

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/xml/XSDValidator.java
https://jira.talendforge.org/browse/TUP-21987
1. Set attribute **XMLConstants.ACCESS_EXTERNAL_SCHEMA**=**platform** to fix the component loading exception mentioned in the jira ticket.
2. Set attribute **XMLConstants.ACCESS_EXTERNAL_DTD**=**file** to fix component loading exception, for example: https://github.com/Talend/tesb-studio-se/blob/snap/master/20190215_1937/main/plugins/org.talend.designer.camel.components.localprovider/components/cSetHeader/cSetHeader_java.xml#L2
> item(TUP-21987): Studio can't load components after upgrade studio target platform

- main/plugins/org.talend.libraries.apache/META-INF/MANIFEST.MF
TUP-22340 Missing jobs after importing with studio build after eclipse upgrade
https://jira.talendforge.org/browse/TUP-22340
> TUP-22340 Missing jobs after importing with studio build after eclipse upgrade

- main/plugins/org.talend.librariesmanager/plugin.xml
TUP-23121 :Error occurred when deploy cJMS route in runtime: org.talend.daikon.crypto.Encryption cannot be found by
local_project.MQMultiReceiver_0.1.0
https://jira.talendforge.org/browse/TUP-23121
> TUP-23121 :Error occurred when deploy cJMS route in runtime:

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/properties/tab/HorizontalTabFactory.java
Fix TUP-23244 Studio continuously throw "Attach is not supported for target JVM" after memory run
https://jira.talendforge.org/browse/TUP-23244
> Fix TUP-23244 Studio continuously throw "Attach is not supported for

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
Fix TUP-23170 New branch with name "/" will lead job with reference joblet build failure (Fix can't clean joblet cache problem)
https://jira.talendforge.org/browse/TUP-23170
> Fix TUP-23170 New branch with name "/" will lead job with reference

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
Fix TUP-22582 [CVE:high] Backend :pkg:maven/org.codehaus.plexus:plexus-utils:1.5.15 requires version upgrade (Fix can't build job with sub job)
https://jira.talendforge.org/browse/TUP-22583
> Fix TUP-22582 [CVE:high] Backend :pkg:maven/org.codehaus.plexus:plexus-utils:1.5.15 requires version upgrade (Fix can't build job with sub job)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/designerproperties/RepositoryToComponentPropertyTest.java
* fix(TUP-23588)For tCreateTable, the Database Type is always Mysql after
dragging and dropping from database Metadata
* fix(TUP-23588)For tCreateTable, the Database Type is always Mysql after
dragging and dropping from database Metadata
> fix(TUP-23588)For tCreateTable, the Database Type is always Mysql after dragging and dropping from database Metadata (#2603)

- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MDMOutputSchemaForm.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MDMTableForm.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MdmConceptWizardPage4.java
Link: https://jira.talendforge.org/browse/TMDM-13806
Known bugs before fixing:
1.  MDMTableForm should keep the wizard page refers it, but when debugging it, the "getPage()" return "null" value,
2. When click "Guess" button, it should iterate XSD schema, and search by defined xpaths, but there is no any code to update current XSD schema, only an empty object, so the result is empty, this causes empty table.(https://github.com/Talend/tcommon-studio-se/blob/dcd7bf801021cf352269544d80267f1072dd5b5c/main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MDMTableForm.java#L277)
3. When switching the different entity, it should update the corresponding entity concept, but from code, it always selects the first …
> TMDM-13806 Fixed "Guess" schema return an empty schema for Talend MDM connection

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ConfigModuleDialog.java
turning into a reference to the default 6.0.0-SNAPSHOT version
> bugfix(TUP-24563):Specifying a custom MVN URI in a Bean still ends up

- main/plugins/org.talend.core/src/main/java/org/talend/core/CoreService.java
Fix TUP-24579 MacOS : unable to access remote project after applying TPS-3363
https://jira.talendforge.org/browse/TUP-24579
> kjwang/Fix TUP-24579 MacOS : unable to access remote project after

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/StudioEncryption.java
kjwang/Fix TUP-22966 Remove hard-coded key in class org.talend.utils.security.AESEncryption and routines.system.PasswordEncryptUtil (Fix failed junit)
https://jira.talendforge.org/browse/TUP-22966
> kjwang/Fix TUP-22966 Remove hard-coded key in class org.talend.utils.security.AESEncryption and routines.system.PasswordEncryptUtil (Fix failed junit)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ConvertJobsUtil.java
Change the label so MapReduce is shown as deprecated
**BREAKING CHANGE**
If this PR contains a breaking change, please describe the impact and migration
path for existing applications.
If not please remove this section.
**Other information**:
> feat(TBD-9858): Set MapReduce as deprecated

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/ClasspathsJarGenerator.java
hive-exec jar is loaded before commons-lang3 but hive-exec is a fatjar that contains an old version of commons-lang3
hence a lot of job are failing because this breaks all the tFileOutput components
https://jira.talendforge.org/browse/TBD-9863
> fix(TBD-9863): jar conflict on CDH 6.x

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/prefs/LibrariesManagerUtils.java
The reason of this bug https://jira.talendforge.org/browse/TESB-28050
is that when we are adding external library with custom Maven URI to cConfig component, this library needs to be installed.
But method getNotInstalledModules returns not one, but two libraries with same names and different Maven URIs:
first
mavenUri - mvn:org.talend.libraries/s2jdbc-gen-2.10.48//jar"
mavenUriFromConfiguration - mvn:org.talend.libraries/s2jdbc-gen-2.10.48//jar"
and second
mavenUri - mvn:org.talend.libraries/s2jdbc-gen-2.10.48/6.0.0-SNAPSHOT/jar"
mavenUriFromConfiguration - null
That's why we need to upload both of those libraries, and we are getting behaviour described in bug.
To avoid this, we can upload only library (represented by ModuleNeeded class in application) with correct mavenUri, which is …
> TESB-28050 External jar in Cconfig would not be uploaded for the first time when add the jar in dependencies

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/ComponentsLocalNexusInstallFactory.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/nexus/component/ComponentSyncManager.java
TUP-25935 Studio logon remote project can not reach user custom library will throw error log like
ComponentSyncManager.getSnapshotRepositoryHandler.
https://jira.talendforge.org/browse/TUP-25935
> TUP-25935 Studio logon remote project can not reach user custom library

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenStandardJobOSGiPom.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/SortableDependency.java
- test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/utils/SortableDependencyTest.java
* fix(TUP-26165)jar referenced in bat or sh classpath missing in build
ZIP (#3105)
* fix(TUP-26165)jar referenced in bat or sh classpath missing in build
ZIP
file folder lib
https://jira.talendforge.org/browse/TUP-26165
* fix(TUP-26165)jar referenced in bat or sh classpath missing in build
ZIP
file folder lib
https://jira.talendforge.org/browse/TUP-26165
* fix(TUP-26165)jar referenced in bat or sh classpath missing in build
ZIP
file folder lib
https://jira.talendforge.org/browse/TUP-26165
* fix(TUP-26165)jar referenced in bat or sh classpath missing in build
ZIP
file folder lib
https://jira.talendforge.org/browse/TUP-26165
* fix(TUP-26165)jar referenced in bat or sh classpath missing in build
ZIP
file folder lib
https://jira.talendforge.org/browse/TUP-26165
* fix(TUP-26165):fix jar with …
> fix(TUP-26165):fix jar with classifier missing issue (#3152)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
- main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/setting/repository/tester/AbstractRepositoryNodeRepositorySettingTester.java
The reason of this bug is that Routes are inside Route Designs folder, so we also need to display Route Designs in settings.
> TESB-28895 Route node is missing in project setting

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/TalendQuoteUtils.java
- main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/TalendTextUtils.java
https://jira.talendforge.org/browse/TDI-44093
Syntax error when use query for tCosmosDBSQLAPIInput. Logic remove and add quotes by default.
Currently strings with quoted values process as expected.
New method check is it necessary quote string
> fix(TDI-44093): Add method that checks if string wrapped by quotes

- main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
- pom.xml
talend.studio.parent.pom as a root studio bom for SE/EE product
> chore(TUP-27463):Backport TUP-26304 to 7.3:Re-use

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ITDQRepositoryService.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/SwitchContextGroupNameImpl.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseWizard.java
* Fix TDQ-18565  Cannot save Hive metadata object with context variables
- if the analysis didnot use the current db, can pass
- if any analysis use this db, popup let the user select
* FIx TDQ-18565
* Fix TDQ-18565 backport to 73
Co-authored-by: root <root@LT-D9QV733>
> Fix/yyin/tdq 18565 context check 73 (#3462)

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/files/FileDirCleaner.java
We have a number of cases with FileNotFoundException's on the jobserver cache standalone / in RE where these logs would help to understand what happened when.
> TPSVC-15154 - allow debug logs for deletions to see which files are purged

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
Dynamic Columns handling in Studio:
https://jira.talendforge.org/browse/TCOMP-1651
**Related PRs:**
- https://github.com/Talend/studio-full-master/pull/423
- https://github.com/Talend/tdi-studio-ee/pull/1362
- https://github.com/Talend/tdi-studio-se/pull/4861
- https://github.com/Talend/tcommon-studio-se/pull/3620
- https://github.com/Talend/tcommon-studio-ee/pull/1506
> feat(TCOMP-1651): bump component-runtime to 1.1.24

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/views/ModulesViewComposite.java
Fix: TUP-28372 Modules Tab is not updated when switching branches. (Fix a problem when switching branch may cause wrong save operation )
https://jira.talendforge.org/browse/TUP-28372
> Fix: TUP-28372 Modules Tab is not updated when switching branches. (Fix

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/views/ModulesViewComposite.java
Fix: TUP-28372 Modules Tab is not updated when switching branches. (Fix a problem when switching branch may cause wrong save operation )
https://jira.talendforge.org/browse/TUP-28372
> Fix: TUP-28372 Modules Tab is not updated when switching branches

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TCOMP-1770
https://jira.talendforge.org/browse/TDI-44874
**Related PR**
- https://github.com/Talend/studio-full-master/pull/439
- https://github.com/Talend/tcommon-studio-ee/pull/1522
- https://github.com/Talend/tcommon-studio-se/pull/3637
- https://github.com/Talend/tdi-studio-se/pull/5201
> fix(TCOMP-1770): bump component-runtime to 1.1.25

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/UpdateService.java
Fix TUP-28050 Multi-User: Avoid possible actions that are not supported on shared studio (Fix a NPE issue)
https://jira.talendforge.org/browse/TUP-28050
> Fix a NPE issue

- main/plugins/org.talend.commons.runtime/talend.properties
talend.version value is wrong in talend.properties in org.talend.commons.runtime_7.4.1.xxxxx.jar
> TESB-31287:

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/files/FileDirCleaner.java
This PR is related to https://jira.talendforge.org/browse/TPSVC-15823
Remote Engine automatic purge doesn't work.
We experimented with different changes and @JuergenKindler s tests indicate that the solution implemented here solves the issue.
> TPSVC-15823 jobserver purge issues for maintenance/7.3

- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/MavenLibraryResolverProvider.java
This change is aligned with ﻿https://maven.apache.org/pom.html.
Artifacts with and without classifier share the same general pom.
> fix(TUP-29694):Studio fails to download jar with classifier in mvn uri

- main/plugins/org.talend.core/src/main/java/org/talend/core/model/migration/AbstractJobMigrationTask.java
Fix TUP-29744 The parameter value of jobType is wrong for new created testcase. (Remove unuseful migration task)
https://jira.talendforge.org/browse/TUP-29744
> Fix TUP-29744 The parameter value of jobType is wrong for new created testcase. (Remove unuseful migration task)

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TDI=45530
*Related PR*
- https://github.com/Talend/studio-full-master/pull/618
- https://github.com/Talend/tcommon-studio-se/pull/4036
- https://github.com/Talend/tcommon-studio-ee/pull/1742
- https://github.com/Talend/tdi-studio-se/pull/5803
> feat(TDI-45530): bump component-runtime to 1.29.1 for bouncycastle CVE

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/JavaResourcesHelper.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenStandardJobOSGiPom.java
After applying the latest patch, trunjob component fails with "java.io.IOException: Cannot run program "java.exe": error=2, No such file or directory"
> TESB-32452

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/cmd/AddRepositoryContextGroupCommand.java
TUP-27137 Testcase>Context: when use "select context variable" to select context from repository, the context from job will disappear.
https://jira.talendforge.org/browse/TUP-27137
> TUP-27137 Testcase>Context: when use "select context variable" to select

- main/plugins/org.talend.designer.maven.repo.tcksdk/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TDI-48418
This includes the following fixes:
- fix(TCOMP-2182): pass version to tck guess schema
***Related PR***
**master**
- https://github.com/Talend/studio-se-master/pull/679
- https://github.com/Talend/tcommon-studio-se/pull/5592
- https://github.com/Talend/tdi-studio-se/pull/7987
**maintenance/8.0**
- https://github.com/Talend/studio-se-master/pull/681
- https://github.com/Talend/tcommon-studio-se/pull/5593
- https://github.com/Talend/tdi-studio-se/pull/7988
> feat(TDI-48418): Bump component-runtime to 1.48

- main/plugins/org.talend.designer.maven.repo.tcksdk/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TDI-49951
*Related PR*
- https://github.com/Talend/studio-se-master/pull/819
- https://github.com/Talend/tcommon-studio-se/pull/6250
- https://github.com/Talend/studio-se-master/pull/820 (maintenance/8.0)
- https://github.com/Talend/tcommon-studio-se/pull/6251 (maintenance/8.0)
included tdi-studio-se features:
[x] feat(TCOMP-2443): allow component-server extensions for Studio
- https://github.com/Talend/tdi-studio-se/pull/8892
- https://github.com/Talend/tdi-studio-se/pull/8891 (maintenance/8.0)
> feat(TDI-49951): bump component-runtime to 1.58

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ldap/LDAPCATruster.java
- test/plugins/org.talend.core.repository.test/src/org/talend/core/repository/model/ldap/LDAPCATrusterTest.java
https://jira.talendforge.org/browse/TUP-41020
> fix(TUP-41020): LDAP Metadata : Check Authentication fails when Encryption method = LDAPS(SSL) even with correct credentials.
