- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialogWithProgress.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/librarydata/LibraryDataJsonProvider.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/librarydata/LibraryDataService.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/PluginOptionalMissingJarsExtraUpdatesFactory.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/PluginRequiredMissingJarsExtraUpdatesFactory.java
- test/plugins/org.talend.librariesmanager.ui.test/src/org/talend/librariesmanager/utils/RemoteModulesHelperTest.java
kjwang/Fix TUP-22686 jars show download link but can't download when run storm job
https://jira.talendforge.org/browse/TUP-22686
> kjwang/Fix TUP-22686 jars show download link but can't download when run

- main/plugins/org.talend.repository.view/src/org/talend/repository/viewer/action/RepoDoubleClickAction.java
https://jira.talendforge.org/browse/TUP-22202
> fix(TUP-22202): Studio will be closed after clicking "Setup routine dependencies" in Git Project

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/proposal/JavaSimpleDateFormatProposalProvider.java
> fix(TBD-8573): new date formats suggestions

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/TalendProcessArgumentConstant.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
show as a Tag
https://jira.talendforge.org/browse/TUP-22681
> fix(TUP-22681)Job in CI Builder gets generated and deployed, but doesn't

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
https://jira.talendforge.org/browse/TUP-22735
Conflicts:
main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
> fix(TUP-22735) fix wrong project migrations

- main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/setting/preference/M2eUserSettingForTalendLoginTask.java
> fix(TUP-22772):maven.repository=global doesn't work if set global maven repository to another place

- main/plugins/org.talend.core/META-INF/MANIFEST.MF
occurs while View documentation
https://jira.talendforge.org/browse/TUP-22827
> fix(TUP-22827)Error:java.lang.LinkageError: loader constraint violation

- main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/swt/celleditor/ComboxCellEditorImproved.java
16.04
https://jira.talendforge.org/browse/TUP-22783
> fix(TUP-22783)TELTPOSTGRESQL MAP Join Operator not working in Ubuntu

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponentsFactory.java
https://jira.talendforge.org/browse/TUP-22713
> fix(TUP-22713): Possible thread lock during git update operation

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/XsdMetadataUtils.java
> bugfix(TUP-22222):tXMLMap generates wrong XML when imported schema from

- pom.xml
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/process/ElementParameterParserTest.java
Fix TUP-21510 Update PasswordEncryptUtil (Update crypto-utils version)
https://jira.talendforge.org/browse/TUP-21510
> Fix TUP-21510 Update PasswordEncryptUtil (Update crypto-utils version)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/ITestContainerProviderService.java
- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
compilation error "row1 cannot be resolved to a variable"
> bugfix(TUP-22426):[6.5.1]Test Case generation on tRunJob gives

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/NetworkUtil.java
change from https://www.talend.com to https://talend-update.talend.com
> change from https://www.talend.com to https://talend-update.talend.com

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbstractNode.java
https://jira.talendforge.org/browse/TUP-22906
> fix(TUP-22906): Job working in 6.3.1 fails to generate in 7.1.1 : Failed to generate code. 

- main/plugins/org.talend.librariesmanager/resources/java/routines/system/PasswordEncryptUtil.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/AESEncryption.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/process/ElementParameterParserTest.java
- test/plugins/org.talend.utils.test/src/org/talend/utils/security/AESEncryptionTest.java
TUP-23004 Fail to decrypte password
https://jira.talendforge.org/browse/TUP-23004
> TUP-23004 Fail to decrypte password

- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/PasswordEncryptUtilTest.java
TUP-23004 Fail to decrypte password (Fix a junit)
https://jira.talendforge.org/browse/TUP-23004
> TUP-23004 Fail to decrypte password (Fix a junit)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponentsFactory.java
fix(TUP-22713): Possible thread lock during git update operation 
https://jira.talendforge.org/browse/TUP-22713
> fix(TUP-22713): Possible thread lock during git update operation (#2392)

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TUP-23098
> item(TUP-23098): Upgrade tacokit to release version of 1.1.9

- main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/swt/tableviewer/TableViewerCreatorNotModifiable.java
- main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/swt/tableviewer/tableeditor/TableEditorManager.java
bugfix(TUP-21969):Mixing Schema in tMap for several input data
> bugfix(TUP-21969):Mixing Schema in tMap for several input data (#2413)

- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/DynamicDistributionAetherUtils.java
https://jira.talendforge.org/browse/TUP-23036
> fix(TUP-23036): Can't run spark job when I select CDH513ker as distribution

- main/plugins/org.talend.utils/pom_server.xml
kjwang/Fix TUP-21205 Remove CryptoHelper (Fix a compile problem)
https://jira.talendforge.org/browse/TUP-21205
> kjwang/Fix TUP-21205 Remove CryptoHelper (Fix a compile problem)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/view/RepositoryLabelProvider.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/images/CoreImageProvider.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/string/DigestUtil.java
- test/plugins/org.talend.utils.test/src/org/talend/utils/string/DigestUtilTest.java
TUP-21489 Remove use of MD5 class in the Studio
https://jira.talendforge.org/browse/TUP-21489
> TUP-21489 Remove use of MD5 class in the Studio

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
for jira: https://jira.talendforge.org/browse/TDI-42356
- update jtds jar the one build by us.
> fix(TDI-42356):change jtds jar to talend patched which include talend own class

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/system/EclipseCommandLine.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
https://jira.talendforge.org/browse/TUP-22840
> fix(TUP-22840): add -clean when license changed

- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataUtils.java
> fix(TDQ-16842): fix sometimes for the import jdbc connection, can not

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/PasswordEncryptUtil.java
- main/plugins/org.talend.librariesmanager/resources/java/routines/system/PasswordEncryptUtil.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/process/ElementParameterParserTest.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/PasswordEncryptUtilTest.java
TUP-23201 Need change of encryption for jobs
https://jira.talendforge.org/browse/TUP-23201
> TUP-23201 Need change of encryption for jobs

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
(#2438)
backport to 7.1 for https://jira.talendforge.org/browse/TDI-42356
> fix(TDI-42356):change jtds jar to talend patched which include talend  own class

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
the attached job in ref project
https://jira.talendforge.org/browse/TUP-21838
> fix(TUP-21838)Mvn package miss the context value in bat file when use

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/DatabaseDriversCache.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ModuleNeeded.java
- main/plugins/org.talend.repository.view.example/components/tExampleComponent/tExampleComponent_java.xml
https://jira.talendforge.org/browse/TUP-23168
> fix(TUP-23168)Install external library issues

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
build/publish Job
https://jira.talendforge.org/browse/TUP-22833
> feat(TUP-22833)Remove the addition of context parameters during the

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/Nexus3ScriptSearchHandler.java
kjwang/Fix TUP-22469 Nexus3.15: studio can't detect patch for 701/711 release (Add socket time for script handler)
> Kjwang/fix tup 22469 nexus3.15 2

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/component/ComponentP2ExtraFeature.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/model/P2ExtraFeature.java
> fix(TUP-22261):Patch (update site format) with multiple plugins is not installed correctly

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TUP-23349
> fix(TUP-23349): Studio throw lot error logs about "A null service reference is not allowed."

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/Nexus3ScriptSearchHandler.java
Fix TUP-22469 Nexus3.15: studio can't detect patch for 701/711 release (Add socket time for script handler)
> Fix TUP-22469 Nexus3.15: studio can't detect patch for 701/711

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/Nexus3ScriptSearchHandler.java
* kjwang/Fix TUP-22469 Nexus3.15: studio can't detect patch for 701/711
release (Add socket time for script handler)
> Kjwang/fix tup 22469 nexus3.15 2 (#2466)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataTable.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolHelper.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/dialog/MetadataDialog.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/MetadataToolHelperTest.java
> bugfix(TUP-23228):The order of schema changed when ticked "used column"

- main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/swt/tableviewer/TableViewerCreatorNotModifiable.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/dialog/MetadataDialog.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/editor/MetadataEmfTableEditorView.java
https://jira.talendforge.org/browse/TUP-22359
> fix(TUP-22359)Broken Data Schema UI

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
Fix TUP-23170 New branch with name "/" will lead job with reference joblet build failure
https://jira.talendforge.org/browse/TUP-23170
> Fix TUP-23170 New branch with name "/" will lead job with reference

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
Fix TUP-23170 New branch with name "/" will lead job with reference joblet build failure
https://jira.talendforge.org/browse/TUP-23170
> Fix TUP-23170 New branch with name "/" will lead job with reference joblet build failure

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/routines/RoutineLibraryMananger.java
> bugfix(TUP-23364):Studio can't run jobs when path has spaces 

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/view/RepositoryLabelProvider.java
- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
- main/plugins/org.talend.repository.view/src/org/talend/repository/viewer/label/RepositoryViewLabelProvider.java
https://jira.talendforge.org/browse/TUP-23282
> fix(TUP-23282): Display of Tacokit Metadata is not homogeneous with other metadata

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/cmd/ContextBuiltinToRepositoryCommand.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/editor/command/ContextRemoveParameterCommand.java
have multi groups failed
Conflicts:
main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/editor/command/ContextRemoveParameterCommand.java
> bugfix(TUP-23301):Add and replace variable to repository context which

- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/utils/workbench/gef/SimpleHtmlFigure.java
https://jira.talendforge.org/browse/TUP-22936
> fix(TUP-22936)No description for component red/yellow signs

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/service/ITaCoKitService.java
https://jira.talendforge.org/browse/TUP-23432
> fix(TUP-23432): NPE when single selecting build job

- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
does not exist throw when I rename a folder.
> bugfix(TUP-21693):Error log like Resource '/AA/poms/jobs/process/test1'

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/NexusConstants.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/AbstractArtifactRepositoryHandler.java
version policy: SNAPSHOT does not allow version
https://jira.talendforge.org/browse/TUP-22490
> fix(TUP-22490)Unable to transfer JAR file to Nexsus 3 due to repository

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
https://jira.talendforge.org/browse/TUP-23036
>  fix(TUP-23036): Can't run spark job when I select CDH513ker as distribution

- test/plugins/org.talend.librariesmanager.ui.test/src/org/talend/librariesmanager/utils/RemoteModulesHelperTest.java
kjwang/Fix TUP-23488 Retrieve jar list to download is slow (Fix junit error)
https://jira.talendforge.org/browse/TUP-23488
> kjwang/Fix TUP-23488 Retrieve jar list to download is slow (Fix junit

- main/plugins/org.talend.librariesmanager/plugin.xml
- pom.xml
classpath
https://jira.talendforge.org/browse/TUP-23482
> fix(TUP-23482)should avoid multi version slf4j-log4j jars in the job

- pom.xml
https://jira.talendforge.org/browse/TUP-23482
> fix(TUP-23482)should avoid multi version slf4j-log4j jars in the job classpath

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
https://jira.talendforge.org/browse/TUP-23519
> fix(TUP-23519): spark job can't run success when I select EMR58 as distribution

- main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/ProcessStreamTrashReaderUtil.java
> bugfix(TUP-23230):Guess Schema error - SLF4J: Defaulting to no-operation

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/librarydata/LibraryDataService.java
kjwang/Fix TUP-23488 Retrieve jar list to download is slow (Fix license name is empty problem)
https://jira.talendforge.org/browse/TUP-23488
> kjwang/Fix TUP-23488 Retrieve jar list to download is slow (Fix license

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/PluginOptionalMissingJarsExtraUpdatesFactory.java
set "-Dtalend.disable.internet=true "
> bugfix(TUP-22773):"Optional third-party libraries" should be hidden if

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/metadata/hive/creator/HiveConnectionCreator.java
TUP-23225 Hiveserver2 host is not correctly discovered in the studio
https://jira.talendforge.org/browse/TUP-23225
> TUP-23225 Hiveserver2 host is not correctly discovered in the studio

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/classloader/ClassLoaderFactory.java
https://jira.talendforge.org/browse/TUP-20577
> fix(TUP-20577): [BUG]Cannot support 2 kinds of versions

- main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
https://jira.talendforge.org/browse/TDI-42600
> chore(TDI-42600): upgrade Components version to 0.28.0-SNAPSHOT

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/metadata/xml/utils/TreeUtil.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/i18n/Messages.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/i18n/messages.properties
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/XmlFileStep1Form.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/action/ImportTreeFromXMLAction.java
indexOutOfBoundsException
https://jira.talendforge.org/browse/TUP-22200
> fix(TUP-22200)Import XML tree from xsd file throw

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
- main/plugins/org.talend.repository.items.importexport/plugin.xml
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/exports/SyncChildrenSourceCodeProvider.java
> fix(TUP-22986):Build jobs doesn't creates the java source file for the child jobs

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
fix(TUP-23701) DB connection settings screen does not display all field
> fix(TUP-23701) DB connection settings screen does not display all field

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolHelper.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/LastGenerationInfo.java
> Zshen/chore/tdq 17069 back port 7.1

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/nexus/component/ComponentsDeploymentManager.java
fix(TUP-23536)Component cannot share to Nexus3.15 from local
> fix(TUP-23536)Component cannot share to Nexus3.15 from local

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/nexus/component/ComponentsDeploymentManager.java
fix(TUP-23536)Component cannot share to Nexus3.15 from local (#2601)
> fix(TUP-23536)Component cannot share to Nexus3.15 from local (#2601)

- main/plugins/org.talend.libraries.jdbc.exasol/pom.xml
https://jira.talendforge.org/browse/TDI-42572
> Fix(TDI-42572):upgrade EXAUtil version (#2602)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/LastGenerationInfo.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/ItemCacheManager.java
TUP-23950 Error in calling spark job from trunjob job inside standard job
https://jira.talendforge.org/browse/TUP-23950
> TUP-23950 Error in calling spark job from trunjob job inside standard

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
7.1.1
https://jira.talendforge.org/browse/TUP-23789
> fix(TUP-23789)Pom files are not generated sometimes for the jobs in

- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/drawing/background/BackgroundRefresher.java
https://jira.talendforge.org/browse/TUP-23984
> fix(TUP-23984): JSON metadata wizard for output mode throws class cast exception on Linux and Mac

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/LastGenerationInfo.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/ItemCacheManager.java
TUP-23950 Error in calling spark job from trunjob job inside standard job
https://jira.talendforge.org/browse/TUP-23950
> TUP-23950 Error in calling spark job from trunjob job inside standard job

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/IRepositoryService.java
Resources
https://jira.talendforge.org/browse/TUP-22943
> fix(TUP-22943)checkbox with empty item name display on window Save

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/advanced/composite/FilteredCheckboxTree.java
https://jira.talendforge.org/browse/TUP-23854
> fix(TUP-23854)Can't create EDI until I open error log view

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/IAdditionalInfo.java
https://jira.talendforge.org/browse/TUP-20943
> fix(TUP-20943): Code generates with an error when Pattern check fails if contain back slash

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/AbstractForm.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MdmConceptWizardPage3.java
https://jira.talendforge.org/browse/TMDM-13648
> TMDM-13648 fix the event loop exception when refreshing wizard page during edit receive type entity.

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/preference/I18nPreferencePage.java
https://jira.talendforge.org/browse/TUP-23998
> fix(TUP-23998)Studio language not working as expected

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/excel/ExcelReader.java
https://jira.talendforge.org/browse/TDI-41662
Fix signature for parse method
> fix(TDI-41662): change ExcelReader.parse signature  

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
https://jira.talendforge.org/browse/TUP-23933
> fix(TUP-23933)Metadata connection for Redshift SSO considers username &password as separate field

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/i18n/messages.properties
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/logintask/SyncLibrariesLoginTask.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
https://jira.talendforge.org/browse/TUP-20372
> fix(TUP-20372) Use Project Settings is not checked as default for job

- main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/ProcessStreamTrashReaderUtil.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/AbstractForm.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/json/AbstractTreePopulator.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/json/JsonTreePopulator.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/json/SchemaPopulationUtil.java
https://jira.talendforge.org/browse/TUP-23914
> fix(TUP-23914): JSON with accented characters is not being recognized when creating a new JSON file in Metadata.

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/HandlerUtil.java
https://jira.talendforge.org/browse/TUP-22556
> fix(TUP-22556)TDI License: It takes 190s to finish Import Progress

- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/linking/TreeToTablesLinker.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/extraction/XmlToXPathLinker.java
https://jira.talendforge.org/browse/TUP-24159
> fix(TUP-24159)XML metadata wizard showing inconsistent view on V711 comparing with V6 Studio

- main/plugins/org.talend.repository.mdm/resources/UpdateReport.xsd
Update schema to add new field of `PrimaryKeyInfo`
> TMDM-12997 Add more fields in the Jounal from the MDM Web UI

- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/action/RetrieveMDMSchemaAction.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/CreateConceptWizard.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MDMOutputSchemaForm.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MDMXSDFileForm.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MdmConceptWizardPage2.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MdmConceptWizardPage3.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MdmReceiveForm.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/dnd/MDMOutputDragAndDropHandler.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/dnd/MDMSchema2TreeLinker.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/buttons/AbstractTreeNodeButton.java
https://jira.talendforge.org/browse/TMDM-13805
> TMDM-13805 Can read entity and navigator to previous/next page.

- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/action/RetrieveMDMSchemaAction.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/CreateConceptWizard.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MDMOutputSchemaForm.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MDMXSDFileForm.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MdmConceptWizardPage2.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MdmConceptWizardPage3.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/MdmReceiveForm.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/dnd/MDMOutputDragAndDropHandler.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/dnd/MDMSchema2TreeLinker.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/buttons/AbstractTreeNodeButton.java
https://jira.talendforge.org/browse/TMDM-13805
> TMDM-13805 Can read entity and navigator to previous/next page. 

- main/plugins/org.talend.libraries.jdbc.exasol/pom.xml
https://jira.talendforge.org/browse/TDI-42725
> fix(TDI-42725): change groupID EXAUtil

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/logintask/SyncLibrariesLoginTask.java
https://jira.talendforge.org/browse/TUP-20372
> fix(TUP-20372)[git] Use Project Settings is not checked as default for job

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
building the job in tJDBCInput Component
> bugfix(TUP-24218):Talend 6.5.1 Unable to see XMLMapping file after

- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataUtils.java
https://jira.talendforge.org/browse/TUP-24232
> fix(TUP-24232)JDBC metadata connection for Redshift when exported as context, unable to retrieve schema

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TDI-42034
Driver was updated from 1.2.20.1043 to 1.2.32.1056
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:
> fix(TDI-42034): update Redshift jar to 1.2.32.1056

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/component/ComponentP2ExtraFeature.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/model/AbstractExtraFeature.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/model/ExtraFeature.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/model/P2ExtraFeature.java
https://jira.talendforge.org/browse/TUP-24226
> fix(TUP-24226): Studio doesn't load latest jar for TCOMPv0 update site patch.

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/json/JsonTreePopulator.java
https://jira.talendforge.org/browse/TUP-24248
> fix(TUP-24248)when edit the metadata, the display content is different as when created

- main/plugins/org.talend.librariesmanager/pom.xml
- pom.xml
Fix :TUP-24363 Create excel metadata get error:Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
https://jira.talendforge.org/browse/TUP-24363
> kjwang/Fix TUP-24363 Create excel metadata get error

- main/plugins/org.talend.librariesmanager/resources/java/routines/Numeric.java
Numeric sequence is now thread safe
> fix : TDI-42776

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/JobContext.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/IContext.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/ContextNebulaGridComposite.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/SelectRepositoryContextDialog.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java
https://jira.talendforge.org/browse/TUP-24411
> fix(TUP-24411)Error message: unable to update task config if the Context parameters have same values but different case

- main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/messages.properties
- main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/wizard/imports/ImportItemsWizardPage.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/manager/ChangeIdManager.java
https://jira.talendforge.org/browse/TUP-23905
> fix(TUP-23905): Job disappearing after merging git branches

- main/plugins/org.talend.core/src/main/java/org/talend/core/CoreService.java
kjwang/Fix TUP-24579 MacOS : unable to access remote project after applying TPS-3363
https://jira.talendforge.org/browse/TUP-24579
>  kjwang/Fix TUP-24579 MacOS : unable to access remote project after applying TPS-3363

- main/plugins/org.talend.core/src/main/java/org/talend/core/CoreService.java
kjwang/Fix TUP-24579 MacOS : unable to access remote project after applying TPS-3363
https://jira.talendforge.org/browse/TUP-24579
> kjwang/Fix TUP-24579 MacOS : unable to access remote project after

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/VersionUtils.java
- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
- test/plugins/org.talend.commons.runtime.test/src/org/talend/commons/utils/VersionUtilsTest.java
routines-7.1.1.jar instead of routines-7.2.1.jar
https://jira.talendforge.org/browse/TUP-24433
> fix(TUP-24433)Migrating Big Data Jobs from 7.1.1 to 7.2.1 is adding the

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TUP-23960
> fix(TUP-23960)Following TDI-42674, update dependency for Redshift database metadata

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IProcessor.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/ProcessorDependenciesManager.java
- main/plugins/org.talend.platform.logging/src/log4j2.xml
https://jira.talendforge.org/browse/TUP-24444
> feat(TUP-24444)Add choice between log4j and log4j2 in project settings

- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/SetNameForm.java
https://jira.talendforge.org/browse/TMDM-13924
TMDM-13924 Change the pattern string to adapt to jdk8 & jdk11; extract method to get next name and won't change selected entity name; replace the exception handler and exception catch pattern.
> TMDM-13924 Schema tree show empty when retrieve entity for mdm connection.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbstractNode.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/INode.java
This reverts commit 03958a67cbb24926a2123233c00f2a83903fbfdd.
> Revert "fix(TBD-9333): add new methods to get previous node (#2760)"

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/AbstractArtifactRepositoryHandler.java
'@' character in it
https://jira.talendforge.org/browse/TUP-24735
> fix(TUP-24735)Studio fails to sync jars with Artifactory if password has

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
https://jira.talendforge.org/browse/TDI-43035
Use only MAIN Connection Category and avoid returning Lookup.
> fix(TDI-43035): use only main connection category

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
- test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/model/ModulesNeededProviderTest.java
> fix(TUP-24613)routine section does not allow user to edit required

- main/plugins/org.talend.utils/.classpath
https://jira.talendforge.org/browse/TUP-21518
Add resource into eclipse project
> feat(TUP-21518) Remove CryptoHelper

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
* fix(TDI-43035): use only main connection category
* fix(TDI-43035): use better condition to catch the issue
Backport to maintenance/7.2
https://jira.talendforge.org/browse/TDI-43035
> fix(TDI-43035): use only main connection category (#2754)

- main/plugins/org.talend.librariesmanager/resources/java/routines/Mathematical.java
https://jira.talendforge.org/browse/TDI-43022
> fix(TDI-43022): change LN method in Routines

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
https://jira.talendforge.org/browse/TDI-43035
For cumulative patch 20191101.
> fix(TDI-43035): use only main connection category (#2754) (#2778)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
Reverts Talend/tcommon-studio-se#2780
> Revert "fix(TDI-43035): use only main connection category (#2754) (#2778)"

- main/plugins/org.talend.librariesmanager/resources/java/routines/Mathematical.java
Backport to 7.1
Link to Jira main task: https://jira.talendforge.org/browse/TDI-43022
> fix(TDI-43022): change LN method in Routines (#2751)

- main/plugins/org.talend.designer.maven.aether/.classpath
- main/plugins/org.talend.designer.maven.aether/META-INF/MANIFEST.MF
- main/plugins/org.talend.designer.maven.aether/build.properties
- main/plugins/org.talend.designer.maven.aether/pom.xml
- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/MavenLibraryResolverProvider.java
bugfix(TUP-25048) Add https transporter
https://jira.talendforge.org/browse/TUP-25048
> bugfix(TUP-25048) Add https transporter

- main/plugins/org.talend.core.runtime/mappings/mapping_XSD.xml
- main/plugins/org.talend.datatools.xml/src/main/java/org/talend/datatools/xml/utils/ATreeNode.java
- main/plugins/org.talend.datatools.xml/src/main/java/org/talend/datatools/xml/utils/XSDPopulationUtil2.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/xml/TreePopulator.java
- test/plugins/org.talend.datatools.xml.test/resources/simple_node_test.xsd
- test/plugins/org.talend.datatools.xml.test/src/main/java/org/talend/datatools/xml/utils/XSDPopulationUtil2Test.java
https://jira.talendforge.org/browse/TUP-24954
> fix(TUP-24954): Error "XML format is incorrect", when customer try to define a 'File XML metadata' using a XSD file

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/metadata/xml/utils/TreeUtil.java
https://jira.talendforge.org/browse/TUP-25050
> fix(TUP-25050)Cannot Read data from xsd file while creating xml metadata

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/i18n/internal/messages.properties
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/TalendProxySelector.java
- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/RepositorySystemFactory.java
- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/DynamicDistributionAetherUtils.java
- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/MavenLibraryResolverProvider.java
- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/TalendAetherProxySelector.java
- main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/MavenUIService.java
* fix(TUP-24749): [7.2.1] issue to download component jar via https
proxy
https://jira.talendforge.org/browse/TUP-24749
https://jira.talendforge.org/browse/TUP-24783
https://jira.talendforge.org/browse/TUP-24606
Conflicts:
main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/RepositorySystemFactory.java
main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/MavenLibraryResolverProvider.java
> Cmeng/bugfix/tup 24749 proxy issue (#2808)

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
- test/plugins/org.talend.core.test/src/org/talend/designer/runprocess/ProcessorUtilitiesTest.java
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
> Jding/tup 24732 studio code tab doesn't show error (#2805)

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
https://jira.talendforge.org/browse/TUP-25006
> feat(TUP-25006): Redshift SSO support with Ping Federate

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
Reverts Talend/tcommon-studio-se#2820
> Revert "feat(TUP-25006): Redshift SSO support with Ping Federate"

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/PasswordMigrationUtil.java
https://jira.talendforge.org/browse/TUP-25101
> TUP-25101 The key store password missing of component "tSetKeyStore" when import into studio

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/encoding/CharsetToolkit.java
TUP-25128 Studio miss item properties when change item version(for routine/json items)
https://jira.talendforge.org/browse/TUP-25128
> TUP-25128 Studio miss item properties when change item version(for routine/json items)

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/TalendProxySelector.java
- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/TalendAetherProxySelector.java
https://jira.talendforge.org/browse/TUP-24749
> fix(TUP-24749): [7.2.1] issue to download component jar via https proxy

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/json/SchemaPopulationUtil.java
- test/plugins/org.talend.repository.metadata.test/resources/test/file/relationship.json
- test/plugins/org.talend.repository.metadata.test/src/org/talend/repository/ui/wizards/metadata/connection/files/json/SchemaPopulationUtilTest.java
https://jira.talendforge.org/browse/TUP-25052
> fix(TUP-25052): File json miss source schema when after do export to context.

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
PR linked: https://github.com/Talend/studio-se-master/pull/218
> fix(TDI-43180): couchbase TOS upgrade

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
https://jira.talendforge.org/browse/TUP-24578
bugfix(TUP-24578) Exclude all of dynamic distribution maven urls from mavenUrlIndex
> bugfix(TUP-24578) Exclude all of dynamic distribution maven urls from mavenUrlIndex

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/ISAPConstant.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/command/RepositoryChangeMetadataForSAPBapi.java
https://jira.talendforge.org/browse/TUP-24942
> fix(TUP-24942): need to do studio metadata mapping to tsapbapi components for the new closedlist when D&D metadata to job

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
- test/plugins/org.talend.core.test/src/org/talend/designer/runprocess/ProcessorUtilitiesTest.java
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* fix(TUP-24732)[7.2.1] Studio Code tab doesn't generate code/show errors
in Job
https://jira.talendforge.org/browse/TUP-24732
> Jding/tup 24732 check loop dependency issues (#2844)

- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
- test/plugins/org.talend.repository.localprovider.test/src/org/talend/repository/localprovider/model/LocalRepositoryFactoryTest.java
https://jira.talendforge.org/browse/TUP-25186
bugfix(TUP-25186) Skip migration tasks already executed
> bugfix(TUP-25186) Skip migration tasks already executed

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
(#2820)" (#2827)" (#2828)
This reverts commit 57a0d745f3a8961a8da4c00e81d166d6501c300e.
Conflicts:
main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
> Revert "Revert "feat(TUP-25006): Redshift SSO support with Ping Federate

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
https://jira.talendforge.org/browse/TUP-25344
> fix(TUP-25344): can't logon project after change workspace if set log4j2

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
- test/plugins/org.talend.core.test/src/org/talend/designer/runprocess/ProcessorUtilitiesTest.java
* Jding/tup 24732 studio code tab doesn't show error (#2805) (#2812)
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* Jding/tup 24732 check loop dependency issues (#2844) (#2860)
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job
https://jira.talendforge.org/browse/TUP-24732
* fix(TUP-24732)Studio Code tab doesn't generate code/show errors in Job …
> Jding/test patch tps 3474 (#2861)

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://jira.talendforge.org/browse/TDI-43300
> fix(TDI-43300): fix tacokit component jar clash with locales

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/PasswordEncryptUtil.java
TUP-22966 Remove hard-coded key in class org.talend.utils.security.AESEncryption and routines.system.PasswordEncryptUtil (Fix failed junit)
> Fix failed junit

- main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/messages.properties
- main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/wizard/imports/ImportItemsWizardPage.java
and still going on
Revert the same name import issue fix
> fix(TUP-23082)[Performance] import specific job takes more than 44 mins

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/StudioEncryption.java
https://jira.talendforge.org/browse/TUP-25441
> bugfix(TUP-25441) Decrypt M3 format data with correct key

- main/plugins/org.talend.librariesmanager/resources/java/routines/system/RunStat.java
add a new signature for the method "log"
> fix(TBD-9669): add method signature for class RunStat

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ILibraryManagerService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/routines/RoutineLibraryMananger.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/maven/MavenArtifact.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/ArtifacoryRepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/VersionUtil.java
- test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/nexus/utils/VersionUtilTest.java
* Fix TUP-24953 Nexus 3 gets populated by crypto-utils.jar
https://jira.talendforge.org/browse/TUP-24953
> Kjwang/fix tup 24953 nexus 3 gets populated by crypto utils.jar (#2883)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/LastGenerationInfo.java
https://jira.talendforge.org/browse/TUP-25237
> bugfix(TUP-25237) Add method clear modules per job

- main/plugins/org.talend.designer.maven/resources/templates/general/pom_codes_template.xml
Fix TUP-25511 Targeted job use database run bat file fail after package out
https://jira.talendforge.org/browse/TUP-25511
> Fix TUP-25511 Targeted job use database run bat file fail after package out

- main/plugins/org.talend.utils/META-INF/MANIFEST.MF
https://jira.talendforge.org/browse/TUP-25362
> bugfix(TUP-25362) Export org.talend.utils.migration package

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
https://jira.talendforge.org/browse/TUP-23557
> bugfix(TUP-23557) Referenced job can not run because of classnotfound

- main/plugins/org.talend.designer.maven/resources/templates/general/pom_codes_template.xml
Fix TUP-25511 Targeted job use database run bat file fail after package out
https://jira.talendforge.org/browse/TUP-25511
> Fix TUP-25511 Targeted job use database run bat file fail after package

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/JobInfo.java
https://jira.talendforge.org/browse/TUP-25570
> fix(TUP-25570)Add a way to auto-propagate always the context group name

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/ConnParameterKeys.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/HadoopClassLoaderFactory2.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/HadoopConfJarBean.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/hadoop/IHadoopClusterService.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ExtendedNodeConnectionContextUtils.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/hive/HiveClassLoaderFactory.java
https://jira.talendforge.org/browse/TUP-25226
> feat(TUP-25226): Make the hadoop conf jar path a contextualizable parameter in the Hadoop conf wizard

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
https://jira.talendforge.org/browse/TUP-24554
Fix TUP-24554 Potential NullPointerException
> Fix TUP-24554 Potential NullPointerException

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java
parameters cann't drag to job
https://jira.talendforge.org/browse/TUP-18610
> fix(TUP-18610):When drag hdfs to spark job,hadoop cluster some context

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
https://jira.talendforge.org/browse/TUP-21574
> bugfix(TUP-21574) Disable test connection button for qubole

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
pkg:maven/org.codehaus.plexus:plexus-utils:1.5.15 requires version
upgrade (Fix can't build job with sub job)
https://jira.talendforge.org/browse/TUP-22583
> Fix TUP-22582 [CVE:high] Backend : (#2587)

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialog.java
https://jira.talendforge.org/browse/TUP-4621
> fix(TUP-4621): GUI issue: Spark assembly in spark job

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/files/excel/ExcelFileStep1Form.java
Fix TUP-25095 Excel metadata can not preview
TUP-25095 Excel metadata can't preview data at step 2/4 when use context
mode
> Fix TUP-25095 Excel metadata can not preview

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/ModuleMavenURIUtils.java
- test/plugins/org.talend.librariesmanager.ui.test/src/org/talend/librariesmanager/utils/ModuleMavenURIUtilsTest.java
contains too much digits
https://jira.talendforge.org/browse/TUP-25405
> fix(TUP-25405)[Module view] Install module does not work if version

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/ContextTreeTable.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/JavaVersion.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/StudioKeysFileCheck.java
- test/plugins/org.talend.utils.test/src/org/talend/utils/JavaVersionTest.java
https://jira.talendforge.org/projects/TUP/issues/TUP-25580
> bugfix(TUP-25580) Show clear message when there is problem to encrypt/decrypt password in studio

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/TalendLibsServerManager.java
customer artifact repository
https://jira.talendforge.org/browse/TUP-24057
> feat(TUP-24057)There is no error message when studio can't connect to

- main/features/org.talend.fragment.jars.common.feature/feature.xml
Fix TUP-24523 Online Help in studio - refactor help features (Fix the compile error)
https://jira.talendforge.org/browse/TUP-24523
> Fix TUP-24523 Online Help in studio - refactor help features (Fix the compile error)

- main/features/org.talend.fragment.jars.common.feature/feature.xml
Reverts Talend/tcommon-studio-se#2961
> Revert "Fix TUP-24523 Online Help in studio - refactor help features (Fix the compile error)"

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/DynamicDistibutionLicenseUtil.java
https://jira.talendforge.org/browse/TUP-25221
> fix(TUP-25221): Can't load license of dynamic distribution if the path contains special character

- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/dialogs/ProgressDialog.java
https://jira.talendforge.org/browse/TUP-23333
> fix(TUP-23333): ubuntu: Documentation Save as ... function get NPE

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/startup/ShareMavenArtifactsOnStartup.java
library to local nexus
https://jira.talendforge.org/browse/TUP-25075
> fix(TUP-25075)Studio download jars but donot dynamically distribute some

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/dialog/OpenXSDFileDialog.java
confirmation dialog box
https://jira.talendforge.org/browse/TUP-6493
> fix(TUP-6493)File path can't change when inputting a file path for the

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
> fix(TUP-24475):studio metadata ui is wrong for exasol database, is different ui with component part

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/io/FilesUtils.java
kjwang/Fix TUP-23742 Remove FilesUtils.getFileMD5
https://jira.talendforge.org/browse/TUP-23742
> kjwang/Fix TUP-23742 Remove FilesUtils.getFileMD5

- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/manager/ExtractManager.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/utils/MetadataConnectionUtils.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableFilterForm.java
> bugfix(TUP-25697)：system tables do not show up when trying to retrieve

- main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java
from 7.1.1 to 7.2.1
https://jira.talendforge.org/browse/TUP-25632
> fix(TUP-25632)Custom scripts pom for job is not automatically migrated

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/ContextTreeTable.java
https://jira.talendforge.org/browse/TUP-25355
> bugfix(TUP-25355) Context display not showing as expected on Ubuntu18

- main/plugins/org.talend.core.runtime/mappings/mapping_BigQuery.xml
> feat(TDI-42591): bigquery dynamic column support

- main/plugins/org.talend.utils/pom.xml
- main/plugins/org.talend.utils/pom_minimal.xml
- main/plugins/org.talend.utils/pom_server.xml
https://jira.talendforge.org/browse/TUP-25827
> bugfix(TUP-25827) Upgrade commons-codec, commons-io and ant dependencies

- main/features/org.talend.help.feature/feature.xml
Fix TUP-25786 Enable online help
https://jira.talendforge.org/browse/TUP-25786
> feat(TUP-25786): Enable online help

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/xml/XSDValidator.java
error log list if Studio store path contain space
> bugfix(TUP-25764):Win:Cannot load component "tImpalaOutput" error in

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/VersionUtils.java
the studio 7.2.1
https://jira.talendforge.org/browse/TUP-25152
> fix(TUP-25152): component does not display in palette, after deployed to

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListCellEditor.java
This PR is to make possibility to enter custom MVN URI when adding external dependency using cConfig (like we have for e.g. tLibraryLoad). This allows us to publish 
external dependencies with correct GroupID and ArtefactID. More details about the bug in description here https://jira.talendforge.org/browse/TESB-26993
> TESB-26993 Fixing cConfig doesn't use a standard Maven file system structure when publishing dependencies

- main/plugins/org.talend.common.ui.runtime/META-INF/MANIFEST.MF
- main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/utils/ZipFileUtils.java
- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/utils/io/archive/Unzipper.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/commons/utils/io/FilesUtils.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/io/FilesUtils.java
- test/plugins/org.talend.utils.test/src/org/talend/utils/files/FileUtilsTest.java
https://jira.talendforge.org/browse/TUP-24536
> bugfix(TUP-24536) Studio is vulnerable to "Zip Slip" style attacks

- main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
https://jira.talendforge.org/browse/TDI-43517
Add NetSuite 2019 runtime to tos resources.
> feat(TDI-43517): add 2019 runtime module

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/INOSQLService.java
> bugfix(TUP-26031):Cannot connect successfully for mongDB which is

- main/plugins/org.talend.designer.maven/resources/templates/maven_user_settings.xml
https://jira.talendforge.org/browse/TUP-26064
> bugfix(TUP-26064) Change to https for maven central

- main/plugins/org.talend.libraries.jdbc.mysql/plugin.xml
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
still call an old jar mariadb-java-client.jar.
> bugfix(TUP-26074):Retrieve schema for jdbc maria db in context mode

- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/RepositorySystemFactory.java
- main/plugins/org.talend.librariesmanager/src/main/java/messages.properties
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
https://jira.talendforge.org/browse/TUP-26081
> fix(TUP-26081): Share libraries pb

- main/plugins/org.talend.core.runtime/mappings/mapping_H2.xml
- main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml
- main/plugins/org.talend.core.runtime/mappings/mapping_Vertica.xml
https://jira.talendforge.org/browse/TDI-43466
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:
> Fix(TDI-43446):fix mysql,h2 and vertica

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
Reverts Talend/tcommon-studio-se#3069
> Revert "fix(TUP-26110):Jar missing when install user component."

- i18n/plugins/org.talend.rcp.nl/plugin_de.properties
- i18n/plugins/org.talend.rcp.nl/plugin_en.properties
https://jira.talendforge.org/browse/TUP-26123
> bugfix(TUP-26123) Update copyright date

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/JavaVersion.java
- test/plugins/org.talend.utils.test/src/org/talend/utils/JavaVersionTest.java
https://jira.talendforge.org/browse/TUP-26136
> bugfix(TUP-26136): Fix java version parsing

- main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml
for https://jira.talendforge.org/browse/TDI-42965
fixed the issue when change defalt talend type for BINARY/BIT, caused some tujs failed.
> fix(TDI-42965): Change back Mysql Mapping default talend type for BINARY/BIT

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolHelper.java
> bugfix(TUP-26059):tELTPostgresqlMap lost its "DB Type" column for which

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
- main/plugins/org.talend.repository.items.importexport/plugin.xml
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/exports/SyncChildrenTestReportsProvider.java
https://jira.talendforge.org/browse/TUP-25965
> bugfix(TUP-25965) backport TUP-25965

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/io/FilesUtils.java
- test/plugins/org.talend.utils.test/src/org/talend/utils/files/FileUtilsTest.java
https://jira.talendforge.org/browse/TDQ-18070
> bugfix(TDQ-18070): Improve file path validation

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/InstallNewFeatureJob.java
Fix TUP-25920 components will not pop up install help plugin again once installation meet a failure
https://jira.talendforge.org/browse/TUP-25920
> Fix TUP-25920 components will not pop up install help plugin again once

- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/linking/TableToTreeLinker.java
> fix(TUP-25889)Display issue for the line between Linker source and

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/relationship/RelationshipItemBuilderTest.java
https://jira.talendforge.org/browse/TUP-26138
> bugfix(TUP-26138) Regenerate relationship.index

- main/plugins/org.talend.commons.runtime/META-INF/MANIFEST.MF
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/CommonsPlugin.java
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/TalendProxySelector.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-26189
> fix(TUP-26189): [7.2.1] snowflake metadata connection with proxy failure

- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/util/MavenLibraryResolverProvider.java
https://jira.talendforge.org/browse/TUP-26212
> fix(TUP-26212): Share more than one car component to nexus3.19.1 will fail to generate the right index file

- main/plugins/org.talend.rcp/src/main/java/messages.properties
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/JavaVersion.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/StudioKeysFileCheck.java
https://jira.talendforge.org/browse/TUP-26350
> fix(TUP-26350): Add java version check for tos

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/IRepositoryArtifactHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/AbstractArtifactRepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus2RepositoryHandler.java
TUP-26308 Nexus 2 gets populated by different crypto-utils jar versions
https://jira.talendforge.org/browse/TUP-26308
> TUP-26308 Nexus 2 gets populated by different crypto-utils jar versions

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenStandardJobOSGiPom.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/SortableDependency.java
- test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/utils/SortableDependencyTest.java
file folder lib
https://jira.talendforge.org/browse/TUP-26165
> fix(TUP-26165)jar referenced in bat or sh classpath missing in build ZIP

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
- main/plugins/org.talend.repository.items.importexport/plugin.xml
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/exports/SyncChildrenTestReportsProvider.java
* bugfix(TUP-25965) Synchronize test reports
* bugfix(TUP-25965) Ignore test failures and zip test reports
* bugfix(TUP-25965) Ignore test failures and zip test reports
* bugfix(TUP-25965) Ignore test failures and zip test reports
* bugfix(TUP-25965) Ignore test failures and zip test reports
* bugfix(TUP-25965) Ignore test failures
* bugfix(TUP-25965) Ignore test failures
* bugfix(TUP-25965) Skip tests when running job
* fix(TUP-25965): Call service to check is build job or not
> bugfix(TUP-25965) Include subjob's test reports (#3055)

- main/plugins/org.talend.utils/src/main/java/org/talend/utils/io/FilesUtils.java
- test/plugins/org.talend.utils.test/src/org/talend/utils/files/FileUtilsTest.java
* fix(TDQ-18070): Improve file path validation
* fix(TDQ-18070): Improve file path validation
> backport(TUP-26230) Unzip file path validation error

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
Fix TUP-26346 Files from custom component folders are uploaded to nexus multiple times
https://jira.talendforge.org/browse/TUP-26346
> Fix TUP-26346 Files from custom component folders are uploaded to nexus multiple times

- main/plugins/org.talend.designer.maven.aether/src/main/java/org/talend/designer/maven/aether/RepositorySystemFactory.java
- main/plugins/org.talend.librariesmanager/src/main/java/messages.properties
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
* fix(TUP-26081): Share libraries pb
https://jira.talendforge.org/browse/TUP-26081
* fix(TUP-26081): Share libraries pb
https://jira.talendforge.org/browse/TUP-26081
> fix(TUP-26081): Share libraries pb (#3063)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolHelper.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/MetadataToolHelperTest.java
> fix(TUP-26377)FileDelimited metadata doesnt retrieve the column names

- main/plugins/org.talend.core/src/main/java/org/talend/core/model/genhtml/IJobSettingConstants.java
> bugfix(TUP-26388):Amazon Redshift Driver class not working with Implicit

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://jira.talendforge.org/browse/TDI-43837
Fix bug with couchbase-locales in TOS found by QA
>  fix(TDI-43837): remove couchbase-locales from dep

- main/plugins/org.talend.core/src/main/java/org/talend/core/model/genhtml/IJobSettingConstants.java
Reverts Talend/tcommon-studio-se#3141
> Revert "bugfix(TUP-26388):Amazon Redshift Driver class not working with Implicit"

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IMDMWebServiceHook.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/mdm/S60MdmConnectionHelper.java
- test/plugins/org.talend.metadata.managment.test/src/org/talend/metadata/managment/mdm/S60MdmConnectionHelperTest.java
https://jira.talendforge.org/browse/TMDM-14505.
Add studio token to created mdm metadata connection.
> TMDM-14505 MDM connection in metadata randomly failed with error 'Failed to connect to MDM, please change MDM settings'

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/projectsetting/IProjectSettingPreferenceConstants.java
reference job even after we delete it from the main job
> bugfix(TUP-26475):Job is referring to the joblet present in the

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ConvertJobsUtil.java
https://jira.talendforge.org/browse/TUP-26033
> fix(TUP-26033)deprecated show first in the list

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialog.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/PluginOptionalMissingJarsExtraUpdatesFactory.java
* fix(TUP-26596)Proxy of libraries not working when studio have no
internet access
* fix(TUP-26596)Proxy of libraries not working when studio have no
internet access
* fix(TUP-26596)Proxy of libraries not working when studio have no
internet access
* fix(TUP-26596)Proxy of libraries not working when studio have no
internet access
> fix(TUP-26596)Proxy of libraries not working when studio have no (#3165)

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/DBConnectionContextUtils.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
context value like
context.cdh513judy_impala1_hiveAdditionalJDBCParameters, which should be
the detailed value.
> fix when "revert context", the "Additional JDBD Settings" is still

- main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonViewer.java
- test/plugins/org.talend.core.runtime.test/META-INF/MANIFEST.MF
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/RepositoryNodeTest.java
* fix(TUP-26539): Fix wrong tree node implmentation
* fix(TUP-26539): add test case
* fix(TUP-26539): Remove reference to itself
* fix(TUP-26539): Return root node
* fix(TUP-26539): Update test case
* fix(TUP-26539): update test case
* fix(TUP-26539): Unassociate unnecessary listeners
* fix(TUP-26539): Revert changes of RepositoryNode
* fix(TUP-26539): Add override annotation
> backport732(TUP-26539): Unassociate data from associateListeners (#3169)

- main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonViewer.java
- test/plugins/org.talend.core.runtime.test/META-INF/MANIFEST.MF
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/RepositoryNodeTest.java
* fix(TUP-26539): Fix wrong tree node implmentation
* fix(TUP-26539): add test case
* fix(TUP-26539): Remove reference to itself
* fix(TUP-26539): Return root node
* fix(TUP-26539): Update test case
* fix(TUP-26539): update test case
* fix(TUP-26539): Unassociate unnecessary listeners
* fix(TUP-26539): Revert changes of RepositoryNode
* fix(TUP-26539): Add override annotation
> backport722(TUP-26539): Unassociate data from associateListeners (#3169)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IMultipleComponentManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericService.java
> fix(TUP-26388)Amazon Redshift Driver class not working with Implicit

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
https://jira.talendforge.org/browse/TUP-26735
> fix(TUP-26735):Cannot see the contents of the Recycle bin

- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/mdm/S60MdmConnectionHelper.java
https://jira.talendforge.org/browse/TMDM-14565
Switch context class loader for web service created.
> TMDM-14565 Check mdm connection cannot work both in mdm and di perspective at same time

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
Reverts Talend/tcommon-studio-se#3109
> Revert "feat(TUP-26284)Upgrade AWS SDK for driver in metadata"

- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataUtils.java
https://jira.talendforge.org/browse/TUP-26793
> fix(TUP-26793)JDBC Redshift in context mode still asked for jars

- main/plugins/org.talend.core/src/main/java/org/talend/core/model/components/conversions/ResetComponentNameConversion.java
> bugfix(TUP-26439):Need to fix other rename components Migration task

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/recyclebin/RecycleBinManager.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
https://jira.talendforge.org/browse/TUP-26735
> fix(TUP-26735)Cannot see the contents of the Recycle bin

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/IMetadataTable.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataTable.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java
> bugfix(TUP-26758):[7.2.1] Wrong column order when using Schema from

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://jira.talendforge.org/browse/TDI-43717
> feat(TDI-43717):integrate cosmosdb into studio

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/manager/ChangeIdManager.java
> bugfix(TUP-24445):Testcase will list under the wrong job after do import

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/manager/ChangeIdManager.java
Reverts Talend/tcommon-studio-se#3201
> Revert "bugfix(TUP-24445):Testcase will list under the wrong job after do import"

- main/plugins/org.talend.core.runtime/META-INF/MANIFEST.MF
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/TalendMavenResolver.java
https://jira.talendforge.org/browse/TUP-26752
> bugfix(TUP-26752) Required Libraries pop-up appears after each restart of studio

- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/contentProvider/DynamicContentProvider.java
> bugfix(TUP-26485):TOS can not show the right pane for cloud product

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/MavenProjectUtils.java
> bugfix(TUP-26868):xmlMapping file are not correctly add to class path in

- main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/wizard/imports/providers/ImportItemsViewerSorter.java
> bugfix(TUP-26875):when import a job with many versions,the order of the

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtil.java
upload to nexus with two versions
> fix(TUP-26810)if one jar used by two different components, it will

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/dialog/PastSelectorDialog.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/RepositoryNodeSortUtil.java
- test/plugins/org.talend.core.repository.test/src/org/talend/repository/utils/RepositoryNodeSortUtilTest.java
* bugfix(TUP-26870):Incorrect sorting order
> Hwang/tup 26870 (#3214)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericDBService.java
connections
https://jira.talendforge.org/browse/TUP-26639
> fix(TUP-26639):Talend Cloud studio Issues - Group context and

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/preference/collector/TalendDataCollectorPreferencePage.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/TokenCollectorFactory.java
https://jira.talendforge.org/browse/TUP-26833
> feat(TUP-26833):Test studio data collector

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericDBService.java
connections
https://jira.talendforge.org/browse/TUP-26639
> fix(TUP-26639):Talend Cloud studio Issues - Group context and (#3233)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericDBService.java
Names is not reflected on the Connection for Snowflake
https://jira.talendforge.org/browse/TUP-26639
> fix(TUP-26639):Talend Cloud studio Issue -Changes to Context Parameter

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/database/Sybase16SADatabaseMetaData.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/EDatabaseTypeName.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataFromDataBase.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataUtils.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/utils/MetadataConnectionUtils.java
https://jira.talendforge.org/browse/TUP-26896
> fix(TUP-26896)Error create a Sybase connection in metadata and cannot retrieve tables

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/database/Sybase16SADatabaseMetaData.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/EDatabaseTypeName.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataFromDataBase.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataUtils.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/utils/MetadataConnectionUtils.java
retrieve tables (#3231)
* fix(TUP-26896)Error create a Sybase connection in metadata and cannot
retrieve tables
https://jira.talendforge.org/browse/TUP-26896
* fix(TUP-26896)retrieve schema on sybase 16 anywhere metadate get empry
value
https://jira.talendforge.org/browse/TUP-26896
* fix(TUP-26896)Error create a Sybase connection in metadata and cannot
retrieve tables
* fix(TUP-26896)Error create a Sybase connection in metadata and cannot
retrieve tables
https://jira.talendforge.org/browse/TUP-26896
* fix(TUP-26896)Error create a Sybase connection in metadata and cannot
retrieve tables
* fix(TUP-26896)Error create a Sybase connection in metadata and cannot
retrieve tables
* fix(TUP-26896)Error create a Sybase connection in metadata and cannot
retrieve tables
* fix(TUP-26896)Error create a …
> fix(TUP-26896)Error create a Sybase connection in metadata and cannot

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/XmiResourceManager.java
https://jira.talendforge.org/browse/TUP-26990
> fix(TUP-26990):Possible conflict in talend project

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/XmiResourceManager.java
* fix(TUP-26990):Possible conflict in talend project
https://jira.talendforge.org/browse/TUP-26990
* fix(TUP-26990):Possible conflict in talend project
https://jira.talendforge.org/browse/TUP-26990
> fix(TUP-26990):Possible conflict in talend project (#3264)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IMDMWebServiceHook.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/mdm/S60MdmConnectionHelper.java
- test/plugins/org.talend.metadata.managment.test/src/org/talend/metadata/managment/mdm/S60MdmConnectionHelperTest.java
https://jira.talendforge.org/browse/TPS-3943
> TPS-3943 [7.2.1]Talend MDM Connection Errors(TMDM-14505, TMDM-14565)

- main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/exception/ExceptionMessageDialog.java
found dialog when project is in MERGING state
https://jira.talendforge.org/browse/TUP-27003
> fix(TUP-27003):Should disable the Commit button of Uncommitted files

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/ContextParameterUtilsTest.java
> fix(TUP-27072)_Unexpected behaviour occurred when context name is in

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/manager/ChangeIdManager.java
Reverts Talend/tcommon-studio-se#3226
> Revert "bugfix(TUP-24445):Testcase will list under the wrong job after do imp…"

- main/plugins/org.talend.metadata.managment.ui/src/main/java/messages.properties
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/metadata/ShowAddedContextdialog.java
https://jira.talendforge.org/browse/TUP-27046
Bad phrasing on the connection contextualization wizard
> TUP-27046 Replace the "Added context" wizard message.

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://jira.talendforge.org/browse/TDI-44203
> fix(TDI-44203):upgrade tacokit version to 1.10.0-SNAPSHOT for studio

- main/plugins/pom_server.xml
Backport of https://github.com/Talend/tcommon-studio-se/commit/a2d1786ea8dc73c0c9dc20df80af4d7dad864d59
For proper maven build when using pom_server.xml
> Pin plugin versions

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TUP-27186
> bugfix(TUP-27186)Create JDBC-sybase-anywhere connection need upload driver two times

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/XmiResourceManager.java
https://jira.talendforge.org/browse/TUP-26990
> fix(TUP-26990):Possible conflict in talend project (#3295)

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/DefaultTokenCollector.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/contentProvider/DynamicContentProvider.java
- main/plugins/org.talend.registration/src/main/java/org/talend/registration/register/RegisterManagement.java
* bugfix(TUP-26994):Usage data collector : change the way Studio Unique Id
is calculated
> Hwang/tup 26994 (#3282)

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://github.com/Talend/studio-full-master/pull/250
> fix(TDI-43717):backport cosmos to 7.3

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java
kjwang/Fix TUP-26288 Fix salesforce context var update issue
https://jira.talendforge.org/browse/TUP-26288
> kjwang/Fix TUP-26288 Fix salesforce context var update issue

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/AbstractRepositoryContextUpdateService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/GenericDbContextUpdateService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryContextUpdateService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java
Fix TUP-26639 Talend Cloud studio Issue -Changes to Context Parameter Names is not reflected on the Connection for Snowflake
https://jira.talendforge.org/browse/TUP-26639
> Fix TUP-26639 Talend Cloud studio Issue -Changes to Context Parameter

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/JobContextManager.java
Fix joblet build in param internal id changeproblem
https://jira.talendforge.org/browse/TUP-26288
> Fix TUP-26288_Enhance context joblet build in param internal id change

- main/plugins/pom_server.xml
https://jira.talendforge.org/browse/TUP-27224
> bugfix(TUP-27224): Upgrade crypto-utils to 1.15.0

- main/plugins/org.talend.libraries.apache.xml/lib/.gitignore
- main/plugins/org.talend.libraries.apache.xml/pom.xml
https://jira.talendforge.org/browse/TDI-44169
https://jira.talendforge.org/browse/TDI-44105
To fix CVE issues xmlrpc libs was updated from 3.0 to 3.1.3.
Updated libs was uploaded to Nexus talend-update
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:
> fix(TDI-44169): remove xmlrpc_3.0 from studio

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/service/ITaCoKitService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IRunProcessService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/wizard/models/ImportNodesBuilder.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/StudioEncryption.java
https://jira.talendforge.org/browse/TUP-26569
> feat(TUP-26569): merge known conflicts automatically

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
- test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPomTest.java
https://jira.talendforge.org/browse/TUP-27053
> fix(TUP-27053): backport

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/TrackerUtil.java
https://jira.talendforge.org/browse/TDI-44216
> feat(TDI-44216):Redshift partner tracker

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/ArtifacoryRepositoryHandler.java
https://jira.talendforge.org/browse/TUP-27078
> bugfix(TUP-27078): Studio upload the libraries (jar files) into the Artifactory Server at each start

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/utils/PomUtilTest.java
https://jira.talendforge.org/browse/TUP-25835
> fix(TUP-25835): Dynamic distribution cannot download libraries from proxy Nexus

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/IInstalledPatchService.java
- main/plugins/org.talend.core/src/main/java/org/talend/core/services/ICoreTisService.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ApplicationWorkbenchWindowAdvisor.java
* bugfix(TUP-27210):Version isn't correct in Help->"About Talend Studio"
after installing monthly patch
> Hwang/tup 27210 (#3316)

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
…in (#3328)
Metadata
https://jira.talendforge.org/browse/TUP-27259
> feat(TUP-27259)Change default driver to Microsoft official for MSSql

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
https://jira.talendforge.org/browse/TUP-26687
> fix(TUP-26687): make Nexus3RepositoryHandler.dosearch thread safe

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/context/ContextModeWizard.java
find the link to context after export and imported in.
https://jira.talendforge.org/browse/TUP-27190
> fix(TUP-27190):[Bug] DB connection use context in ref project can not

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/link/AbstractItemContextLinkService.java
a new context group for context and propagate to job.
https://jira.talendforge.org/browse/TUP-27522
> fix(TUP-27522):[Bug] context var id in link file will be null after add

- main/plugins/org.talend.core.runtime/plugin.xml
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/ContextUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/link/AbstractItemContextLinkService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/link/ConnectionItemContextLinkService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/link/ContextLinkService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/link/IItemContextLinkService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/link/ProcessItemContextLinkService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManagerHelper.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/context/ContextModeWizard.java
TUP-26699 Enhance context propagation over reference project - Resolve link conflict with Git
https://jira.talendforge.org/browse/TUP-26699
> TUP-26699 Enhance context propagation over reference project - Resolve link conflict with Git

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/i18n/messages.properties
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
https://jira.talendforge.org/browse/TUP-27119
> fix(TUP-27119)need give a warning if the schema is empty when switch context mode

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://jira.talendforge.org/browse/TDI-44402
> fix(TDI-44402):update tacokit version studio

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
- test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPomTest.java
https://jira.talendforge.org/browse/TUP-27053
> fix(TUP-27053): backport (#3361)

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/utils/PomUtilTest.java
fix(TUP-25835): Dynamic distribution cannot download libraries from proxy Nexus
https://jira.talendforge.org/browse/TUP-25835
> fix(TUP-25835): Dynamic distribution cannot download libraries

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/utils/PomUtilTest.java
fix(TUP-25835): Dynamic distribution cannot download libraries from proxy Nexus
https://jira.talendforge.org/browse/TUP-25835
> fix(TUP-25835): Dynamic distribution cannot download libraries from

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/sqlbuilder/util/ConnectionParameters.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/sqlbuilder/util/TextUtil.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/TalendQuoteUtils.java
- test/plugins/org.talend.core.test/src/org/talend/core/sqlbuilder/util/TextUtilTest.java
https://jira.talendforge.org/browse/TUP-27607
> fix(TUP-27607)Metadata Database connection with special characters(double quote) in the password

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/runprocess/IRunProcessService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/wizard/models/ImportNodesBuilder.java
https://jira.talendforge.org/browse/TUP-26569
> feat(TUP-26569): merge known conflicts automatically (#3349)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
always Mysql after dragging and dropping from database Metadata
> fix(TUP-27588)tCreateTable data types mapping in the schema editor is

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/resource/UpdatesHelper.java
https://jira.talendforge.org/browse/TUP-27586
> fix(TUP-27586): skip checking installed patches

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/resource/UpdatesHelper.java
https://jira.talendforge.org/browse/TUP-27586
> fix(TUP-27586): fix test case failure

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/ITalendNexusPrefConstants.java
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/NetworkUtil.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/NexusServerUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/prefs/ITalendCorePrefConstants.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialog.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/PluginOptionalMissingJarsExtraUpdatesFactory.java
7.2 PR: https://jira.talendforge.org/browse/TUP-27416
> TUP-27416 Validate network, timeout value read from nexus timeout preference configuration .

- main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonViewer.java
- test/plugins/org.talend.core.runtime.test/META-INF/MANIFEST.MF
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/RepositoryNodeTest.java
* fix(TUP-26539): Fix wrong tree node implmentation
* fix(TUP-26539): add test case
* fix(TUP-26539): Remove reference to itself
* fix(TUP-26539): Return root node
* fix(TUP-26539): Update test case
* fix(TUP-26539): update test case
* fix(TUP-26539): Unassociate unnecessary listeners
* fix(TUP-26539): Revert changes of RepositoryNode
* fix(TUP-26539): Add override annotation
> fix(TUP-26539): Unassociate data from associateListeners (#3169) (#3177)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/handlers/JobAndNodesParametersRelationshipHandler.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/handlers/JobRoutinesItemRelationshipHandler.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
https://jira.talendforge.org/browse/TUP-27590
> fix(TUP-27590):Relationship.index might get really big

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/link/ItemContextLink.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
Fix: TUP-27544 Context update can not update to the first testcase if the job have more than one testcase.
https://jira.talendforge.org/browse/TUP-27544
> Fix: TUP-27544 Context update can not update to the first testcase if the job have more than one testcase.

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/resource/UpdatesHelper.java
https://jira.talendforge.org/browse/TUP-27586
> fix(TUP-27586): fix test case failure (#3443)

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/ITalendNexusPrefConstants.java
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/NetworkUtil.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/NexusServerUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/prefs/ITalendCorePrefConstants.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ExternalModulesInstallDialog.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/RemoteModulesHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/PluginOptionalMissingJarsExtraUpdatesFactory.java
7.4 PR: https://jira.talendforge.org/browse/TUP-27416
> TUP-27416 Validate network, timeout value read from nexus timeout preference configuration . 

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/recyclebin/RecycleBinManager.java
https://jira.talendforge.org/browse/TUP-27349
> TUP-27349 Avoid concurrent modification exception that will some times throw NPE when doing Pull And Merge in git project.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/ComponentUtilities.java
https://jira.talendforge.org/browse/TDI-44472
> fix(TDI-44472):Rename global variable

- test/plugins/org.talend.core.repository.test/src/org/talend/core/repository/handlers/JobAndNodesParametersRelationshipHandlerTest.java
https://jira.talendforge.org/browse/TUP-27590
> fix(TUP-27590)Relationship.index might get really big

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/ComponentUtilities.java
* fix(TDI-44472):Rename global variable
https://jira.talendforge.org/browse/TDI-44472
> fix(TDI-44472):Rename global variable (#3439)

- main/plugins/org.talend.utils/META-INF/MANIFEST.MF
- main/plugins/org.talend.utils/pom.xml
- main/plugins/org.talend.utils/pom_minimal.xml
- main/plugins/org.talend.utils/pom_server.xml
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/StudioKeysFileCheck.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/dates/DateUtils.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/files/AbstractDataCleaner.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/files/FileDirCleaner.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/json/JSONObject.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/network/FreePortFinder.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/network/ServerSocketFreePortOpener.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/properties/PropertiesLoader.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/properties/TypedProperties.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/BouncyCastleEncryption.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/StudioEncryption.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/StudioKeyName.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/security/StudioKeySource.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/sql/ConnectionUtils.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/thread/TimeoutOperationHandler.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/time/TimeTracer.java
https://jira.talendforge.org/browse/TUP-27949
> bugfix(TUP-27949) Replace dependency of log4j by slf4j

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/relationship/RelationshipItemBuilderTest.java
* fix(TUP-26138): Regenerate relationship index
> bugfix(TUP-26138) Regenerate relationship.index (#3088)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/handlers/JobAndNodesParametersRelationshipHandler.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/handlers/JobRoutinesItemRelationshipHandler.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
- test/plugins/org.talend.core.repository.test/src/org/talend/core/repository/handlers/JobAndNodesParametersRelationshipHandlerTest.java
* fix(TUP-27590):Relationship.index might get really big
https://jira.talendforge.org/browse/TUP-27590
* fix(TUP-27590):Relationship.index might get really big
https://jira.talendforge.org/browse/TUP-27590
* fix(TUP-27590)Relationship.index might get really big
https://jira.talendforge.org/browse/TUP-27590
relatedItems is empty should not add  as a record
* fix(TUP-27590):Relationship.index might get really big
https://jira.talendforge.org/browse/TUP-27590
* fix(TUP-27590)Relationship.index might get really big
https://jira.talendforge.org/browse/TUP-27590
> fix(TUP-27590):Relationship.index might get really big (#3424)

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
Conflicts:
main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
> fix miss dependency in assmble.xml with loop dependency

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/exports/SyncChildrenContextsResourcesProvider.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/exports/SyncChildrenSourceCodeProvider.java
(#3168)
PublishJob is not correct, missing item files.
> fix(TUP-26233):[7.0.1] Sometimes , the ZIP file created by a commandline

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/exports/SyncChildrenSourceCodeProvider.java
> fix(TUP-27888):[7.1.1] Jenkins build fails when compiling job from

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/utils/UpdateTools.java
https://jira.talendforge.org/browse/TUP-27814
> fix(TUP-27814): Skip file.exists()

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/librarydata/LibraryDataJsonProvider.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/librarydata/LibraryDataService.java
Fix:TUP-27879 Shared user can't write library index file
library_data.index
https://jira.talendforge.org/browse/TUP-27879
> Fix:TUP-27879 Shared user can't write library index file library_data.index

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
https://jira.talendforge.org/browse/TUP-26099
PR: master
> TUP-26099 Adjust UI layout, do not show horizontal bar anymore for scrolled composite.

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
https://jira.talendforge.org/browse/TUP-26687
> fix(TUP-26687): backport

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbsJobletReplaceNodeHandler.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbsReplaceNodeHandler.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/AbstractNode.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/IJobletReplaceNodeHandler.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/INode.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/IReplaceNodeHandler.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/JobletReplaceNodeHandler.java
https://jira.talendforge.org/browse/TUP-27953
> fix(TUP-27953): tSalesforceInput component displays in-job tSalesforceConnection incorrectly

- main/plugins/org.talend.designer.maven.ui/src/main/java/messages.properties
https://jira.talendforge.org/browse/TUP-25566
> feat(TUP-25566):All the recycle bin should not be build or executed

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/maven/MavenRepoSynchronizer.java
https://jira.talendforge.org/browse/TUP-28002
> fix(TUP-28002): Search release repository before uploading jars

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/recyclebin/RecycleBinManager.java
- main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/setting/project/initializer/MavenScriptsProjectSettingInitializer.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-27989
> fix(TUP-27989): Git related issues checked with support

- main/plugins/org.talend.core.runtime/mappings/mapping_Sybase.xml
- main/plugins/org.talend.core.runtime/mappings/mapping_validate.xsd
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/DbDefaultDatePattern.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/Dbms.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MappingFileLoader.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MappingTypeRetriever.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableForm.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/SelectorTableForm.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/MappingTypeRetrieverTest.java
* feat(TUP-27862)Add possibility to customize pattern for dates when
retrieve table
* feat(TUP-27862)Add possibility to customize pattern for dates when
retrieve table
* feat(TUP-27862)Add possibility to customize pattern for dates when
retrieve table
* feat(TUP-27862)Add possibility to customize pattern for dates when
retrieve table
* feat(TUP-27862)Add possibility to customize pattern for dates when
retrieve table
* add junit
* add junits
* add junits
> Jzhang/feat/73/tup 27862 (#3480)

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/resource/UpdatesHelper.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
https://jira.talendforge.org/browse/TUP-26633
PR: 7.4
> TUP-26633 Remove local component(tcompv0) patch installation function.

- main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml
Backport of https://github.com/Talend/tcommon-studio-se/pull/3495 into "master" branch
> Enable precision check for Timestamp datatype

- main/plugins/org.talend.core.runtime/mappings/mapping_Mysql.xml
Fix for https://jira.talendforge.org/browse/TDI-44457 issue.
> Enable precision check for Timestamp datatype.

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
new connection in remote project
https://jira.talendforge.org/browse/TUP-28078
> fix(TUP-28078)metadata folder generated under .../poms/jobs when create

- test/plugins/org.talend.commons.runtime.test/src/org/talend/commons/utils/VersionUtilsTest.java
https://jira.talendforge.org/browse/TUP-27506
> fix(TUP-27374): fix test case

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ILibraryManagerService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ModuleNeeded.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/routines/RoutineLibraryMananger.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/IRepositoryArtifactHandler.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/maven/MavenArtifact.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/startup/ShareMavenArtifactsOnStartup.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/DownloadModuleRunnable.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/AbstractArtifactRepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/ArtifacoryRepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus2RepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtil.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/VersionUtil.java
- test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/nexus/utils/VersionUtilTest.java
https://jira.talendforge.org/browse/TUP-24953
https://jira.talendforge.org/browse/TUP-25929
https://jira.talendforge.org/browse/TUP-23519
https://jira.talendforge.org/browse/TUP-27078 
https://jira.talendforge.org/browse/TUP-26346
> bugfix(TUP-26346) backport

- test/plugins/org.talend.commons.runtime.test/src/org/talend/commons/utils/VersionUtilsTest.java
https://jira.talendforge.org/browse/TUP-27506
> fix(TUP-27506): Update minor version

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
"Exclude deleted items" and delete to recycle bin
> fix(TUP-28180):[bug]Only latest version deleted from root pom when check

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
https://jira.talendforge.org/browse/TUP-25566
> fix(TUP-25566):All the recycle bin should not be build or executed

- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/proposal/CommonTextCellEditorWithProposal.java
- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/proposal/ExtendedTextCellEditorWithProposal.java
* TUP-25103
* remove service
* TUP-25103
> Hengzhao/backport73/tup 25103 (#3541)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
https://jira.talendforge.org/browse/TUP-27924
PR: master
> WorkItem(TUP-27924) m2 jars in patch will be synchronized right after patch installed, before logon phase.

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
https://jira.talendforge.org/browse/TUP-28078
> fix(TUP-28078)metadata folder generated under .../poms/jobs when create new connection in remote project

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/component/settings/ComponentsSettingsHelper.java
> fix(TUP-28134):TCK Components shown as hidden by default in the palette

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/BuildCacheManager.java
https://jira.talendforge.org/browse/TUP-28308
> fix(TUP-28308): build error and  joblet maven xml file has incorrect values and Couldn't parse data error message

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TPS-4101
> patch(TPS-4101): bump component-runtime to 1.1.15.2

- main/plugins/org.talend.core.ui/META-INF/MANIFEST.MF
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/TokenCollectorFactory.java
https://jira.talendforge.org/browse/TUP-26341
Conflicts:
main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/TokenCollectorFactory.java
> fix(TUP-26341): Talend Token Collector doesn't work with http/https proxy

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/logintask/SyncLibrariesLoginTask.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/login/AbstractLoginTask.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/login/ILoginTask.java
https://jira.talendforge.org/browse/TUP-27268
> fix(TUP-27268): Add isRequiredAlways for ILoginTask

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/logintask/SyncLibrariesLoginTask.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/login/AbstractLoginTask.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/login/ILoginTask.java
https://jira.talendforge.org/browse/TUP-27268
> fix(TUP-27268): Add isRequiredAlways for ILoginTask (#3593)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ILibrariesService.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/AbstractLibrariesService.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/CustomUriManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LibrariesService.java
Fix: TUP-28372 Modules Tab is not updated when switching branches.
https://jira.talendforge.org/browse/TUP-28372
> Fix: TUP-28372 Modules Tab is not updated when switching branches.

- main/plugins/org.talend.datatools.xml/src/main/java/org/talend/datatools/xml/utils/XPathPopulationUtil.java
https://jira.talendforge.org/browse/TUP-27927
Note I haven't tested this as I can't build the project.
> TUP-27927 - Use Pattern.quote instead of manually escaping regex values

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
* bump version of TCK components from [1.11.0-SNAPSHOT] to [1.12.0-SNAPSHOT]
> chore(TDI-44799): bump version of TCK components

- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/component/LocalComponentsInstallComponent.java
https://jira.talendforge.org/browse/TUP-26633
> bugfix(TUP-26633) Add back local component(tcompv0) patch installation function,and just keep TaCoKitCars patch install.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IUpdateService.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/maven/MavenRepoSynchronizer.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/UpdateService.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/utils/UpdateTools.java
https://jira.talendforge.org/browse/TUP-27924
> bugfix(TUP-27924) Do sync Component M2 Jars just after patch installed, and will not deploy to nexus at this moment.

- main/features/org.talend.utils.feature/feature.xml
- main/plugins/org.talend.libraries.apache.http/META-INF/MANIFEST.MF
https://jira.talendforge.org/browse/TUP-28546
> fix(TUP-28546): upgrade commons-codec plugin

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/logintask/SyncLibrariesLoginTask.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/login/AbstractLoginTask.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/login/ILoginTask.java
https://jira.talendforge.org/browse/TUP-27268
> fix(TUP-27268): Add isRequiredAlways for ILoginTask (#3593) (#3603)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TUP-28432
> feat(TUP-28432)Upgrade AWS SDK's version

- main/features/org.talend.utils.feature/feature.xml
https://jira.talendforge.org/browse/TUP-28574
> fix(TUP-28574): Add org.talend.studio.studio-utils bundle

- main/features/org.talend.utils.feature/feature.xml
- main/plugins/org.talend.libraries.apache.http/META-INF/MANIFEST.MF
https://jira.talendforge.org/browse/TUP-27438
> fix(TUP-27438): restore org.apache.commons.codec

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/recyclebin/RecycleBinManager.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/XmiResourceManager.java
- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-28316
Conflicts:
main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/recyclebin/RecycleBinManager.java
> fix(TUP-28316): Left git related issues checked with support

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/time/PerformanceLogManager.java
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/time/TimeMeasurePerformance.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/exportLogs/ExportLogsWizardPage.java
https://jira.talendforge.org/browse/TUP-28334
> feature(TUP-28334) Enhance logging of performance.

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
Dynamic Columns handling in Studio : https://jira.talendforge.org/browse/TCOMP-1651
Master backport
**Related PRs:**
- https://github.com/Talend/studio-full-master/pull/432
- https://github.com/Talend/tcommon-studio-ee/pull/1507
- https://github.com/Talend/tcommon-studio-se/pull/3621
- https://github.com/Talend/tdi-studio-ee/pull/1459
- https://github.com/Talend/tdi-studio-se/pull/5180
> feat(TCOMP-1651): backport to master

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/AbstractEMFRepositoryFactory.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/IRepositoryFactory.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/ContextUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/link/AbstractItemContextLinkService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/IProxyRepositoryFactory.java
- main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportCacheHelper.java
- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
* fix(TUP-28487): fix performance issue
> fix(TUP-28487): fix performance issue (#3598)

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TUP-28617
> fix(TUP-28617): add commons-codec

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
* bump version of TCK components [1.9.0] -> [1.13.0]
> chore(TDI-44671): bump tck components

- main/plugins/org.talend.librariesmanager/resources/java/routines/system/ResumeUtil.java
https://jira.talendforge.org/browse/TDI-44826
> fix(TDI-44826): Missing line in Resume log

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TCOMP-1770
https://jira.talendforge.org/browse/TDI-44874
**Related PR**
- https://github.com/Talend/tcommon-studio-ee/pull/1523
- https://github.com/Talend/tcommon-studio-se/pull/3638
- https://github.com/Talend/tdi-studio-se/pull/5202
> feat(TCOMP-1770): backport to master

- main/plugins/org.talend.designer.maven.tos/resources/surefire/pom.xml
https://jira.talendforge.org/browse/TUP-28633
> bugfix(TUP-28633) add junit dependencies

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/AbstractEMFRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-28682
> fix(TUP-28682): Connection info missing when create dataset for tck components

- main/plugins/org.talend.commons.runtime/META-INF/MANIFEST.MF
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/time/PerformanceStatisticUtil.java
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/time/TimeMeasurePerformance.java
- main/plugins/org.talend.core.ui/.classpath
- main/plugins/org.talend.core.ui/META-INF/MANIFEST.MF
- main/plugins/org.talend.core.ui/build.properties
- main/plugins/org.talend.core.ui/plugin.xml
- main/plugins/org.talend.core.ui/pom.xml
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/DefaultTokenCollector.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/PerformanceTokenCollector.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ApplicationWorkbenchAdvisor.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ApplicationWorkbenchWindowAdvisor.java
https://jira.talendforge.org/browse/TUP-28405
> feature(TUP-28405) Collect hardware info.Add functio to measure IO speed, startup time.

- main/plugins/org.talend.commons.runtime/META-INF/MANIFEST.MF
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/time/PerformanceStatisticUtil.java
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/time/TimeMeasurePerformance.java
- main/plugins/org.talend.core.ui/.classpath
- main/plugins/org.talend.core.ui/META-INF/MANIFEST.MF
- main/plugins/org.talend.core.ui/build.properties
- main/plugins/org.talend.core.ui/plugin.xml
- main/plugins/org.talend.core.ui/pom.xml
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/DefaultTokenCollector.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/PerformanceTokenCollector.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ApplicationWorkbenchAdvisor.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ApplicationWorkbenchWindowAdvisor.java
https://jira.talendforge.org/browse/TUP-28405
> feature(TUP-28405) Collect hardware info.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericService.java
https://jira.talendforge.org/browse/TUP-26413
> fix(TUP-26413): Be able to compare metadata connection conflicts

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericService.java
https://jira.talendforge.org/browse/TUP-26413
> fix(TUP-26413): Be able to compare metadata connection conflicts (#3657)

- main/plugins/org.talend.librariesmanager/resources/java/routines/system/JobStructureCatcherUtils.java
- main/plugins/org.talend.librariesmanager/resources/java/routines/system/ProcessIdAndThreadId.java
- main/plugins/org.talend.librariesmanager/resources/java/routines/system/RunStat.java
* fix(TDI-44807): Observability: initialize moment only when necessary
* fix(TDI-44806): Observability: Add customization for event frequency
> fix(TDI-44623): [OBSERVABILITY] : add PID and (Thread-ID OR UUID) information

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponentsFactory.java
https://jira.talendforge.org/browse/TUP-27654
> feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/mappings/mapping_Databricks_Delta_Lake.xml
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponentsFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataTalendType.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/ComponentToRepositoryProperty.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericWizardService.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DBTypeForm.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseWizardPage.java
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
TUP-28615:[Bug] Save the property to metadata will change Delta Lake to
JDBC.
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
https://jira.talendforge.org/browse/TUP-27654
* feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE …
> feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE (#3592)

- main/plugins/org.talend.librariesmanager/resources/java/routines/TalendDate.java
https://jira.talendforge.org/browse/TDI-44726
> fix(TDI-44726):add some necessary annotation.

- main/plugins/org.talend.core/src/main/java/org/talend/core/services/ICoreTisService.java
- main/plugins/org.talend.migrationTool/META-INF/MANIFEST.MF
- main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java
- main/plugins/org.talend.repository.items.importexport/META-INF/MANIFEST.MF
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
* Fix TUP-28603 'Export item' missing signature
https://jira.talendforge.org/browse/TUP-28603
> Fix TUP-28603 'Export item' missing signature (#3643)

- main/plugins/org.talend.librariesmanager/resources/java/routines/TalendDate.java
https://jira.talendforge.org/browse/TDI-44726
> fix(TDI-44726):add some necessary annotation. (#3666)

- main/plugins/org.talend.librariesmanager/resources/java/routines/system/ResumeUtil.java
This reverts commit cf52e1e004fdeaf2df4c18ea02a1611571519da0.
> Revert "fix(TDI-44826): Missing line in Resume log (#3640)"

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TPS-4351
**Related PR**
- https://github.com/Talend/studio-full-master/pull/456
- https://github.com/Talend/tcommon-studio-ee/pull/1544
- https://github.com/Talend/tcommon-studio-se/pull/3668
- https://github.com/Talend/tdi-studio-se/pull/5247
> fix(TPS-4351): Make component-runtime class loader find classes in JobServer

- main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/ColorConstants.java
https://jira.talendforge.org/browse/TUP-28811
> feat(TUP-28811)update color for login page

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/NetworkUtil.java
https://jira.talendforge.org/browse/TUP-27076
> fix(TUP-27076): Unable to connect to codecommit GIT after the first login.

- main/plugins/org.talend.librariesmanager/resources/java/routines/system/ResumeUtil.java
See https://jira.talendforge.org/browse/TDI-44962 + https://jira.talendforge.org/browse/TDI-44826
Recreating the SimpleCsvWriter as it was done in fix for https://jira.talendforge.org/browse/TDI-44826 and fixing the problem of stream closed by adding the SimpleCsvWriter to sharedWriterMap.
> fix(TDI-44962): fix stream closed exception

- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
https://jira.talendforge.org/browse/TUP-28839
> fix(TUP-28839)NPE when retrieve schema for JDBC connection of postgresql

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/SharedStudioUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IUpdateService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/IInstalledPatchService.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
- main/plugins/org.talend.updates.runtime/META-INF/MANIFEST.MF
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/model/interfaces/ITaCoKitCarFeature.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/ITaCoKitUpdateService.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/SharedStudioPatchInfoProvider.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/UpdateService.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/utils/PathUtils.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/utils/TaCoKitCarUtils.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/utils/UpdateTools.java
* TUP-28274 Shared Studio: Can't find EMR 5.29 option in Hadoop Cluster
wizard after enable shared studio mode
https://jira.talendforge.org/browse/TUP-28274
> Kjwang/feat tup 27762 new version of ci (#3656)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/UpdateRepositoryHelper.java
https://jira.talendforge.org/browse/TUP-28618
> fix(TUP-28618):[Bug] db type dont show Delta in impact page.

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/ComponentToRepositoryProperty.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericWizardService.java
supported DBs and components automatically
https://jira.talendforge.org/browse/TUP-28640
> feat(TUP-28640):Improve JDBC database support framework to load

- main/plugins/org.talend.librariesmanager/build.properties
- main/plugins/org.talend.librariesmanager/plugin.xml
https://jira.talendforge.org/browse/TUP-28659
> fix(TUP-28659): Remove snapshot version of jars

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/ContextTreeTable.java
https://jira.talendforge.org/browse/TUP-28903
> fix(TUP-28903): NPE exception when clicking on context

- main/plugins/org.talend.designer.maven.tos/resources/apache/official/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/apache/talend/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/cxf/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/pom.xml
- main/plugins/org.talend.libraries.apache.common/pom.xml
- main/plugins/org.talend.libraries.apache.cxf/pom.xml
- main/plugins/org.talend.libraries.apache.http/pom.xml
org.talend.libraries:javax.ws.rs-api-2.0-m10:jar:6.0.0
> add repository for Could not find artifact

- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
to metadata" in component view) to context mode, throw many errors
https://jira.talendforge.org/browse/TUP-28924
> fix(TUP-28924):Export JDBC connection(which create by "Save the property

- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ImageAction.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/contentProvider/DynamicContentProvider.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/linksbar/LinksToolbarItem.java
https://jira.talendforge.org/browse/TUP-28564
correct the url to access cloud website, keep align the url in 3 parts.
> TUP-28564 Fix talend cloud website can't access problem.

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/VersionUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/DialogUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/utils/ELoginInfoCase.java
- main/plugins/org.talend.repository.localprovider/src/main/java/messages.properties
- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
- test/plugins/org.talend.commons.runtime.test/src/org/talend/commons/utils/VersionUtilsTest.java
(#3675)
* feat(TUP-28758)Add a warning when we login to a project and if there
is
migration to do
* feat(TUP-28758)Add a warning when we login to a project and if there
is
migration to do
* update warning info
* format code
* Add a warning when we login to a project and if there is migration to
do
* collect warnings in one dialog
* remove nexus warning dialog
* update login info
* adjust warning content
* adjust warning content
* adjust warning content
* remove useless cases
* add junits
* update method and junits
* modify the text
* get right monthly patch name
* modify project patch version name
* remove Talend word in warning message
Conflicts:
main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/VersionUtils.java …
> feat(TUP-28758)Add a warning when we login to a project and if there is

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/time/PerformanceStatisticUtil.java
- test/plugins/org.talend.commons.runtime.test/src/org/talend/commons/utils/time/PerformanceStatisticUtilTest.java
https://jira.talendforge.org/browse/TUP-28944
fix the number format problem related to locale.
> TUP-28944 Issue with performance tracking with french locale

- main/plugins/org.talend.librariesmanager/build.properties
- main/plugins/org.talend.librariesmanager/plugin.xml
https://jira.talendforge.org/browse/TUP-28659
> fix(TUP-28659): Remove snapshot version of jars (#3664)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/UpdateRepositoryHelper.java
https://jira.talendforge.org/browse/TUP-28618
> fix(TUP-28618):[Bug] db type dont show Delta in impact page. (#3676)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/ComponentToRepositoryProperty.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IGenericWizardService.java
* feat(TUP-28640):Improve JDBC database support framework to load
supported DBs and components automatically
https://jira.talendforge.org/browse/TUP-28640
* feat(TUP-28640):Improve JDBC database support framework to load
supported DBs and components automatically
https://jira.talendforge.org/browse/TUP-28640
> feat(TUP-28640):Improve JDBC database support framework to load (#3686)

- main/plugins/org.talend.librariesmanager/plugin.xml
https://jira.talendforge.org/browse/TUP-28659
> fix(TUP-28659): Update verson of crypto-utils

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomIdsHelper.java
https://jira.talendforge.org/browse/TUP-28952
> fix(TUP-28952):TOS: NPE when delete items to recycle bin

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomIdsHelper.java
https://jira.talendforge.org/browse/TUP-28952
> fix(TUP-28952):TOS: NPE when delete items to recycle bin (#3737)

- main/plugins/org.talend.core/src/main/java/org/talend/core/services/ICoreTisService.java
- main/plugins/org.talend.migrationTool/META-INF/MANIFEST.MF
- main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java
- main/plugins/org.talend.repository.items.importexport/META-INF/MANIFEST.MF
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
* Fix TUP-28603 'Export item' missing signature
https://jira.talendforge.org/browse/TUP-28603
> Fix TUP-28603 'Export item' missing signature (#3643) (#3681)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/relationship/RelationshipItemBuilderTest.java
* fix(TUP-26138): Regenerate relationship index
Conflicts:
main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
> bugfix(TUP-26138) Regenerate relationship.index (#3088) (#3473)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
Batch jobs job into Artifact Repository for Talend Studio 7.2 and 7.3
> fix(TUP-28846): Export Type Dropdown is empty when publishing Big Data

- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
Fix TUP-27762 Multi-User:new version of ci builder can't synchronize to m2 of multi user ( Fix can't sync shared studio library in patch because the modify of TUP-27924)
https://jira.talendforge.org/browse/TUP-27762
> Fix can't sync shared studio library in patch because the modify of

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/maven/MavenUrlHelper.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ConfigModuleDialog.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/ConfigModuleHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/VersionUtil.java
* fix(TUP-28978): search local support other type and strip snapshot version
* fix(TUP-28978): Fix strip timestamp
* fix(TUP-2897): search remote dll, strip timestamp
* fix(TUP-28978): search local filtering timestamp
* fix(TUP-28978): Revert unnecessary changed files
> bugfix(TUP-28978): Add migration and make module name consistent (#3753)

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/time/TimeMeasurePerformance.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-29059
Add the project name to first log message, like : 
XXX.TimeMeasurePerformance  -   Start 'logOnProject'**, logon project name 'Local_Project'** ...
> TUP-29059 Add project name in the studio performance log.

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ConfigModuleDialog.java
https://jira.talendforge.org/browse/TUP-29170
> fix(TUP-29170): Fix jarpath change

- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
…sql (#3700)
https://jira.talendforge.org/browse/TUP-28839
> fix(TUP-28839)NPE when retrieve schema for JDBC connection of postgre

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IUpdateService.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/ActionBarBuildHelper.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/ExtraFeaturesUpdatesFactory.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/AbstractExtraUpdatesFactory.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/PluginOptionalMissingJarsExtraUpdatesFactory.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/factory/PluginRequiredMissingJarsExtraUpdatesFactory.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/SharedStudioPatchInfoProvider.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/UpdateService.java
Fix TUP-28050 Multi-User: Avoid possible actions that are not supported on shared studio
https://jira.talendforge.org/browse/TUP-28050
> Kjwang/fix tup 28050 avoid possible actions (#3683)

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableForm.java
* fix(TUP-26278): Validate table name before persisting
* fix(TUP-26278): Remove validating table name
> bugfix(TUP-26278): Validate table name before persisting (#3108)

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ConfigModuleDialog.java
https://jira.talendforge.org/browse/TUP-29170
> fix(TUP-29170): Fix jarpath change (#3786)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-29076
> feat(TUP-29076):support memsql in studio metadata and components

- main/plugins/org.talend.librariesmanager.ui/src/main/java/messages.properties
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ConfigModuleDialog.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/utils/ConfigModuleHelper.java
https://jira.talendforge.org/browse/TUP-29208
> fix(TUP-29208): add warning message for checking remote artifactory

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
- test/plugins/org.talend.designer.maven.test/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPomTest.java
https://jira.talendforge.org/browse/TUP-28904
Add latest version dependency jars to ci job dependencies.
> TUP-28904 CI/CD build for DI jobs that contain 2 different versions of httpcore and httpclient are inconsistent with Studio build

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/SVNConstant.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/IRepositoryService.java
- main/plugins/org.talend.core/src/main/java/org/talend/core/services/IGITProviderService.java
https://jira.talendforge.org/browse/TUP-29126
> feat(TUP-29126): Github Renaming the default branch from master

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/components/IComponentsFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/ComponentsLocationProvider.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/SharedStudioInfoProvider.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/SharedStudioUtils.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
TUP-28833 Multi-User: support custom javajet component in shared studio
https://jira.talendforge.org/browse/TUP-28833
> TUP-28833 Multi-User: support custom javajet component in shared studio

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
https://jira.talendforge.org/browse/TUP-29076
> feat(TUP-29076):support memsql in studio metadata and components (#3779)

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/NetworkUtil.java
- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/TalendProxySelector.java
https://jira.talendforge.org/browse/TUP-28790
> feat(TUP-28790): Enhance detection of localhost

- test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtilTest.java
> Fix junit failure

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://jira.talendforge.org/browse/TDI-45157
> chore(TDI-45157): bump TCK components version

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/EParameterFieldType.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/metadata/celleditor/ModuleListCellEditor.java
https://jira.talendforge.org/browse/TESB-28330
> feat(TESB-28330): remove workaround for cConfig

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/commons/utils/io/FilesUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/general/ILibrariesService.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/CustomUriManager.java
https://jira.talendforge.org/browse/TUP-29285
> fix(TUP-29285): Improve reloading logic of Custom Uri Mapping

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/ContextUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManagerHelper.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/CodeM2CacheManager.java
Fix TUP-29290 "Detect and Update all jobs " is not identifying the changes in imported projects.
https://jira.talendforge.org/browse/TUP-29290
> Fix TUP-29290 "Detect and Update all jobs " is not identifying the changes in imported projects.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/ContextUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/update/RepositoryUpdateManagerHelper.java
Fix TUP-29290 "Detect and Update all jobs " is not identifying the changes in imported projects.
https://jira.talendforge.org/browse/TUP-29290
> Fix TUP-29290 "Detect and Update all jobs " is not identifying the changes in imported projects. (#3833)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/JobContextManager.java
https://jira.talendforge.org/browse/TUP-29227
> fix(TUP-29227): set default prompt value if it is null

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/JobContextManager.java
https://jira.talendforge.org/browse/TUP-29227
> fix(TUP-29227): Set prompt value if it is null

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/PluginChecker.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/IRepositoryService.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/CodeM2CacheManager.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenRoutinePom.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
* fix(TUP-29360): Missing log4j2 jar on user routines
* fix(TUP-29360): fix switch log4j level problem
> fix(TUP-29360): Missing log4j2 jar on user routines (#3858)

- main/plugins/org.talend.core/src/main/java/org/talend/core/CorePlugin.java
https://jira.talendforge.org/browse/TUP-28314
> fix(TUP-28314): Talend Studio - Git Pull and Merge not showing branches

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
https://jira.talendforge.org/browse/TUP-29165
> fix(TUP-29165): Add cache for all of current project nodes

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/TalendCodeProjectUtil.java
https://jira.talendforge.org/browse/TUP-29157
> fix(TUP-29157): Recreate project if project can not be opened correctly

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/SharedStudioUtils.java
- main/plugins/org.talend.core/src/main/java/org/talend/core/prefs/CorePreferenceInitializer.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/metadata/xml/utils/TreeUtil.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/ui/wizard/concept/CreateConceptWizard.java
- main/plugins/org.talend.repository.mdm/src/main/java/org/talend/repository/mdm/util/MDMUtil.java
* TUP-28891:Shared Studio: Check which functions will write data into
folder "temp" of Studio installation folder from code
https://jira.talendforge.org/browse/TUP-28891
> Kjwang/feat tup 28891 temp folder (#3799)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/NexusServerUtils.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/ArtifacoryRepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtil.java
- test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtilTest.java
https://jira.talendforge.org/browse/TUP-28893
Conflicts:
main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/ArtifacoryRepositoryHandler.java
main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
> fix(TUP-28893)Support more types of artifact for share libs

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
* fix(TUP-29165): Add cache for all of current project nodes
* fix(TUP-29165): Add cache for loaded nodes
* fix(TUP-29165): Not cache emfproject
* fix(TUP-29165): add projectlabel to key
* fix(TUP-29165): add object as key
> fix(TUP-29165): Add cache for all of current project nodes (#3827)

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/properties/tab/HorizontalTabFactory.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
TUP-29231 Shared Studio: Check Exchange related functions after Exchange websevice issue resolved
https://jira.talendforge.org/browse/TUP-29231
> TUP-29231 Shared Studio: Check Exchange related functions after Exchange websevice issue resolved

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
install new monthly 11 patch
https://jira.talendforge.org/browse/TUP-29368
> fix(TUP-29368):[SingleStore]Mapping file missing for metadata when

- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ConnectionContextHelper.java
- test/plugins/org.talend.metadata.managment.ui.test/src/main/test/org/talend/metadata/managment/ui/utils/ConnectionContextHelperTest.java
from Metadata Connection are read-only
https://jira.talendforge.org/browse/TUP-29344
> fix(TUP-29344):Local context variables of new context envs inherited

- main/plugins/org.talend.commons.runtime/talend.properties
Reverts Talend/tcommon-studio-se#3891
> Revert "TESB-31287:"

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/dialogs/ConfigModuleDialog.java
https://jira.talendforge.org/browse/TUP-29083
> TUP-29083 update custom mvn uri after select different module.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
- main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonViewer.java
https://jira.talendforge.org/browse/TUP-29165
> fix(TUP-29165): add cache for project nodes

- main/plugins/org.talend.core/src/main/java/org/talend/core/services/ICoreTisService.java
- main/plugins/org.talend.migrationTool/META-INF/MANIFEST.MF
- main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java
- main/plugins/org.talend.repository.items.importexport/META-INF/MANIFEST.MF
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
TUP-29525 Update certificates for item / job signing on 7.0 / 7.1
https://jira.talendforge.org/browse/TUP-29525
> Kjwang/fix tup 29525 update certificates 71 (#3892)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/RepositoryWorkUnit.java
https://jira.talendforge.org/browse/TUP-29390
> fix(TUP-29390): Improve the file commit logic in RepositoryWorkUnit during Pull and Merge

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/IESBService.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
> fix(TESB-30556):[CI] SOAP service operation job is duplicated in the

- main/plugins/org.talend.core/src/main/java/org/talend/core/services/ICoreTisService.java
- main/plugins/org.talend.migrationTool/META-INF/MANIFEST.MF
- main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java
- main/plugins/org.talend.repository.items.importexport/META-INF/MANIFEST.MF
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
TUP-29525 Update certificates for item / job signing on 7.0 / 7.1
https://jira.talendforge.org/browse/TUP-29525
> Kjwang/fix tup 29525 update certificates 71 (#3892) (#3898)

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://jira.talendforge.org/browse/TDI-45339
> chore(TDI-45339): Bump TCK comp version

- main/plugins/org.talend.commons.runtime/pom_server.xml
- main/plugins/org.talend.designer.maven.tos/resources/build/plugins/maven-bundle-plugin-2-3-7/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/build/plugins/maven-bundle-plugin-2-5-3/pom.xml
https://jira.talendforge.org/browse/TUP-29402
> chore(TUP-29402)CVE on plexus-archiver-1.0.jar and plexus-archiver-2.1.jar

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/SharedStudioUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IUpdateService.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
- main/plugins/org.talend.updates.runtime/src/main/java/messages.properties
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/SharedStudioPatchInfoProvider.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/UpdateService.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/ui/ShowWizardHandler.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/string/DigestUtil.java
TUP-29426 Shared Studio: We should not display button "Installation of BPM is required..." on toolbar and task status area.
https://jira.talendforge.org/browse/TUP-29426
> TUP-29426 Shared Studio: We should not display button "Installation of BPM is required..." on toolbar and task status area.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/SharedStudioUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/IUpdateService.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
- main/plugins/org.talend.updates.runtime/src/main/java/messages.properties
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/SharedStudioPatchInfoProvider.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/UpdateService.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/ui/ShowWizardHandler.java
TUP-29426 Shared Studio: We should not display button "Installation of
BPM is required..." on toolbar and task status area.
https://jira.talendforge.org/browse/TUP-29426
> TUP-29426 Shared Studio: We should not display button "Installation of BPM is required..." on toolbar and task status area. 

- main/plugins/org.talend.designer.maven.tos/resources/build/plugins/talend-compiler-plugin/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/build/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/unzip/pom.xml
- main/plugins/org.talend.designer.maven/resources/templates/general/pom_project_template.xml
> chore(TUP-29382): upgrade maven-jar-plugin to upgrade commons-compress

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/AbstractMavenCodesTemplatePom.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/CreateMavenJobPom.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomUtil.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
- test/plugins/org.talend.librariesmanager.test/src/org/talend/librariesmanager/model/ModulesNeededProviderTest.java
* fix routine dependency issue
* code change
* code change
* code change
* fix junit
* fix junit
Conflicts:
main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
> fix routine dependency issue (#3946)

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
[7.3.1] After publish to cloud, job with context password fails with NullPointer exception
> TESB-31277: [7.3.1] After publish to cloud, job with context password fails with NullPointer exception

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/preference/I18nPreferencePage.java
https://jira.talendforge.org/browse/TUP-29595
> fix(TUP-29595): Slow start of studio when install all additional packages

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/context/ContextUtils.java
https://jira.talendforge.org/browse/TUP-29447
> fix(TUP-29447)Studio should not pop up "update detection" shell when opening job

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/startup/ShareCIJarsOnStartup.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
https://jira.talendforge.org/browse/TUP-29700
> fix(TUP-29700): skip share ci jars if tos

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
https://jira.talendforge.org/browse/TUP-29432
> fix(TUP-29432): remove beans check

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProjectRepositoryNode.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DeleteAction.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/ERepositoryObjectType.java
> feat(TUP-29943):codejars under recycle bin should be hierarchy

- main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonViewer.java
https://jira.talendforge.org/browse/TUP-30069
> fix(TUP-30069): Fix repository tree

- main/plugins/org.talend.repository.view/src/org/talend/repository/navigator/RepoViewCommonViewer.java
https://jira.talendforge.org/browse/TUP-30069
> fix(TUP-30069): Open job with NPE and job which in folder disappeared

- main/plugins/org.talend.librariesmanager/plugin.xml
- main/plugins/pom_server.xml
This reverts commit 5780ce269318d7643892ea655103964df53a593b.
> Revert "fix(TDI-45465): upgrade tcompv0 for studio 7.3 patch and master (#3981)"

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DeleteAction.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/EmptyRecycleBinAction.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/RestoreAction.java
items, include delete forever from recycle bin and empty recycle bin
Restore code should also restore parent node codeJar
> feat(TUP-29943):delete codejar forever should also delete child code

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/wizard/models/ImportNodesBuilder.java
> feat(TUP-29943):Fail to import custom Routine jar

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DeleteAction.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/wizard/models/ImportNodesBuilder.java
should not have duplicate nodes in import dialog
> feat(TUP-29943):delete forever should also delete codejar folder

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/database/SAPHanaDataBaseMetadata.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/DqRepositoryViewService.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/model/DBConnectionFillerImpl.java
- main/plugins/org.talend.model/src/main/java/org/talend/cwm/helper/PackageHelper.java
- main/plugins/org.talend.model/src/main/java/org/talend/cwm/helper/TableHelper.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/sql/metadata/constants/TableType.java
* feat(TDQ-19005): Support SAP Hana calculation views on DQ profiling in
Studio
> Zshen/feat/tdq 19005 implement calculation view (#3977)

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
https://jira.talendforge.org/browse/TUP-29700
> feat(TUP-29700): move preference settings to libraries page

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
https://jira.talendforge.org/browse/TUP-29700
> feat(TUP-29700): move preference settings to libraries page (#3990)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/RoutineUtils.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
> feat(TUP-29943):import no value present issue and import to change inner

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ILibraryManagerService.java
- main/plugins/org.talend.core/src/main/java/org/talend/core/services/ICoreTisService.java
- main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/setting/preference/M2eUserSettingForTalendLoginTask.java
https://jira.talendforge.org/browse/TUP-30160
> fix(TUP-30160): Signer won't be installed if studio path has space character

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/handlers/JobRoutinesItemRelationshipHandler.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/DeleteAction.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/EmptyRecycleBinAction.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/relationship/RelationshipItemBuilder.java
> feat(TUP-29943):delete folder issue and build job routinesJar

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/IProxyRepositoryFactory.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/PropertiesWizard.java
> feat(TUP-29943): rename codejar should update package and folder path

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/routines/RoutineLibraryMananger.java
> feat(TUP-29943):export and import to deploy libs issue

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/ITaCoKitDependencyService.java
- main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/wizard/imports/providers/ImportItemsViewerLabelProvider.java
https://jira.talendforge.org/browse/TUP-23738
> fix(TUP-23738):The couchbase icon is not correct when import (#4025)

- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/PatchP2InstallManager.java
* Fix TUP-29885 ERROR: Some patches are not compatible with current
product
https://jira.talendforge.org/browse/TUP-29885
> Fix TUP-29885 ERROR: Some patches are not compatible with current product (#3970)

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
Reverts Talend/tcommon-studio-se#4011
> Revert "TESB-31841: Regression caused by TESB-30969 , when run job gets java.…"

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/NetworkUtil.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/prefs/ITalendCorePrefConstants.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/startup/ShareLibsSynchronizer.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/prefs/LibrariesManagerUtils.java
> fix(TUP-30360): add an option to disable sharing libraries

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://jira.talendforge.org/browse/TDI-45607
> fix(TDI-45607) Upgrade tck in studio

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/RepositoryWorkUnit.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
https://jira.talendforge.org/browse/TUP-30103
> fix(TUP-30103): Studio sometimes hangs for 20 seconds

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/service/ITaCoKitService.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/constants/FileConstants.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/ProxyRepositoryFactory.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ComponentsJsonModel.java
- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
(#1988)
* fix(TUP-21055)Migration check executed at each start of studio
https://jira.talendforge.org/browse/TUP-21055
* fix(TUP-21055)Migration check executed at each start of studio
https://jira.talendforge.org/browse/TUP-21055
* fix(TUP-21055)Migration check executed at each start of studio
https://jira.talendforge.org/browse/TUP-21055
Conflicts:
main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
> fix(TUP-21055)Migration check executed at each start of studio (#1973)

- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/startup/ShareLibsSynchronizer.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/prefs/LibrariesManagerUtils.java
> fix(TUP-30360): add preference to disable sharing libs from components

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/actions/CopyObjectAction.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/services/IDesignerMavenService.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/DesignerMavenService.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/PropertiesWizardPage.java
> feat(TUP-29943):fix some copy paste issues

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/ui/view/RepositoryLabelProvider.java
> feat(TUP-29943):image issue

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/IElementParameter.java
- main/plugins/org.talend.core/src/main/java/org/talend/core/model/runprocess/shadow/ObjectElementParameter.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/TestElementParameter.java
https://jira.talendforge.org/browse/TUP-30273
> fix(TUP-30273)tDBOutput component compilation error

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/utils/ProjectDataJsonProvider.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/RepositoryWorkUnit.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
https://jira.talendforge.org/browse/TUP-30180
> item(TUP-30180): Studio slowness on merge operation

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
Reverts Talend/tcommon-studio-se#4086
> Revert "chore(TDQ-18698)：use i18n message"

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/prefs/ITalendCorePrefConstants.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/startup/ShareLibsSynchronizer.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/prefs/LibrariesManagerUtils.java
* fix(TUP-30360): add an option to disable sharing libraries
* fix(TUP-30360): add new preference to disable sharing libs at startup
* fix(TUP-30360): update log message
* fix(TUP-30360): install libfile
Conflicts:
main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/NetworkUtil.java
main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
> fix(TUP-30360): add an option to disable sharing libraries (#4040)

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TDI-45704
*Related PRs*
- https://github.com/Talend/studio-full-master/pull/660
- https://github.com/Talend/tcommon-studio-ee/pull/1767
- https://github.com/Talend/tcommon-studio-se/pull/4090
- https://github.com/Talend/tdi-studio-se/pull/5890
> feat(TDI-45704): bump component-runtime to 1.30.0

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TUP-30526
> fix(TUP-25109): missing redshiftjar warning

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/maven/MavenConstants.java
- main/plugins/org.talend.designer.maven.ui/src/main/java/messages.properties
- main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/setting/project/page/MavenProjectSettingPage.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomIdsHelper.java
https://jira.talendforge.org/browse/TUP-30416
> fix(TUP-30416): backport TUP-30416

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/maven/MavenConstants.java
- main/plugins/org.talend.designer.maven.ui/src/main/java/messages.properties
- main/plugins/org.talend.designer.maven.ui/src/main/java/org/talend/designer/maven/ui/setting/project/page/MavenProjectSettingPage.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/AggregatorPomsHelper.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/PomIdsHelper.java
https://jira.talendforge.org/browse/TUP-30547
> fix(TUP-30416): backport TUP-30416 (#4088)

- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/context/nattableTree/ExtendedContextColumnPropertyAccessor.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/context/ContextModeWizard.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/wizard/context/ContextWizard.java
https://jira.talendforge.org/browse/TUP-29586
after save changed context , popup dialog to update job.
> fix(TUP-29586) Change repository context variable type would pop up job update dialog.

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/network/NetworkUtil.java
> fix(TUP-30360): add missing properties

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/routines/RoutineLibraryMananger.java
> fix(TUP-30360): wrong backport

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/NexusServerUtils.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/ArtifacoryRepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/Nexus3RepositoryHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/NexusDownloader.java
wrong nexus url.
https://jira.talendforge.org/browse/TUP-30277
> fix(TUP-30277)Fail to download jar in remote project when tac set a

- main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/managers/ProviderManager.java
https://jira.talendforge.org/browse/TUP-29768
> fix(TUP-29768)Studio won't release resource after cancel import

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/IMetadataColumn.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataColumn.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataTable.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolHelper.java
the job
https://jira.talendforge.org/browse/TUP-30615
> fix(TUP-30615):Schema Update Detection popping up everytime upon opening

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/nexus/NexusServerUtils.java
https://jira.talendforge.org/browse/TUP-30277
> fix(TUP-30277)Fail to download jar in remote project when tac set a wrong nexus url

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/EDatabase4DriverClassName.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
https://jira.talendforge.org/browse/TUP-30381
> feat(TUP-30381)Support greenplum driver for Greenplum Database in studio metadata

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataTalendType.java
https://jira.talendforge.org/browse/TUP-30216
> fix(TUP-30216):Commandline install patch and login project throw NPE

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
https://jira.talendforge.org/browse/TUP-30685
> fix(TUP-30685) Mvn package job use joblet in subref project fail to run the bat file correct.

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/utils/ClasspathsJarGenerator.java
https://jira.talendforge.org/browse/TUP-30047
> feat(TUP-30047): port TUP-30047

- main/plugins/org.talend.designer.maven.tos/resources/components/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/pom.xml
https://jira.talendforge.org/browse/TDI-45881
> fix(TDI-45881):Update jackson mapper

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/ICoreUIService.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/CoreUIService.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
https://jira.talendforge.org/browse/TUP-30768
> TUP-30768 Can't reset performance_record if first patch use manual installation then the second use Software update

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/service/ICoreUIService.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/CoreUIService.java
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
https://jira.talendforge.org/browse/TUP-30768
move 'reset performance record' to other place.
> fix(TUP-30768): Can't reset performance_record if first patch use manual installation then the second use Software update

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/PluginChecker.java
create custom routine jar/bean jar.
> fix(TUP-30786):Avoid to click finish button more than once when do

- main/plugins/org.talend.librariesmanager/src/main/java/messages.properties
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/ShareComponentsLibsJob.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtil.java
https://jira.talendforge.org/browse/TUP-30203
> bugfix(TUP-30203): Search required groups only

- main/plugins/org.talend.core.runtime/mappings/mapping_Greenplum.xml
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/EDatabase4DriverClassName.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/DatabaseConnStrUtil.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataTalendType.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/RepositoryToComponentProperty.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/ExtractMetaDataUtils.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseWizard.java
(#4138)
* feat(TUP-30381)Support greenplum driver for Greenplum Database in
studio
metadata
https://jira.talendforge.org/browse/TUP-30381
* add dbversion for greeenplu
* add dbversion
* update mapping_greenplum file
* update greenplum_mapping
* update greenplum mapping
Conflicts:
main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/EDatabase4DriverClassName.java
main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java
main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/version/EDatabaseVersion4Drivers.java
> feat(TUP-30381)Support greenplum driver for Greenplum Database in studio

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TDI-45842
> feat(TDI-45842): bump component-runtime to 1.31.2

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/IProcess.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/process/JobInfo.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/process/TalendProcessOptionConstants.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/ui/IJobletProviderService.java
- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
- test/plugins/org.talend.core.test/src/org/talend/designer/runprocess/ProcessorUtilitiesTest.java
* fix(TUP-30849):Improve build Job performance
https://jira.talendforge.org/browse/TUP-30849
* fix(TUP-30849):Improve build Job performance
https://jira.talendforge.org/browse/TUP-30849
* fix(TUP-30849):Improve build Job performance
https://jira.talendforge.org/browse/TUP-30849
* fix(TUP-30849):Improve build Job performance
https://jira.talendforge.org/browse/TUP-30849
* fix(TUP-30849):Improve build Job performance
https://jira.talendforge.org/browse/TUP-30849
* fix(TUP-30849):Improve build Job performance
https://jira.talendforge.org/browse/TUP-30849
* …
> fix(TUP-30849):Improve build Job performance

- main/plugins/org.talend.librariesmanager/src/main/java/messages.properties
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/ShareComponentsLibsJob.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtil.java
* fix(TUP-30203): only search required library groups
* fix(TUP-30203): only search required library groups, refactor
* fix(TUP-30203): only search required library groups, refactor
* fix(TUP-30203): exclude class file
* fix(TUP-30203): exclude class file
* fix(TUP-30203): share libs in background
* fix(TUP-30203): add i18n
Conflicts:
main/plugins/org.talend.librariesmanager/src/main/java/messages.properties
main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtil.java
> bugfix(TUP-30203): Search required groups only (#4174)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/prefs/ITalendCorePrefConstants.java
- main/plugins/org.talend.librariesmanager.ui/src/main/java/org/talend/librariesmanager/ui/startup/ShareLibsSynchronizer.java
- main/plugins/org.talend.librariesmanager/src/main/java/messages.properties
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/ShareLibrareisHelper.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/ShareComponentsLibsJob.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtil.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/prefs/LibrariesManagerUtils.java
https://jira.talendforge.org/browse/TUP-30203
> bugfix(TUP-30203): Performance issue when logon project / switch branch

- main/plugins/org.talend.core/src/main/java/org/talend/core/model/utils/ContextOrderProperties.java
migration 7.2.1 to 7.3.1 R2021-01
> fix(TUP-30921):Job fails with "Could not find the context Default" after

- main/plugins/org.talend.model/src/main/java/org/talend/cwm/helper/TaggedValueHelper.java
Reverts Talend/tcommon-studio-se#4172
> Revert "fix(TDQ-19030): fix complier error"

- main/plugins/org.talend.designer.maven/resources/templates/general/pom_project_template.xml
https://jira.talendforge.org/browse/TUP-30992
> fix(TUP-30992):CVE: junit-4.11,4.13

- main/plugins/org.talend.designer.maven/resources/templates/general/pom_project_template.xml
https://jira.talendforge.org/browse/TUP-30992
> fix(TUP-30992):CVE: junit-4.11,4.13 (#4220)

- main/plugins/org.talend.designer.maven.tos/resources/surefire/pom.xml
- main/plugins/org.talend.designer.maven.tos/resources/unzip/pom.xml
- main/plugins/org.talend.designer.maven/resources/templates/general/pom_project_template.xml
https://jira.talendforge.org/browse/TUP-30992
> chore(TUP-30992): remove junit-4.12

- main/plugins/org.talend.designer.maven/resources/templates/general/pom_project_template.xml
https://jira.talendforge.org/browse/TUP-30992
> chore(TUP-30992): revert unncessary changes

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/EDatabaseTypeName.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/messages.properties
- main/plugins/org.talend.repository.metadata/plugin.xml
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/metadata/migration/RemoveDeprecateSASItemMigrationTask.java
https://jira.talendforge.org/browse/TUP-30730
> feat(TUP-30730):Remove SAS from metadata wizard.

- main/plugins/org.talend.designer.maven/resources/templates/general/pom_project_template.xml
Reverts Talend/tcommon-studio-se#4224
> Revert "chore(TUP-30992): revert unncessary changes"

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
> chore: bump to tck:1.32.0

- main/plugins/org.talend.platform.logging/src/org/talend/platform/logging/Activator.java
https://jira.talendforge.org/browse/TUP-30846
> feat(TUP-30846) Unify studio version information & patch info in studio logs.

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/HandlerUtil.java
Fix TUP-31096 Could not find or load main class error on the jobs created on the Feature Branch which has #
https://jira.talendforge.org/browse/TUP-31096
> Fix TUP-31096 Could not find or load main class error on the jobs

- main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
* chore(TUP-31155): change the way to check if it's CI mode
* TUP-31155 code change
* TUP-31155 add comments
Conflicts:
main/plugins/org.talend.core/src/main/java/org/talend/designer/runprocess/ProcessorUtilities.java
> chore(TUP-31155): change the way to check if it's CI mode

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/ProjectManager.java
https://jira.talendforge.org/browse/TUP-31060
> chore(TUP-31060): ci build job cannot found routine in sub reference project.

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/launch/MavenCommandLauncher.java
case fail
https://jira.talendforge.org/browse/TUP-31234
> fix(TUP-31234):Build job fail with option "Execute tests" if any test

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/HandlerUtil.java
Revert https://github.com/Talend/tcommon-studio-se/pull/4250/files that cause tuj import failed
https://jira.talendforge.org/browse/TUP-31096
> Revert the commit of TUP-31096 to test tuj

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolHelper.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/projectsetting/ProjectPreferenceManager.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/preference/SpecificSettingPreferencePage.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/preference/metadata/MetadataPreferenceInitializer.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableForm.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/MetadataToolAvroHelperTest.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/MetadataToolHelperTest.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/ContextParameterUtilsTest.java
- test/plugins/org.talend.metadata.managment.test/src/org/talend/core/model/metadata/builder/ConvertionHelperTest.java
Feat:TUP-30377 Move the "Allow specific characters (UTF8,...)" preference setting to project setting.
https://jira.talendforge.org/browse/TUP-30377
> Feat:TUP-30377 Move the "Allow specific characters (UTF8,...)" preference setting to project setting.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/MetadataToolHelper.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/projectsetting/ProjectPreferenceManager.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/preference/SpecificSettingPreferencePage.java
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/preference/metadata/MetadataPreferenceInitializer.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableForm.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/MetadataToolAvroHelperTest.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/metadata/MetadataToolHelperTest.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/ContextParameterUtilsTest.java
- test/plugins/org.talend.metadata.managment.test/src/org/talend/core/model/metadata/builder/ConvertionHelperTest.java
Feat:TUP-30377 Move the "Allow specific characters (UTF8,...) preference
setting to project setting.
https://jira.talendforge.org/browse/TUP-30377
> Feat:TUP-30377 Move the "Allow specific characters (UTF8,...)" (#4238)

- main/plugins/org.talend.model/src/main/java/org/talend/cwm/helper/TaggedValueHelper.java
Reverts Talend/tcommon-studio-se#4212
> Revert "Revert "fix(TDQ-19030): fix complier error""

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/EImpalaDriver.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/DatabaseConnStrUtil.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/DbConnStrForHive.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/template/EDatabaseConnTemplate.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/DBConnectionContextUtils.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/metadata/managment/connection/manager/ImpalaConnectionManager.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
* fix(TUP-31248):impala metadata connection issues for Cloudera
* TUP-31248 revert mistake remove
* TUP-31248 remove some useless code
* TUP-31248 add connection info to log when connection failed
> fix(TUP-31248):impala metadata connection issues for Cloudera (#4246)

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
Reverts Talend/tcommon-studio-se#4263
> Revert "APPINT-32905: Issue with Rest service flow"

- main/plugins/org.talend.designer.maven.tos/resources/build/plugins/karaf-maven-plugin-4-2-10/pom.xml
https://jira.talendforge.org/browse/APPINT-32936
> chore(APPINT-32936):CVE:Upgrade commons-codec-1.11 to 1.15

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/ModulesNeededProvider.java
https://jira.talendforge.org/browse/TUP-31060
> fix(TUP-31060): store real routine id in case recreated routine with same name.

- main/features/org.talend.core.feature/feature.xml
https://jira.talendforge.org/browse/TUP-30475
Add missing org.talend.migrationTool.nl
> feat(TUP-30475): studio lite

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/AbstractEMFRepositoryFactory.java
TUP-31227 Studio populate UnstagedChanges for Global Routines and SQL Templates when opening a new Feature Branch (Improve the code)
https://jira.talendforge.org/browse/TUP-31227
> TUP-31227 Studio populate UnstagedChanges for Global Routines and SQL Templates when opening a new Feature Branch (Improve the code)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/AbstractEMFRepositoryFactory.java
* TUP-31227 Studio populate UnstagedChanges for Global Routines and SQL
Templates when opening a new Feature Branch
https://jira.talendforge.org/browse/TUP-31227
> Kjwang/fix tup 31227 studio populate unstaged changes (#4277)

- main/plugins/org.talend.core.repository/src/main/java/org/talend/core/repository/model/AbstractEMFRepositoryFactory.java
TUP-31227 Studio populate UnstagedChanges for Global Routines and SQL
Templates when opening a new Feature Branch
https://jira.talendforge.org/browse/TUP-31227
> Kjwang/fix tup 31227 studio populate unstaged changes (#4277) (#4302)

- main/plugins/org.talend.designer.maven/src/main/java/org/talend/designer/maven/tools/creator/AbstractMavenCodesTemplatePom.java
https://jira.talendforge.org/browse/TUP-31380
> fix(TUP-31380): include all needed modules for routines in CI mode

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/table/database/DatabaseTableForm.java
> fix(TUP-31164)Guess schema button on the informix tDBinput component

- main/plugins/org.talend.designer.maven.tos/resources/unzip/pom.xml
https://jira.talendforge.org/browse/TUP-30451
> chore(TUP-30451): remove cve jars

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/IRepositoryPrefConstants.java
> feat(TUP-30343):have the "Export Dependencies" option checked by default.

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/IRepositoryPrefConstants.java
> feat(TUP-30343):have the "Export Dependencies" option checked by default (#4312)

- main/plugins/org.talend.libraries.apache.axis2/pom.xml
https://jira.talendforge.org/browse/TUP-30834
> feat(TUP-30834) remove extra tag.

- main/plugins/org.talend.core.runtime/.classpath
- main/plugins/org.talend.core.runtime/META-INF/MANIFEST.MF
- main/plugins/org.talend.core.runtime/build.properties
- main/plugins/org.talend.core.runtime/pom.xml
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/ContextParameterUtilsTest.java
https://jira.talendforge.org/browse/TUP-31580
> fix(TUP-31580): replace javascriptengine

- main/plugins/org.talend.core.runtime/.classpath
- main/plugins/org.talend.core.runtime/META-INF/MANIFEST.MF
- main/plugins/org.talend.core.runtime/build.properties
- main/plugins/org.talend.core.runtime/pom.xml
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/ContextParameterUtils.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/utils/NodeUtil.java
- test/plugins/org.talend.core.runtime.test/src/org/talend/core/model/utils/ContextParameterUtilsTest.java
https://jira.talendforge.org/browse/TUP-31580
> fix(TUP-31580): replace javascriptengine (#4334)

- main/plugins/org.talend.core.runtime/pom.xml
https://jira.talendforge.org/browse/TUP-31580
> fix(TUP-31580): Exclude unnecessary libraries

- main/plugins/org.talend.core.runtime/pom.xml
https://jira.talendforge.org/browse/TUP-31580
> fix(TUP-31580): execlude other dependencies

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TDI-46215
*Related PR*
- https://github.com/Talend/tdi-studio-se/pull/6294
- https://github.com/Talend/tcommon-studio-se/pull/4338
- https://github.com/Talend/tcommon-studio-ee/pull/1955
- https://github.com/Talend/studio-full-master/pull/780
> feat(TDI-46215): bump component-runtime to 1.33.1

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/service/ICollectDataService.java
- main/plugins/org.talend.core.ui/plugin.xml
- main/plugins/org.talend.core.ui/src/main/java/org/talend/core/ui/token/AMCUsageTokenCollector.java
https://jira.talendforge.org/browse/TUP-31252
> fix(TUP-31252) Improve the data collector for AMC.

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/service/P2InstallComponent.java
- main/plugins/org.talend.rcp/src/main/java/messages.properties
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
- main/plugins/org.talend.updates.runtime/src/main/java/messages.properties
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/engine/PatchP2InstallManager.java
https://jira.talendforge.org/browse/TUP-30489
> feat(TUP-30489) add progress bar to indicate install patch. 

- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/contentProvider/DynamicContentProviderGeneric.java
https://jira.talendforge.org/browse/TUP-31796
> fix(TUP-31796): Pictures in welcom page are missing

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/repository/model/RepositoryConstants.java
https://jira.talendforge.org/browse/TUP-31122
> feat(TUP-31122)new Data Center in AWS Australia

- main/plugins/org.talend.registration/src/main/java/org/talend/registration/register/proxy/RegisterUserPortTypeProxy.java
https://jira.talendforge.org/browse/TUP-30834
> feat(TUP-30834) fix ClassCastException

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/SharedStudioUtils.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/UpdateService.java
Fix TUP-31909 Shared mode for Talend Studio doesn't work 
https://jira.talendforge.org/browse/TUP-31909
> Fix TUP-31909 Shared mode for Talend Studio doesn't work   5921

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/util/SharedStudioUtils.java
- main/plugins/org.talend.updates.runtime/src/main/java/org/talend/updates/runtime/service/UpdateService.java
Fix TUP-31909 Shared mode for Talend Studio doesn't work
https://jira.talendforge.org/browse/TUP-31909
> Fix TUP-31909 Shared mode for Talend Studio doesn't work   5921 (#4395)

- main/plugins/org.talend.common.ui.runtime/src/main/java/org/talend/commons/ui/runtime/image/ImageUtils.java
https://jira.talendforge.org/browse/TUP-31997
> fix(TUP-31997): Commandline fails start studio with error 'Could not load SWT library' on Ubuntu 18 LTS without UI

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/IRepositoryPrefConstants.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/runtime/projectsetting/ProjectPreferenceManager.java
- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
* feat(TUP-23337):Option to disable Job's screenshot creation.
https://jira.talendforge.org/browse/TUP-23337
* feat(TUP-23337):Option to disable Job's screenshot creation.
https://jira.talendforge.org/browse/TUP-23337
* feat(TUP-23337):Option to disable Job's screenshot creation.
https://jira.talendforge.org/browse/TUP-23337
* feat(TUP-23337):Option to disable Job's screenshot creation.
https://jira.talendforge.org/browse/TUP-23337
* feat(TUP-23337):Option to disable Job's screenshot creation.
https://jira.talendforge.org/browse/TUP-23337
> feat(TUP-23337):Option to disable Job's screenshot creation. (#4365)

- main/plugins/org.talend.librariesmanager/plugin.xml
- main/plugins/org.talend.migrationTool/src/org/talend/migrationtool/MigrationToolService.java
https://jira.talendforge.org/browse/TUP-31163
> chore(TUP-31163): upgrade daikon to 0.31.12

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/rowgenerator/data/AbstractTalendFunctionParser.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/rowgenerator/data/Function.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/rowgenerator/data/FunctionManager.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/rowgenerator/data/RoutineJarsFunctionParser.java
https://jira.talendforge.org/browse/TUP-31736
> fix(TUP-31736): add functions of custom routine jars to auto complete

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/designer/rowgenerator/data/RoutineJarsFunctionParser.java
https://jira.talendforge.org/browse/TUP-31736
> fix(TUP-31736): fix junit

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/ImportExportHandlersManager.java
https://jira.talendforge.org/browse/TUP-31880
> fix(TUP-31880)Build job failure due to joblet relationship didn't record

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
**Related PR**
- https://github.com/Talend/studio-full-master/pull/827
- https://github.com/Talend/tcommon-studio-se/pull/4413
- https://github.com/Talend/tcommon-studio-ee/pull/2022
- https://github.com/Talend/tdi-studio-se/pull/6405
> chore(master): bump component-runtime to 1.34.1

- main/plugins/org.talend.designer.maven.tos/resources/tcompv1/pom.xml
https://jira.talendforge.org/browse/TDI-46395
**Related PR**
- https://github.com/Talend/studio-full-master/pull/834
- https://github.com/Talend/tcommon-studio-se/pull/4423
- https://github.com/Talend/tcommon-studio-ee/pull/2029
- https://github.com/Talend/tdi-studio-se/pull/6422
> chore(studio731): bump component-runtime to 1.34.1

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/repository/IRepositoryPrefConstants.java
- main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/messages.properties
- main/plugins/org.talend.repository.items.importexport.ui/src/main/java/org/talend/repository/items/importexport/ui/wizard/imports/ImportItemsWizardPage.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportBasicHandler.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportCacheHelper.java
- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportDependencyRelationsHelper.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/io/FilesUtils.java
- test/plugins/org.talend.repository.items.importexport.test/src/org/talend/repository/items/importexport/handlers/imports/ImportDependencyRelationsHelperTest.java
branch"
https://jira.talendforge.org/browse/TUP-28580
> feat(TUP-28580):Replace current "Copy to branch", with "Copy from

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/maven/MavenArtifactsHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/model/service/LocalLibraryManager.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtil.java
https://jira.talendforge.org/browse/TUP-32088
> fix(TUP-32088): check remote snapshot artifacts

- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/nexus3/handler/AbsNexus3SearchHandler.java
- main/plugins/org.talend.librariesmanager/src/main/java/org/talend/librariesmanager/nexus/utils/ShareLibrariesUtil.java
https://jira.talendforge.org/browse/TUP-32088
> fix(TUP-32088: Libs re-uploaded to Nexus during each project login

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/database/conn/ConnParameterKeys.java
- main/plugins/org.talend.metadata.managment.ui/src/main/java/org/talend/metadata/managment/ui/utils/ExtendedNodeConnectionContextUtils.java
* fix(TBD-12715):Knox check HDFS service
* fix(TBD-12715):Knox check HDFS service
* fix(TBD-12715):Knox check HDFS service
> fix(TBD-12715):Knox check HDFS service (#4408)

- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
This reverts commit b2c74643a74895dc63419e5be7672535c75bc14b.
> Revert "fix(TBD-12184):Password field missing for tImpalaRow (#4472)"

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/model/metadata/designerproperties/SapJcoVersion.java
https://jira.talendforge.org/browse/TDI-46315
> fix(TDI-46315):sap component and sap metadata have different module name/mvnurl.(#4567)

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/threading/lockerbykey/LockerByKey.java
[7.2.1] TAC jobs cant be killed, and incorrect status reported
> [7.2.1] TAC jobs cant be killed, and incorrect status reported

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/utils/threading/lockerbykey/LockerByKey.java
TAC-15694
[7.2.1] TAC jobs cant be killed, and incorrect status reported
> TAC-15694 [7.2.1] TAC jobs cant be killed, and incorrect status reported

- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
project which exported from monthly patch studio>Studio
https://jira.talendforge.org/browse/TUP-33385
> fix(TUP-33385):Error pops up while logging on migrated project if the

- main/plugins/org.talend.designer.maven.tos/resources/tacokit/pom.xml
https://jira.talendforge.org/browse/TDI-46994
> fix(TDI-46994) Upgrade tck in studio 7.3

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/pendo/properties/PendoTMapProperties.java
https://jira.talendforge.org/browse/TUP-36710
> fix(TUP-36710):Some tMap data not show in pendo

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/pendo/PendoTrackDataUtil.java
- main/plugins/org.talend.core.runtime/src/main/java/org/talend/core/pendo/properties/PendoLoginProperties.java
https://jira.talendforge.org/browse/TUP-36780
> fix(TUP-36780):Add tracking to Studio

- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/dnd/DNDTableViewerHelper.java
- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/swt/tableviewer/TableViewerCreator.java
https://jira.talendforge.org/browse/TUP-41057
> fix(TUP-41057) add dnd support for dynamic setting's tableviewer

- main/plugins/org.talend.repository.items.importexport/src/main/java/org/talend/repository/items/importexport/handlers/imports/ImportDependencyRelationsHelper.java
dependent for db connection
https://jira.talendforge.org/browse/TUP-40871
> fix(TUP-40871):Import dependencies will not calculate the context

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/commons/utils/generation/JavaUtils.java
- main/plugins/org.talend.rcp/src/main/java/messages.properties
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
https://jira.talendforge.org/browse/TUP-40916
> chore(TUP-40916): Studio issues if Java version is > Java 17 

- main/plugins/org.talend.core.runtime/src/main/java/org/talend/commons/utils/generation/JavaUtils.java
- main/plugins/org.talend.rcp/src/main/java/messages.properties
- main/plugins/org.talend.rcp/src/main/java/org/talend/rcp/intro/Application.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/JavaVersion.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/StudioKeysFileCheck.java
- main/plugins/org.talend.utils/src/main/java/org/talend/utils/VersionException.java
https://jira.talendforge.org/browse/TUP-40916
> chore(TUP-40916): Studio issues if Java version is > Java 17

- main/plugins/org.talend.commons.runtime/src/org/talend/commons/runtime/xml/XMLFileUtil.java
https://jira.talendforge.org/browse/TUP-40457
> chore(TUP-40457) Errors in CommandLine log file

- main/plugins/org.talend.commons.ui/src/main/java/org/talend/commons/ui/utils/loader/MyURLClassLoader.java
- main/plugins/org.talend.metadata.managment/src/main/java/org/talend/core/model/metadata/builder/database/HotClassLoader.java
- main/plugins/org.talend.repository.metadata/src/main/java/org/talend/repository/ui/wizards/metadata/connection/database/DatabaseForm.java
Fix TUP-41299 Cannot connect to Oracle with patch R2023-11 
https://jira.talendforge.org/browse/TUP-41299
> Fix TUP-41299 Cannot connect to Oracle with patch R2023-11 (#6693)

- main/plugins/org.talend.signon.util/src/main/java/org/talend/signon/util/TMCRepositoryUtil.java
https://jira.talendforge.org/browse/TUP-41640
> fix(TUP-41640): Incorrect message when login TMC project

- main/plugins/org.talend.repository.localprovider/src/main/java/org/talend/repository/localprovider/model/LocalRepositoryFactory.java
- test/plugins/org.talend.repository.localprovider.test/src/org/talend/repository/localprovider/model/BaseRepositoryTest.java
- test/plugins/org.talend.repository.localprovider.test/src/org/talend/repository/localprovider/model/LocalRepositoryFactoryTest.java
https://jira.talendforge.org/browse/TUP-41099
> fix(TUP-41099) Author path not updated for all items when moved as group
